import { useEffect, useState } from 'react';
import { FileText, Presentation, Code, Download, FileType, AlertTriangle, Loader2, BookOpen, X, LayoutDashboard } from 'lucide-react';
import DOMPurify from 'dompurify';
import { authFetch } from '@/api/authFetch';
import { getDashboard } from '@/api/dashboards';
import { needsPreviewToken } from '@/lib/previewToken';
import DashboardViewer from '@/components/dashboard/DashboardViewer';
import FullStackDashboardViewer from '@/components/dashboard/FullStackDashboardViewer';
import DocxArtifactPreview from './DocxArtifactPreview';
import PptxArtifactPreview from './PptxArtifactPreview';
import PdfFaithfulPreview from './PdfFaithfulPreview';

/**
 * Render the agent-generated sidecar HTML preview without using an iframe.
 *
 * Why not an iframe?  Inside an iframe the browser draws its own native
 * scrollbar that lives outside the React tree.  On Linux/Chromium the
 * default overlay scrollbar is only shown while the cursor hovers the
 * scrollable area, and it gets proportionally smaller as less content
 * overflows — so once the user drags the right preview panel wider the
 * scrollbar effectively disappears and the user can't tell there's more
 * content to read.
 *
 * Rendering the same HTML directly via ``dangerouslySetInnerHTML`` lets the
 * outer ``overflow-auto`` container own the scrollbar, so it stays styled
 * like the rest of the app and is always visible regardless of panel width.
 *
 * The sidecar HTML is generated by the backend (LLM output) and served
 * unauthenticated from ``/api/artifacts/:id/preview``, so injecting it is
 * equivalent to what the iframe would have rendered.
 *
 * Because we render into our own DOM rather than an iframe, the sidecar's
 * inline `<style>` would otherwise leak globals like `body { margin: 0 }`
 * into the host page.  ``scopeSidecarHtml`` rewrites those rules to be
 * scoped to the preview root container and drops the `<html>` / `<body>`
 * wrappers so the document stays well-formed.
 */
const SIDECAR_ROOT_CLASS = 'sidecar-html-preview';

function scopeSidecarHtml(rawHtml) {
  if (!rawHtml) return '';
  const rootClass = SIDECAR_ROOT_CLASS;
  let html = rawHtml;
  // Strip outer wrappers the browser would otherwise treat as the document.
  html = html.replace(/<!DOCTYPE[^>]*>/gi, '');
  html = html.replace(/<\/?html[^>]*>/gi, '');
  html = html.replace(/<\/?body[^>]*>/gi, '');
  html = html.replace(/<\/?head[^>]*>/gi, '');
  // Scope every <style> block so its selectors only match inside our root.
  html = html.replace(/<style([^>]*)>([\s\S]*?)<\/style>/gi, (_match, attrs, css) => {
    const scoped = css.replace(
      /(^|[\s,>+~{(])(html|body)(?=[\s,>.:>+~({]|$)/gi,
      `$1.${rootClass}`,
    );
    return `<style data-sidecar-scope="${rootClass}"${attrs}>${scoped}</style>`;
  });
  return html;
}

function SidecarHtmlPreview({ src, className = '' }) {
  const [html, setHtml] = useState('');
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    setHtml('');
    setError(null);
    fetch(src, { credentials: 'same-origin' })
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.text();
      })
      .then((text) => {
        if (!cancelled) {
          // Sanitize LLM-generated HTML before injecting into the DOM. The
          // sidecar HTML is produced by the backend from model output and is
          // never trusted — without sanitization a crafted payload could
          // execute script in the host origin and steal the JWT from
          // localStorage. DOMPurify strips event handlers / script nodes
          // while preserving the <style> blocks (needed for scoped CSS) and
          // the data-sidecar-scope attribute injected by scopeSidecarHtml.
          const scoped = scopeSidecarHtml(text);
          const clean = DOMPurify.sanitize(scoped, {
            ADD_TAGS: ['style'],
            ADD_ATTR: ['data-sidecar-scope'],
          });
          setHtml(clean);
        }
      })
      .catch((e) => {
        if (!cancelled) setError(e.message || 'Failed to load preview');
      });
    return () => {
      cancelled = true;
    };
  }, [src]);

  if (error) {
    return (
      <div className={`flex h-full items-center justify-center p-6 text-sm text-muted-foreground ${className}`}>
        <AlertTriangle className="mr-2 h-4 w-4 text-destructive" />
        Could not load preview: {error}
      </div>
    );
  }

  if (!html) {
    return (
      <div className={`flex h-full items-center justify-center text-sm text-muted-foreground ${className}`}>
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
        Loading preview…
      </div>
    );
  }

  return (
    <div
      className={`${SIDECAR_ROOT_CLASS} h-full w-full overflow-auto bg-background ${className}`}
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}

const TYPE_ICON = {
  docx: FileText,
  pdf: FileText,
  pptx: Presentation,
  html: Code,
  html_report: FileText,
  dashboard: LayoutDashboard,
};

const TYPE_LABEL = {
  docx: 'Word Document',
  pdf: 'PDF Document',
  pptx: 'PowerPoint',
  html: 'HTML Page',
  html_report: 'Report',
  dashboard: 'Live Dashboard',
};

function formatSize(bytes) {
  if (bytes == null) return null;
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function LiveDashboardArtifactPreview({ dashboardId, artifact }) {
  const [dashboard, setDashboard] = useState(null);
  const [error, setError] = useState(null);

  // Full-stack pipeline dashboards are served as standalone apps (not stored in
  // the legacy `dashboards` table). Render them directly from the artifact's
  // served URL without any legacy fetch.
  if (artifact?.source === 'dashboard_app') {
    const appUrl = artifact.app_url || dashboardId;
    if (!appUrl) {
      return (
        <div className="flex h-full items-center justify-center p-6 text-sm text-muted-foreground">
          <AlertTriangle className="mr-2 h-4 w-4 text-destructive" />
          Dashboard URL is missing.
        </div>
      );
    }
    return (
      <FullStackDashboardViewer
        appUrl={appUrl}
        name={artifact.name}
        slug={artifact.slug}
      />
    );
  }

  useEffect(() => {
    if (!dashboardId) return undefined;
    let cancelled = false;
    setDashboard(null);
    setError(null);
    getDashboard(dashboardId)
      .then((data) => {
        if (!cancelled) setDashboard(data);
      })
      .catch((e) => {
        if (!cancelled) setError(e.message || 'Failed to load dashboard');
      });
    return () => { cancelled = true; };
  }, [dashboardId]);

  if (!dashboardId) {
    return (
      <div className="flex h-full items-center justify-center p-6 text-sm text-muted-foreground">
        <AlertTriangle className="mr-2 h-4 w-4 text-destructive" />
        Dashboard id is missing.
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex h-full items-center justify-center p-6 text-sm text-muted-foreground">
        <AlertTriangle className="mr-2 h-4 w-4 text-destructive" />
        Could not load dashboard: {error}
      </div>
    );
  }

  if (!dashboard) {
    return (
      <div className="flex h-full items-center justify-center text-sm text-muted-foreground">
        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
        Loading dashboard…
      </div>
    );
  }

  return <DashboardViewer dashboard={dashboard} canEdit={!!dashboard.can_edit} />;
}

/**
 * ArtifactPreviewPane — Claude-style right-anchored document preview.
 *
 * Rendered inside a resizable Panel beside the chat (see Chat.jsx). Unlike
 * the older ArtifactPreviewSheet (a modal overlay), this pane stays anchored
 * to the right of the conversation so the user reads the document alongside
 * the chat without losing context.
 *
 * Body rendering reuses the existing preview pipeline:
 *   - docx  → DocxArtifactPreview  (mammoth HTML via /artifacts/:id/preview?format=html)
 *   - pptx  → PptxArtifactPreview  (python-pptx HTML)
 *   - html  → sandboxed iframe
 *   - other → iframe if a preview_url exists, else a graceful fallback
 */
export default function ArtifactPreviewPane({ artifact, onClose }) {
  // Default to 'html' (mammoth/pptx2html rendered content) so the chat
  // preview matches the "Files in this task" modal. Previously defaulted
  // to 'document' (PDF render via LibreOffice) which only showed page 1
  // of multi-page documents and looked visually different from the modal.
  // Users can still toggle to 'pdf' for a faithful page-by-page render.
  const [viewMode, setViewMode] = useState('html');
  const _artifactIdForReset = artifact?.id || artifact?.artifact_id;
  useEffect(() => { setViewMode('html'); }, [_artifactIdForReset]);

  // Null-safe derivations for the preview-token hook below (hooks must run
  // unconditionally, before the ``if (!artifact) return null`` guard). The
  // plain-iframe branch points at ``preview_url`` =
  // ``/api/automations/files/{id}/preview`` — a Bearer-authenticated route an
  // iframe cannot send the Authorization header to, so loading it directly
  // returned ``401 {"detail":"Authentication required"}`` and the browser
  // rendered that JSON inside the pane (the reported bug). Mirror
  // InlineArtifactPreview: mint a short-lived signed token and point the
  // iframe at the returned ``?token=`` URL. ``/api/artifacts/{id}/preview`` is
  // served unauthenticated → used as-is (needsPreviewToken → false).
  const _artifactId = artifact?.id || artifact?.artifact_id;
  const _previewUrl = artifact?.preview_url || artifact?.previewUrl;
  const _isOffice = artifact?.type === 'docx' || artifact?.type === 'pptx' || artifact?.type === 'xlsx';
  const _hasSidecar = !!(artifact?.preview_artifact_id || artifact?.previewArtifactId);
  const _hasPreview = (artifact?.has_preview ?? artifact?.hasPreview) && !!_previewUrl;
  const _wantsIframe = !_isOffice && !_hasSidecar && _hasPreview;
  const _tokenRequired = _wantsIframe && needsPreviewToken(_previewUrl);
  const [signedIframeUrl, setSignedIframeUrl] = useState(null);
  const [iframeTokenFailed, setIframeTokenFailed] = useState(false);
  useEffect(() => {
    if (!_tokenRequired || !_artifactId) return undefined;
    let cancelled = false;
    setIframeTokenFailed(false);
    setSignedIframeUrl(null);
    authFetch(`/api/automations/files/${_artifactId}/preview-token`, { method: 'POST' })
      .then((res) => {
        if (!res || !res.ok) throw new Error(`mint failed: ${res && res.status}`);
        return res.json();
      })
      .then((data) => {
        if (cancelled) return;
        if (data?.url) setSignedIframeUrl(data.url);
        else setIframeTokenFailed(true);
      })
      .catch(() => { if (!cancelled) setIframeTokenFailed(true); });
    return () => { cancelled = true; };
  }, [_tokenRequired, _artifactId]);

  if (!artifact) return null;

  const Icon = TYPE_ICON[artifact.type] || FileType;
  const label = TYPE_LABEL[artifact.type] || artifact.type;
  const size = formatSize(artifact.file_size);
  const title = artifact.title || artifact.file_name || 'Artifact';
  // Artifacts coming from the chat-message stream use ``artifact_id``
  // (canonical from the backend's ``_collect_artifact_results``) while
  // artifacts read straight from the artifacts entity use ``id``.
  // Accept either so the preview works regardless of where the
  // artifact object originated — without this, the DOCX/PPTX
  // previewer would receive an ``undefined`` id, the ``useEffect``
  // would no-op, and the pane would spin on "Loading document…"
  // forever (the exact bug the user reported).
  const artifactId = artifact.id || artifact.artifact_id;
  const dashboardId = artifact.dashboard_id || artifact.dashboardId || (artifact.type === 'dashboard' ? artifactId : null);
  const previewUrl = artifact.preview_url || artifact.previewUrl;
  const fileUrl = artifact.file_url || artifact.download_url;
  const hasPreview = (artifact.has_preview ?? artifact.hasPreview) && !!previewUrl;
  // Sidecar rich-HTML preview (Layer 2 of the "one card per file
  // format" plan).  When the backend attached a rich-HTML sibling to
  // a docx/pptx/xlsx artifact, it sets this field.  We prefer it
  // over the plain mammoth/pptx2html rendering.
  const previewArtifactId = artifact.preview_artifact_id || artifact.previewArtifactId;
  const sidecarPreviewUrl = previewArtifactId
    ? `/api/artifacts/${previewArtifactId}/preview`
    : null;

  // Office-file artifacts (docx/pptx/xlsx) have three view modes:
  //   'html'    — mammoth/pptx2html rendition (default; matches Files modal)
  //   'pdf'     — faithful PDF render via LibreOffice (page-by-page)
  //   'summary' — sibling rich-HTML artifact (sidecar, when present)
  const isOfficeDoc = artifact.type === 'docx' || artifact.type === 'pptx' || artifact.type === 'xlsx';
  const showToggle = isOfficeDoc; // always show the toggle for office docs

  // Automation-file artifacts live in the AutomationFile table (not the
  // Artifact table) and are served by a different endpoint. Routing them
  // through the Artifact-table endpoint returns 404 — the bug the user
  // reported with "Daily Sales Data Sync.docx" showing "Preview
  // unavailable (HTTP 404)". Use the automation-files endpoint when the
  // artifact is sourced from an automation run; null otherwise (the
  // PdfFaithfulPreview default will then build the artifact endpoint).
  const isAutomationFile = artifact.source === 'automation_file';
  const pdfPreviewUrl = isAutomationFile
    ? `/api/automations/files/${artifactId}/preview`
    : null;

  // The src the iframe should actually load: the signed ``?token=`` URL minted
  // by the hook above when the route is Bearer-authenticated (automation
  // files), else the plain ``preview_url`` (unauthenticated artifact sidecars).
  // ``_tokenRequired``/``signedIframeUrl``/``iframeTokenFailed`` come from the
  // hook state declared above the ``if (!artifact) return null`` guard.
  const iframeSrc = _tokenRequired ? signedIframeUrl : previewUrl;

  return (
    <div className="flex h-full flex-col overflow-hidden rounded-xl border border-border bg-card shadow-sm">
      {/* Header */}
      <div className="flex shrink-0 items-center justify-between gap-2 border-b border-border bg-secondary/40 px-4 py-3">
        <div className="flex min-w-0 items-center gap-2.5">
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-primary/10 text-primary">
            <Icon className="h-4 w-4" />
          </div>
          <div className="min-w-0">
            <p className="truncate text-sm font-medium text-foreground">{title}</p>
            <p className="text-[11px] text-muted-foreground">
              {label}
              {size && <span className="opacity-60"> · {size}</span>}
            </p>
          </div>
        </div>
        <div className="flex shrink-0 items-center gap-1.5">
          {showToggle && (
            <div className="flex items-center rounded-md border border-border bg-secondary/40 p-0.5">
              <button
                onClick={() => setViewMode('html')}
                className={`rounded px-2 py-1 text-xs font-medium transition-colors ${viewMode === 'html'
                    ? 'bg-background text-foreground shadow-sm'
                    : 'text-muted-foreground hover:text-foreground'
                  }`}
              >
                HTML
              </button>
              <button
                onClick={() => setViewMode('document')}
                className={`rounded px-2 py-1 text-xs font-medium transition-colors ${viewMode === 'document'
                    ? 'bg-background text-foreground shadow-sm'
                    : 'text-muted-foreground hover:text-foreground'
                  }`}
              >
                PDF
              </button>
              {sidecarPreviewUrl && (
                <button
                  onClick={() => setViewMode('summary')}
                  className={`rounded px-2 py-1 text-xs font-medium transition-colors ${viewMode === 'summary'
                      ? 'bg-background text-foreground shadow-sm'
                      : 'text-muted-foreground hover:text-foreground'
                    }`}
                >
                  Summary
                </button>
              )}
            </div>
          )}
          {artifact.ms_word_open_url && (
            <a
              href={artifact.ms_word_open_url}
              target="_blank"
              rel="noreferrer"
              title="Open in Microsoft Word Online (sends the file to Microsoft)"
              className="inline-flex items-center gap-1 rounded-md border border-blue-500/40 bg-blue-500/10 px-2 py-1.5 text-xs font-medium text-blue-600 transition-colors hover:bg-blue-500/20 dark:text-blue-300"
            >
              <BookOpen className="h-3.5 w-3.5" />
              <span className="hidden lg:inline">Word</span>
            </a>
          )}
          {fileUrl && (
            <a
              href={fileUrl}
              download={artifact.file_name}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1 rounded-md border border-border bg-background px-2 py-1.5 text-xs font-medium text-foreground transition-colors hover:bg-secondary"
            >
              <Download className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Download</span>
            </a>
          )}
          <button
            onClick={onClose}
            title="Close preview (Esc)"
            className="inline-flex items-center justify-center rounded-md p-1.5 text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
          >
            <X className="h-4 w-4" />
          </button>
        </div>
      </div>

      {/* Body */}
      {/* ``min-h-0`` is critical here.  In a flex column, the default
          ``min-height: auto`` on a child means the flex item won't
          shrink below its content's natural height.  Without
          ``min-h-0`` the body div would grow to fit ALL of the
          sidecar HTML's content — and the user couldn't scroll
          because there's no overflow.  ``overflow-auto`` lets the
          body own the scrollbar, which stays styled like the rest of
          the app and is always visible regardless of panel width. */}
      <div className="flex-1 min-h-0 overflow-auto bg-background">
        {/* Sidecar rich-HTML preview (Layer 2).  When the backend
            attached a sibling HTML artifact to this file-format
            artifact, prefer that interactive dashboard over the plain
            mammoth/pptx2html rendering.  The user explicitly asked
            for the docx card to look as interactive as the HTML one
            they liked.

            Rendered as in-page HTML (not an iframe) so the parent's
            own scrollbar handles scrolling.  An iframe's native
            scrollbar is invisible on Linux/Chromium once the preview
            panel is dragged wider, which made the content look frozen
            — see the regression the user filed. */}
        {artifact.type === 'dashboard' ? (
          <LiveDashboardArtifactPreview dashboardId={dashboardId} artifact={artifact} />
        ) : isOfficeDoc ? (
          /* Office-file artifacts (docx/pptx/xlsx): three view modes.
             'html' is the default (matches Files in this task modal).
             'document' is a faithful PDF render via LibreOffice.
             'summary' is the sibling rich-HTML sidecar artifact. */
          viewMode === 'summary' && sidecarPreviewUrl ? (
            <SidecarHtmlPreview
              key={`sidecar-${artifactId}-${previewArtifactId}`}
              src={sidecarPreviewUrl}
            />
          ) : viewMode === 'document' ? (
            <PdfFaithfulPreview
              key={`pdf-${artifactId}`}
              artifactId={artifactId}
              previewUrl={pdfPreviewUrl}
              title={title}
              downloadUrl={fileUrl}
              fallback={
                artifact.type === 'docx' ? (
                  <DocxArtifactPreview
                    key={`docx-${artifactId}`}
                    artifactId={artifactId}
                    outline={artifact.preview_outline || []}
                    title={title}
                    downloadUrl={fileUrl}
                  />
                ) : (
                  <PptxArtifactPreview
                    key={`pptx-${artifactId}`}
                    artifactId={artifactId}
                    outline={artifact.preview_outline || []}
                    title={title}
                    downloadUrl={fileUrl}
                  />
                )
              }
            />
          ) : (
            /* 'html' (default) — matches the Files in this task modal. */
            artifact.type === 'docx' ? (
              <DocxArtifactPreview
                key={`docx-${artifactId}`}
                artifactId={artifactId}
                outline={artifact.preview_outline || []}
                title={title}
                downloadUrl={fileUrl}
              />
            ) : (
              <PptxArtifactPreview
                key={`pptx-${artifactId}`}
                artifactId={artifactId}
                outline={artifact.preview_outline || []}
                title={title}
                downloadUrl={fileUrl}
              />
            )
          )
        ) : sidecarPreviewUrl ? (
          /* Non-office artifacts: prefer sidecar rich HTML (unchanged). */
          <SidecarHtmlPreview
            key={`sidecar-${artifactId}-${previewArtifactId}`}
            src={sidecarPreviewUrl}
          />
        ) : hasPreview ? (
          // Token-protected automation-file previews: wait for the signed
          // URL (loading), surface a graceful error if minting failed, else
          // load the signed/plain src. Unauthenticated sidecar previews load
          // previewUrl directly (iframeSrc === previewUrl).
          iframeTokenFailed ? (
            <NoPreviewFallback
              title={title}
              label={label}
              size={size}
              fileUrl={fileUrl}
              fileName={artifact.file_name}
            />
          ) : !iframeSrc ? (
            <div className="flex h-full items-center justify-center text-sm text-muted-foreground">
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              Loading preview…
            </div>
          ) : (
            <iframe
              key={`iframe-${artifactId}`}
              src={iframeSrc}
              title={title}
              className="h-full w-full border-0"
              sandbox={artifact.type === 'html' ? 'allow-scripts' : undefined}
            />
          )
        ) : (artifact.is_pending || (!previewUrl && !fileUrl)) ? (
          <PendingPreview title={title} label={label} />
        ) : (
          <NoPreviewFallback
            title={title}
            label={label}
            size={size}
            fileUrl={fileUrl}
            fileName={artifact.file_name}
          />
        )}
      </div>
    </div>
  );
}

function PendingPreview({ title, label }) {
  return (
    <div className="flex h-full flex-col items-center justify-center gap-4 px-6 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-full bg-blue-500/10">
        <Loader2 className="h-6 w-6 animate-spin text-blue-500" />
      </div>
      <div>
        <p className="text-sm font-medium text-foreground">{title}</p>
        <p className="mt-1 text-xs text-muted-foreground">Generating preview…</p>
        <p className="mt-0.5 text-[11px] text-muted-foreground/60">{label}</p>
      </div>
    </div>
  );
}

function NoPreviewFallback({ title, label, size, fileUrl, fileName }) {
  return (
    <div className="flex h-full flex-col items-center justify-center gap-4 px-6 text-center">
      <div className="flex h-14 w-14 items-center justify-center rounded-full bg-amber-500/10">
        <AlertTriangle className="h-6 w-6 text-amber-500" />
      </div>
      <div>
        <p className="text-sm font-medium text-foreground">{title}</p>
        <p className="mt-1 text-xs text-muted-foreground">Preview unavailable for this file type.</p>
        <p className="mt-0.5 text-[11px] text-muted-foreground/60">
          {label}
          {size ? ` · ${size}` : ''}
        </p>
      </div>
      {fileUrl && (
        <a
          href={fileUrl}
          download={fileName}
          target="_blank"
          rel="noreferrer"
          className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90"
        >
          <Download className="h-4 w-4" />
          Download File
        </a>
      )}
    </div>
  );
}
