"""Automation API — execution history, file downloads, manual triggers.

Provides:
* GET  /api/chat-sessions/{id}/automation       — panel payload (Manus-style)
* GET  /api/automations/{id}/executions         — list past runs
* GET  /api/automations/executions/{id}         — get a single execution
* GET  /api/automations/executions/{id}/details — full run + files + conversation_id
* GET  /api/automations/executions/{id}/files   — list files generated by a run
* GET  /api/automations/files/{id}/download     — download a generated file
* POST /api/automations/{id}/run                — trigger an immediate run
* POST /api/automations/{id}/recompute          — recompute next_run_at
* POST /api/automations/{id}/toggle             — pause/resume
* POST /api/automations/{id}/skip-confirmation  — toggle skip_confirmation
* POST /api/automations/parse-schedule          — parse a schedule string client-side
"""

from __future__ import annotations

import asyncio
import json
import logging
import mimetypes
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse, Response, StreamingResponse
from pydantic import BaseModel
from sqlalchemy import update
from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.deps import get_current_user_optional, get_current_user_required
from app.models.automation_task import AutomationTask
from app.models.automation_execution import AutomationExecution
from app.models.automation_file import AutomationFile
from app.models.user import User
from app.models.user_file import UserFile
from app.services.automation_executor import classify_run_failure_reason

router = APIRouter(prefix="/automations", tags=["automations"])
logger = logging.getLogger(__name__)


def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


def _assert_tenant(obj, user: User) -> None:
    """Raise 404 if ``obj`` doesn't belong to ``user``'s org.

    Returns 404 (not 403) so the mere existence of another tenant's
    resources can't be inferred — closes the IDOR vector on the
    automation read/download endpoints.
    """
    org_id = getattr(user, "org_id", None)
    if org_id is not None and getattr(obj, "org_id", None) != org_id:
        raise HTTPException(status_code=404, detail="Not found")


_PREVIEWABLE_FILE_TYPES = {
    "csv", "docx", "gif", "htm", "html", "jpeg", "jpg", "json", "md",
    "pdf", "png", "pptx", "svg", "txt", "webp", "xlsx",
}


def _serialize_automation_file(file_record: AutomationFile) -> dict:
    """Return one stable deliverable payload for run, chat, and file views."""
    file_type = (file_record.file_type or Path(file_record.name).suffix).lower().lstrip(".")
    file_url = file_record.file_url or f"/api/automations/files/{file_record.id}/download"
    mime_type = file_record.mime_type or mimetypes.guess_type(file_record.name)[0]
    created_date = getattr(file_record, "created_date", None)
    if hasattr(created_date, "isoformat"):
        created_date = created_date.isoformat()

    return {
        "id": file_record.id,
        "automation_file_id": file_record.id,
        "name": file_record.name,
        "file_name": file_record.name,
        "type": file_type,
        "file_type": file_type,
        "mime_type": mime_type,
        "size": file_record.size,
        "file_size": file_record.size,
        "url": file_url,
        "file_url": file_url,
        "preview_url": f"/api/automations/files/{file_record.id}/preview",
        "has_preview": file_type in _PREVIEWABLE_FILE_TYPES,
        "source": "automation_file",
        "created_date": created_date,
    }


def _chat_message_artifacts_for_files(files: list[AutomationFile]) -> list[dict]:
    """Map ``AutomationFile`` rows onto the artifact shape the chat surface
    already understands.

    The chat-side ``ArtifactCardList`` was built around artifact payloads from
    live chat runs. The deliverable serializer (above) is the same shape plus
    a few extras (``has_preview``, ``created_date``) the card list gracefully
    ignores, so we use it directly and add the chat-friendly ``title`` alias
    so cards keep showing the file name when ``title`` is what they read.
    """
    return [
        {
            "id": f.id,
            "artifact_id": f.id,
            "automation_file_id": f.id,
            "title": f.name,
            "name": f.name,
            "file_name": f.name,
            "type": (f.file_type or Path(f.name).suffix).lower().lstrip("."),
            "file_type": (f.file_type or Path(f.name).suffix).lower().lstrip("."),
            "file_size": f.size,
            "size": f.size,
            "url": f.file_url or f"/api/automations/files/{f.id}/download",
            "file_url": f.file_url or f"/api/automations/files/{f.id}/download",
            "preview_url": f"/api/automations/files/{f.id}/preview",
            "has_preview": (f.file_type or Path(f.name).suffix).lower().lstrip(".")
            in _PREVIEWABLE_FILE_TYPES,
            "source": "automation_file",
        }
        for f in files
    ]


# ---------------------------------------------------------------------------
# Schedules
# ---------------------------------------------------------------------------

class ParseScheduleRequest(BaseModel):
    schedule: str
    timezone: str | None = None


@router.post("/parse-schedule")
def parse_schedule_endpoint(req: ParseScheduleRequest):
    """Parse a free-form schedule string into a cron expression + next run time.

    ``timezone`` (optional IANA name, e.g. "Asia/Shanghai") controls which
    timezone the cron is interpreted in; the returned ``next_run_at`` is
    always UTC-naive so the client can display it in the user's locale.
    """
    from app.services.schedule_parser import parse_schedule, next_run_at, describe_schedule
    try:
        cron = parse_schedule(req.schedule)
        nxt = next_run_at(cron, tz_name=req.timezone)
        return {
            "success": True,
            "cron": cron,
            "next_run_at": nxt.isoformat(),
            "description": describe_schedule(cron),
            "timezone": req.timezone or "UTC",
        }
    except Exception as e:
        return {"success": False, "error": str(e)}


# ---------------------------------------------------------------------------
# Per-session panel (Manus-style "Scheduled" side panel)
# ---------------------------------------------------------------------------

@router.get("/by-session/{session_id}")
def get_automation_by_session(
    session_id: str,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_required),
):
    """Return the AutomationTask linked to a chat session, plus its recent
    executions. Used by the Manus-style "Scheduled" side panel that appears
    only in chat sessions that have an automation.

    Returns ``{"task": null}`` if the session has no automation — the
    frontend uses this to decide whether to render the Scheduled button.

    Scoped to the caller's org so one tenant can't enumerate another's
    automations by guessing session ids.
    """
    task = db.query(AutomationTask).filter(
        AutomationTask.session_id == session_id,
        AutomationTask.org_id == user.org_id,
        AutomationTask.is_deleted == False,  # noqa: E712
    ).order_by(AutomationTask.created_date.desc()).first()
    if not task:
        return {"task": None, "executions": []}

    # Attach the last N executions with their file counts.
    rows = db.query(AutomationExecution).filter(
        AutomationExecution.automation_task_id == task.id,
        AutomationExecution.is_deleted == False,  # noqa: E712
    ).order_by(AutomationExecution.created_date.desc()).limit(20).all()

    executions = []
    for r in rows:
        d = r.to_dict()
        files = db.query(AutomationFile).filter(
            AutomationFile.execution_id == r.id,
            AutomationFile.is_deleted == False,  # noqa: E712
        ).all()
        d["files"] = [_serialize_automation_file(f) for f in files]
        d["file_count"] = len(files)
        # Phase 5 (Tier A #2): surface the quality-gate decision + held_back
        # flag so the Scheduled panel can explain why a completed run has no
        # deliverable file (low-confidence output was held back).
        _qg = (
            (r.output_data or {}).get("quality_gate")
            if isinstance(r.output_data, dict) else None
        )
        d["quality_gate"] = _qg
        d["held_back"] = bool(_qg and not _qg.get("passed", True))
        # Per-run conversation id — surfaced explicitly for the run-log
        # "Open in chat" deep-link (the executor creates one conversation
        # per execution, stored in output_data.conversation_id).
        d["conversation_id"] = (
            (r.output_data or {}).get("conversation_id")
            if isinstance(r.output_data, dict) else None
        )
        executions.append(d)

    return {
        "task": task.to_dict(),
        "executions": executions,
    }


def _ext_from_url(file_url: str | None) -> str:
    """Extract lowercase file extension from a URL, default to 'docx'."""
    import re
    if not file_url:
        return "docx"
    m = re.search(r"\.([a-z0-9]+)(?:\?|$)", file_url, re.IGNORECASE)
    return m.group(1).lower() if m else "docx"


def _report_resource_kind(report_type: str | None, file_type: str) -> str:
    """Map Report.type + file extension to a resource_kind value.

    - ``dashboard`` → ``"dashboard"`` (triggers DashboardArtifactPreview)
    - ``html``/``htm`` extension → ``"html_file"`` (triggers sandbox iframe)
    - everything else → ``"report"``
    """
    rt = (report_type or "").lower()
    if rt == "dashboard":
        return "dashboard"
    if file_type in ("html", "htm"):
        return "html_file"
    return "report"


@router.get("/by-session/{session_id}/files")
def list_files_by_session(
    session_id: str,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_required),
):
    """Return the AutomationTask (if any) for this chat session plus every file
    reachable from it.

    Primary list: AI-generated ``AutomationFile`` rows from all executions of the
    session's task. ``_source="ai_generated"`` so the UI can label them.
    Secondary list: any ``UserFile`` rows uploaded to this session, with
    ``_source="uploaded"`` (kept so chat uploads still surface even when the
    session has no automation).

    Used by the chat-side "Files in this task" panel so triggered automation
    runs surface their generated artifacts even though executions aren't
    visible in chat. Scoped to the caller's org, mirroring ``/by-session``.
    """
    task = db.query(AutomationTask).filter(
        AutomationTask.session_id == session_id,
        AutomationTask.org_id == user.org_id,
        AutomationTask.is_deleted == False,  # noqa: E712
    ).order_by(AutomationTask.created_date.desc()).first()

    files: list[dict] = []

    if task:
        rows = db.query(AutomationFile).filter(
            AutomationFile.automation_task_id == task.id,
            AutomationFile.is_deleted == False,  # noqa: E712
        ).order_by(AutomationFile.created_date.desc()).limit(200).all()
        for f in rows:
            d = _serialize_automation_file(f)
            d["_source"] = "ai_generated"
            d["execution_id"] = f.execution_id
            files.append(d)

    # UserFile uploads for this session (secondary; lets manual uploads show
    # even when no task is linked to the session).
    user_rows = db.query(UserFile).filter(
        UserFile.session_id == session_id,
        UserFile.is_deleted == False,  # noqa: E712
    ).order_by(UserFile.updated_date.desc()).limit(200).all()
    for u in user_rows:
        d = u.to_dict()
        d["_source"] = "uploaded"
        files.append(d)

    # Report rows for this session (agent-generated DOCX reports created in
    # chat via create_resource type=report). Normalize to same shape as
    # AutomationFile/UserFile so the frontend ChatFilesModal renders them
    # without any code change.
    from app.models.report import Report as ReportModel
    report_rows = db.query(ReportModel).filter(
        ReportModel.session_id == session_id,
        ReportModel.is_deleted == False,  # noqa: E712
    ).order_by(ReportModel.updated_date.desc()).limit(200).all()
    for r in report_rows:
        # Derive file_type from file_url extension; default to docx
        ft = _ext_from_url(r.file_url)
        # Derive resource_kind: dashboard/HTML get special treatment;
        # everything else is "report"
        kind = _report_resource_kind(r.type, ft)
        files.append({
            "id": r.id,
            "name": r.title,
            "file_type": ft,
            "file_url": r.file_url,
            "source": "ai_generated",
            "resource_kind": kind,
            "project": r.project,
            "project_id": r.project_id,
            "session_id": r.session_id,
            "agent_name": r.agent_name,
            "updated_date": r.updated_date.isoformat() if r.updated_date else None,
            "created_date": r.created_date.isoformat() if r.created_date else None,
            "_source": "ai_generated",
            "_entity_type": "Report",
        })

    # Artifacts stored in chat_messages.artifacts JSON column for this session.
    # The agent stores generated files (DOCX, PDF, HTML) as Artifacts in
    # chat_messages.artifacts (per-message), not always as Report entities.
    # Include them here so the "Files in this task" modal surfaces everything
    # the agent produced in this session.
    from app.models.chat_message import ChatMessage
    seen_artifact_ids: set[str] = set()
    msg_rows = db.query(ChatMessage).filter(
        ChatMessage.session_id == session_id,
        ChatMessage.is_deleted == False,  # noqa: E712
        ChatMessage.artifacts.isnot(None),
    ).all()
    for m in msg_rows:
        arts = m.artifacts
        if not isinstance(arts, list):
            continue
        for art in arts:
            if not isinstance(art, dict):
                continue
            aid = str(art.get("artifact_id") or art.get("id") or "")
            if not aid or aid in seen_artifact_ids:
                continue
            seen_artifact_ids.add(aid)
            raw_file_url = art.get("file_url") or ""
            raw_preview_url = art.get("preview_url") or ""
            ft = _ext_from_url(raw_file_url) or (art.get("type") or "").lower() or "docx"
            kind = _report_resource_kind(art.get("type"), ft)
            # For Office formats (DOCX/PPTX/XLSX), prefer the HTML preview
            # variant (mammoth/pptx-renderer) which renders cleanly inline
            # in a sandboxed iframe. Fall back to PDF preview, then to the
            # raw file_url (which is the download endpoint and will
            # trigger a download instead of rendering).
            OFFICE = {"doc", "docx", "ppt", "pptx", "pps", "ppsx", "xls", "xlsx", "odt", "ods", "odp", "rtf"}
            is_office = ft in OFFICE
            primary_url = raw_file_url
            if is_office and raw_preview_url:
                # If the preview URL points at the artifact preview endpoint
                # (ends with /preview), append ?format=html so the user gets
                # the mammoth/pptx HTML rendition (clean inline render)
                # instead of a PDF (which would still work but feels heavy
                # in a small modal).
                if ft in ("docx", "pptx"):
                    if "?" in raw_preview_url:
                        primary_url = raw_preview_url + "&format=html"
                    else:
                        primary_url = raw_preview_url + "?format=html"
                else:
                    # XLSX: no HTML preview, use cached PDF instead
                    primary_url = raw_preview_url
            elif not is_office and raw_preview_url:
                # PDF/image previews: use the cached preview blob directly
                primary_url = raw_preview_url
            files.append({
                "id": aid,
                "name": art.get("title") or art.get("file_name") or "Artifact",
                "file_type": ft,
                "file_url": primary_url or raw_file_url,
                "preview_url": raw_preview_url,
                "download_url": raw_file_url,
                "file_size": art.get("file_size"),
                "mime_type": art.get("mime_type"),
                "source": "ai_generated",
                "resource_kind": kind,
                "session_id": session_id,
                "agent_name": m.role if m.role == "assistant" else None,
                "message_id": m.id,
                "updated_date": m.updated_date.isoformat() if m.updated_date else None,
                "created_date": m.created_date.isoformat() if m.created_date else None,
                "_source": "ai_generated",
                "_entity_type": "Artifact",
            })

    return {
        "task_id": task.id if task else None,
        "task_name": task.name if task else None,
        "files": files,
    }


# ---------------------------------------------------------------------------
# Executions
# ---------------------------------------------------------------------------

@router.get("/{task_id}/executions")
def list_executions(
    task_id: str,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db),
):
    task = db.query(AutomationTask).filter(
        AutomationTask.id == task_id,
        AutomationTask.is_deleted == False,
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Automation task not found")

    rows = db.query(AutomationExecution).filter(
        AutomationExecution.automation_task_id == task_id,
        AutomationExecution.is_deleted == False,
    ).order_by(AutomationExecution.created_date.desc()).limit(limit).all()

    out = []
    for r in rows:
        d = r.to_dict()
        # Attach file count + urls.
        files = db.query(AutomationFile).filter(
            AutomationFile.execution_id == r.id,
            AutomationFile.is_deleted == False,
        ).all()
        d["files"] = [_serialize_automation_file(f) for f in files]
        d["file_count"] = len(files)
        if d.get("status") == "failed" and d.get("error"):
            d["error_code"] = classify_run_failure_reason(d["error"])
        # Phase 5 (Tier A #2): surface the quality-gate decision + held_back
        # flag so the execution list (dedicated automation page) can explain
        # a completed run with no deliverable file.
        _qg = (
            (r.output_data or {}).get("quality_gate")
            if isinstance(r.output_data, dict) else None
        )
        d["quality_gate"] = _qg
        d["held_back"] = bool(_qg and not _qg.get("passed", True))
        # Per-run conversation id (the executor creates one AgentConversation
        # per execution). Surfaced explicitly so the run-log "Open in chat"
        # deep-link doesn't have to dig through the output_data blob.
        d["conversation_id"] = (
            (r.output_data or {}).get("conversation_id")
            if isinstance(r.output_data, dict) else None
        )
        out.append(d)
    return {"executions": out, "total": len(out)}


@router.get("/executions/{execution_id}")
def get_execution(execution_id: str, db: Session = Depends(get_db)):
    row = db.query(AutomationExecution).filter(
        AutomationExecution.id == execution_id,
    ).first()
    if not row:
        raise HTTPException(status_code=404, detail="Execution not found")
    d = row.to_dict()
    files = db.query(AutomationFile).filter(
        AutomationFile.execution_id == execution_id,
        AutomationFile.is_deleted == False,
    ).all()
    d["files"] = [_serialize_automation_file(f) for f in files]
    return d


@router.get("/executions/{execution_id}/status")
def get_execution_status(execution_id: str, db: Session = Depends(get_db)):
    """Lightweight poll payload for the in-progress execution drawer.

    Returns a compact snapshot — status, activity steps, current phase,
    elapsed seconds, error, and the skill calls recorded against this run —
    so the frontend can drive a 2s-polling drawer without pulling the full
    ``/details`` payload each tick.

    404-tolerant: the execution row may not be committed yet in the first
    poll window after ``POST /run`` (the dispatcher creates the row
    asynchronously). In that case we return ``{"status": "pending",
    "exists": false}`` with HTTP 200 so the drawer keeps polling instead of
    erroring out on a transient race.
    """
    row = db.query(AutomationExecution).filter(
        AutomationExecution.id == execution_id,
    ).first()
    if not row:
        return {
            "status": "pending",
            "exists": False,
            "steps": [],
            "skill_calls": [],
        }

    # Skill invocations recorded against this run (via SkillExecutionRecorder,
    # which stamps SkillRun.execution_id using the executor's contextvar).
    skill_calls: list[dict] = []
    try:
        from app.models.skill_run import SkillRun
        runs = db.query(SkillRun).filter(
            SkillRun.execution_id == execution_id,
        ).order_by(SkillRun.created_date.asc()).all()
        for r in runs:
            _in = r.input_json if isinstance(r.input_json, dict) else {}
            skill_calls.append({
                "skill_name": _in.get("skill_name") or r.skill_profile_id,
                "action": _in.get("action"),
                "agent_name": _in.get("agent_name"),
                "status": r.status,
                "duration_ms": r.duration_ms,
                "at": r.created_date.isoformat() if r.created_date else None,
            })
    except Exception as exc:  # noqa: BLE001
        logger.debug("get_execution_status: skill_calls lookup failed (non-fatal): %s", exc)

    started_at = row.started_at
    if started_at is not None and hasattr(started_at, "isoformat"):
        started_at_iso = started_at.isoformat()
        if row.completed_at is not None and hasattr(row.completed_at, "isoformat"):
            elapsed = (row.completed_at - started_at).total_seconds()
        else:
            # DB DateTime columns are timezone-naive (UTC). Subtract a naive
            # "now" so we don't hit "can't subtract offset-naive and
            # offset-aware datetimes" on live (running) executions.
            now = datetime.now(timezone.utc)
            if started_at.tzinfo is None:
                now = now.replace(tzinfo=None)
            elapsed = (now - started_at).total_seconds()
        elapsed = max(0.0, elapsed)
    else:
        started_at_iso = None
        elapsed = None

    conversation_id = (
        (row.output_data or {}).get("conversation_id")
        if isinstance(row.output_data, dict) else None
    )

    return {
        "status": row.status,
        "exists": True,
        "steps": row.activity_steps or [],
        "current_phase": row.current_phase,
        "started_at": started_at_iso,
        "elapsed_sec": elapsed,
        "error": row.error,
        "conversation_id": conversation_id,
        "skill_calls": skill_calls,
    }


@router.get("/executions/{execution_id}/files")
def list_execution_files(execution_id: str, db: Session = Depends(get_db)):
    files = db.query(AutomationFile).filter(
        AutomationFile.execution_id == execution_id,
        AutomationFile.is_deleted == False,
    ).all()
    return {"files": [_serialize_automation_file(f) for f in files]}


@router.get("/executions/{execution_id}/details")
def get_execution_details(
    execution_id: str,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_required),
):
    """Return one execution with its full output, files, and the linked
    conversation_id. Used by the Scheduled panel's "expand past run" view
    so the user can read the run's full report and download the file(s).
    """
    row = db.query(AutomationExecution).filter(
        AutomationExecution.id == execution_id,
        AutomationExecution.is_deleted == False,  # noqa: E712
    ).first()
    if not row:
        raise HTTPException(status_code=404, detail="Execution not found")
    _assert_tenant(row, user)
    d = row.to_dict()
    files = db.query(AutomationFile).filter(
        AutomationFile.execution_id == execution_id,
        AutomationFile.is_deleted == False,  # noqa: E712
    ).all()
    d["files"] = [_serialize_automation_file(f) for f in files]
    if d.get("status") == "failed" and d.get("error"):
        d["error_code"] = classify_run_failure_reason(d["error"])
    # Surface the conversation_id from output_data so the panel can offer
    # "open in chat" without the client having to dig through nested JSON.
    d["conversation_id"] = (
        (row.output_data or {}).get("conversation_id")
        if isinstance(row.output_data, dict) else None
    )
    d["agent_id"] = (
        (row.output_data or {}).get("agent_id")
        if isinstance(row.output_data, dict) else None
    )
    d["agent_name"] = (
        (row.output_data or {}).get("agent_name")
        if isinstance(row.output_data, dict) else None
    )
    # Which prior run's output was carried as context (cross-run continuity).
    # None on the first run; otherwise lets the panel show "built on run X"
    # and link to it.
    d["carried_context_from"] = (
        (row.output_data or {}).get("carried_context_from")
        if isinstance(row.output_data, dict) else None
    )
    # Phase 5 (Tier A #2): surface the quality-gate decision so the panel can
    # show a "file held back by quality gate" notice when the deliverable
    # wasn't shipped. ``held_back`` is a convenience boolean for the client.
    _qg = (
        (row.output_data or {}).get("quality_gate")
        if isinstance(row.output_data, dict) else None
    )
    d["quality_gate"] = _qg
    d["held_back"] = bool(_qg and not _qg.get("passed", True))
    return d


# Poll interval for the live SSE stream. Uses async sleep (not time.sleep) so
# the event-loop thread is released between polls — a sync generator would
# hold a threadpool worker for the stream's entire lifetime (up to 1h).
SSE_POLL_INTERVAL = 1.5


def _sse(obj: dict) -> str:
    """Format one SSE data frame."""
    return f"data: {json.dumps(obj, default=str)}\n\n"


async def _execution_event_stream(execution_id: str):
    """Generate SSE ``data: {json}`` strings tailing one execution's live
    progress. Yields ``activity_steps`` / ``phase`` deltas, then a terminal
    ``done`` or ``error`` event when the run reaches a terminal status, then
    stops.

    Polls the execution row every ~1.5s using a short-lived session per
    iteration (never holds a session across the sleep). Best-effort: any DB
    error yields an error event and stops so the client's EventSource
    reconnects / falls back to polling. Mirrors the sandbox job-events stream.
    """
    last_steps_sig = None
    last_phase = None
    deadline = time.time() + 3600  # hard cap 1h per stream
    while time.time() < deadline:
        s = SessionLocal()
        try:
            ex = s.query(AutomationExecution).filter(
                AutomationExecution.id == execution_id,
            ).first()
            if not ex:
                yield _sse({"type": "error", "message": "Execution not found"})
                return
            steps = ex.activity_steps or []
            sig = json.dumps(steps, default=str, sort_keys=True)
            if sig != last_steps_sig:
                last_steps_sig = sig
                yield _sse({"type": "activity_steps", "steps": steps})
            phase = ex.current_phase
            if phase != last_phase:
                last_phase = phase
                if phase:
                    yield _sse({"type": "phase", "state": phase})
            status = ex.status
            if status in ("completed", "failed", "skipped"):
                if status == "completed":
                    yield _sse({
                        "type": "done",
                        "content": (ex.output_text or "")[:4000],
                        "execution_id": execution_id,
                    })
                else:
                    yield _sse({
                        "type": "error",
                        "message": (ex.error or "Run failed")[:500],
                        "status": status,
                        "execution_id": execution_id,
                    })
                return
        except Exception as e:  # noqa: BLE001
            yield _sse({"type": "error", "message": f"stream error: {e}"})
            return
        finally:
            try:
                s.close()
            except Exception:
                pass
        await asyncio.sleep(SSE_POLL_INTERVAL)


@router.get("/executions/{execution_id}/events/stream")
async def stream_execution_events(execution_id: str):
    """Server-Sent Events stream of one execution's live progress.

    Mirrors the sandbox job-events stream. The Scheduled panel consumes this
    with ``EventSource`` while a run is queued/running and falls back to 30s
    polling when SSE fails. See ``_execution_event_stream`` for the event
    format.
    """
    # Existence check so a missing id 404s immediately (cleaner for the
    # client than an empty/error stream).
    s = SessionLocal()
    try:
        found = s.query(AutomationExecution).filter(
            AutomationExecution.id == execution_id,
        ).first()
    finally:
        try:
            s.close()
        except Exception:
            pass
    if not found:
        raise HTTPException(status_code=404, detail="Execution not found")

    return StreamingResponse(
        _execution_event_stream(execution_id),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


class SkipConfirmationRequest(BaseModel):
    skip: bool


@router.post("/{task_id}/skip-confirmation")
def set_skip_confirmation(
    task_id: str, req: SkipConfirmationRequest, db: Session = Depends(get_db)
):
    """Toggle the Manus-style "Always skip" confirmations flag on a task."""
    task = db.query(AutomationTask).filter(
        AutomationTask.id == task_id,
        AutomationTask.is_deleted == False,  # noqa: E712
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Automation task not found")
    task.skip_confirmation = "true" if req.skip else "false"
    task.updated_date = datetime.now(timezone.utc)
    db.commit()
    return {
        "success": True,
        "skip_confirmation": str(task.skip_confirmation).lower() in ("1", "true", "yes"),
    }


# ---------------------------------------------------------------------------
# Manual trigger
# ---------------------------------------------------------------------------

class RunRequest(BaseModel):
    note: Optional[str] = None


@router.post("/{task_id}/run")
async def run_now(task_id: str, db: Session = Depends(get_db)):
    """Manually trigger an immediate run. Returns the new execution id."""
    task = db.query(AutomationTask).filter(
        AutomationTask.id == task_id,
        AutomationTask.is_deleted == False,
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Automation task not found")
    from app.services.automation_dispatcher import trigger_now
    exec_id = await trigger_now(task_id)
    if not exec_id:
        raise HTTPException(status_code=500, detail="Failed to start execution")
    return {"success": True, "execution_id": exec_id}


# ---------------------------------------------------------------------------
# Session adoption (Manus UX — one chat per automation)
# ---------------------------------------------------------------------------


def _ensure_task_chat_session(db: Session, task: AutomationTask) -> tuple[str, bool]:
    """Return ``(session_id, created)`` for a dedicated per-task chat.

    Thin delegation to ``app.services.automation_sessions.ensure_task_chat_session``
    so the executor (services layer) can call the same logic without
    importing from the router (which would invert the dependency). The
    full implementation — including project-resolved tagging and drift
    reconciliation — lives in the service.
    """
    from app.services.automation_sessions import ensure_task_chat_session
    return ensure_task_chat_session(db, task)


@router.post("/{task_id}/ensure-session")
def ensure_session(task_id: str, db: Session = Depends(get_db)):
    """Adopt (or create) a dedicated chat session for an automation.

    The Manus-style UX expects every automation to live in its own
    chat, named after the task. Tasks created before the
    one-task-one-session migration may still be sharing a generic
    session (``"test"`` etc.). This endpoint either:

    * returns the existing matching session (no-op), or
    * creates a fresh ChatSession + AgentConversation pair, links
      it to the task, and returns the new session id.

    The frontend ``runNow`` calls this BEFORE ``POST /run`` so the
    resulting ``Open run`` message lands in the dedicated chat, not
    whatever legacy session the task inherited.
    """
    task = db.query(AutomationTask).filter(
        AutomationTask.id == task_id,
        AutomationTask.is_deleted == False,
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Automation task not found")
    session_id, created = _ensure_task_chat_session(db, task)
    return {"success": True, "session_id": session_id, "created": created}


@router.post("/{task_id}/recompute")
def recompute_next_run_endpoint(task_id: str, db: Session = Depends(get_db)):
    """Recompute and persist the next_run_at for a task."""
    from app.services.automation_dispatcher import recompute_next_run
    nxt = recompute_next_run(task_id)
    if not nxt:
        raise HTTPException(
            status_code=400,
            detail="Task has no valid schedule to recompute",
        )
    return {"success": True, "next_run_at": nxt.isoformat()}


@router.post("/executions/{execution_id}/cancel")
def cancel_execution_endpoint(
    execution_id: str,
    db: Session = Depends(get_db),
):
    """Stop a queued or running execution.

    Idempotent: cancelling an already-cancelled run is a no-op. Cancelling
    a run that already finished (succeeded / failed) returns the
    current status with ``already_terminal=True`` rather than 409 — the
    frontend can stop polling in either case.

    Implementation:
      1. CAS the DB row from queued|running -> cancelled (atomic UPDATE
         with WHERE status IN (...)). No-op if the row is already
         terminal.
      2. Set the executor's in-process cancel event
         (``request_cancel``) so the agent loop bails out at the next
         SSE-chunk checkpoint. Returns ``delivered=True`` if a live
         event was signalled, ``False`` if the executor already exited
         (the DB flip above is still authoritative).
    """
    from app.services.automation_executor import request_cancel

    ex = (
        db.query(AutomationExecution)
        .filter(AutomationExecution.id == execution_id)
        .first()
    )
    if ex is None:
        raise HTTPException(status_code=404, detail="Execution not found")
    if ex.status in ("succeeded", "failed", "cancelled"):
        return {
            "id": ex.id,
            "status": ex.status,
            "already_terminal": True,
            "delivered": False,
        }

    rc = db.execute(
        update(AutomationExecution)
        .where(
            AutomationExecution.id == execution_id,
            AutomationExecution.status.in_(["queued", "running"]),
        )
        .values(
            status="cancelled",
            error="Cancelled by user",
            completed_at=datetime.now(timezone.utc),
        )
    )
    db.commit()
    flipped = rc.rowcount == 1
    delivered = request_cancel(execution_id)
    # If two callers raced (cancel + janitor), one of them wins the CAS
    # and the other gets rowcount=0. Re-read for the response.
    if not flipped:
        db.refresh(ex)
    return {
        "id": ex.id,
        "status": ex.status if not flipped else "cancelled",
        "already_terminal": not flipped,
        "delivered": delivered,
    }


# ---------------------------------------------------------------------------
# File preview and download
# ---------------------------------------------------------------------------

_PREVIEW_RESPONSE_HEADERS = {
    "Cache-Control": "private, max-age=300",
    "Content-Security-Policy": (
        "sandbox; default-src 'none'; img-src data: https:; "
        "style-src 'unsafe-inline'; font-src data: https:"
    ),
    "X-Content-Type-Options": "nosniff",
}


@router.post("/files/{file_id}/preview-token")
def mint_file_preview_token(
    file_id: str,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_required),
):
    """Mint a short-lived signed token so iframe previews (which cannot send
    Authorization headers) can load the preview endpoint via ``?token=``."""
    from app.services.preview_tokens import mint_preview_token

    file_row = db.query(AutomationFile).filter(
        AutomationFile.id == file_id,
        AutomationFile.is_deleted == False,  # noqa: E712
    ).first()
    if not file_row:
        raise HTTPException(status_code=404, detail="File not found")
    _assert_tenant(file_row, user)
    token = mint_preview_token(file_id=file_id, user_id=str(user.id))
    return {
        "token": token,
        "url": f"/api/automations/files/{file_id}/preview?token={token}",
    }


@router.get("/files/{file_id}/preview")
def preview_automation_file(
    file_id: str,
    token: Optional[str] = Query(None),
    format: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    user: Optional[User] = Depends(get_current_user_optional),
):
    """Render a generated automation file inline without exposing disk paths.

    Accepts either the Bearer header (fetch/XHR) or a signed ``?token=``
    minted by ``POST /files/{id}/preview-token`` (iframe/img navigation).

    ``?format=html`` (docx/pptx only) returns sanitized mammoth/pptx HTML so
    the frontend's mammoth fallback reader can render automation files —
    otherwise the default path returns the original bytes or a LibreOffice
    PDF conversion.
    """
    from app.services.preview_tokens import verify_preview_token

    file_row = db.query(AutomationFile).filter(
        AutomationFile.id == file_id,
        AutomationFile.is_deleted == False,  # noqa: E712
    ).first()
    if not file_row:
        raise HTTPException(status_code=404, detail="File not found")

    if user is None and token:
        uid = verify_preview_token(token, file_id)
        if uid:
            candidate = db.get(User, uid)
            if candidate is not None and not getattr(candidate, "is_anonymous", False):
                user = candidate
    if user is None:
        raise HTTPException(status_code=401, detail="Authentication required")
    _assert_tenant(file_row, user)

    path = Path(file_row.file_path or "")
    if not path.exists():
        raise HTTPException(status_code=410, detail="File no longer exists on disk")

    file_type = (file_row.file_type or path.suffix).lower().lstrip(".")
    if file_type not in _PREVIEWABLE_FILE_TYPES:
        raise HTTPException(status_code=415, detail="Preview is not available for this file type")

    # HTML fallback for the frontend mammoth reader. Automation files live in
    # the AutomationFile table, not Artifact, so the artifacts router's
    # `?format=html` route 404s for them — this mirrors that route here.
    fmt = (format or "").lower().strip()
    if fmt == "html":
        if file_type not in {"docx", "pptx"}:
            raise HTTPException(
                status_code=400,
                detail="?format=html is only supported for DOCX and PPTX files",
            )
        from app.services.artifacts.preview_builder import (
            convert_docx_to_html,
            convert_pptx_to_html,
        )

        data = path.read_bytes()
        if file_type == "docx":
            html, _messages = convert_docx_to_html(data)
        else:
            html, _messages = convert_pptx_to_html(data)
        if not html:
            raise HTTPException(status_code=415, detail="HTML conversion is unavailable")
        return Response(
            content=html,
            media_type="text/html; charset=utf-8",
            headers={**_PREVIEW_RESPONSE_HEADERS, "Cache-Control": "no-store"},
        )

    if file_type in {"docx", "pptx", "xlsx"}:
        from app.services.artifacts.preview_builder import convert_to_preview

        # Pass the file-extension type ("docx" / "pptx" / "xlsx"), not the
        # MIME string — convert_to_preview dispatches on the extension-style
        # identifier and would silently return None for a MIME string,
        # which then 415s ("Preview conversion is unavailable"). The user
        # reported this with "Daily Sales Data Sync.docx" showing
        # "Preview unavailable (HTTP 404)" in the chat right pane — the
        # 404 was actually from the fallback renderer hitting a separate
        # broken endpoint; the underlying 415 here is what we just fixed.
        converted = convert_to_preview(
            path.read_bytes(),
            file_row.name,
            file_type,
        )
        if converted is None:
            raise HTTPException(status_code=415, detail="Preview conversion is unavailable")
        # convert_to_preview returns (preview_data, preview_file_name,
        # preview_mime_type). The route was previously written against an
        # unapplied dataclass (converted.ext / converted.data / ...) that
        # never landed, so any successful conversion crashed here with
        # AttributeError. Unpack the tuple explicitly.
        preview_bytes, preview_name, preview_mime = converted
        return Response(
            content=preview_bytes,
            media_type=preview_mime,
            headers={
                **_PREVIEW_RESPONSE_HEADERS,
                "Content-Disposition": f'inline; filename="{preview_name}"',
            },
        )

    return FileResponse(
        path=str(path),
        media_type=file_row.mime_type or mimetypes.guess_type(file_row.name)[0]
        or "application/octet-stream",
        filename=file_row.name,
        content_disposition_type="inline",
        headers=_PREVIEW_RESPONSE_HEADERS,
    )


@router.get("/files/{file_id}/download")
def download_file(
    file_id: str,
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_required),
):
    file_row = db.query(AutomationFile).filter(
        AutomationFile.id == file_id,
        AutomationFile.is_deleted == False,
    ).first()
    if not file_row:
        raise HTTPException(status_code=404, detail="File not found")
    _assert_tenant(file_row, user)
    path = Path(file_row.file_path or "")
    if not path.exists():
        raise HTTPException(status_code=410, detail="File no longer exists on disk")
    return FileResponse(
        path=str(path),
        media_type=file_row.mime_type or "application/octet-stream",
        filename=file_row.name,
    )


@router.get("/email-download/{file_id}")
def email_download_file(
    file_id: str,
    token: Optional[str] = Query(None),
    db: Session = Depends(get_db),
):
    """Serve a generated file via a time-limited HMAC-signed link (no auth).

    Used by the email notification gateway when the output file is too large to
    attach (or attachments are disabled). The token is minted by
    ``notification_gateway.download_link.generate_download_token`` and is bound
    to ``file_id`` with a 7-day expiry, so email recipients who are not logged-in
    users can still download the result.
    """
    from app.services.notification_gateway import verify_download_token

    if not token or not verify_download_token(token, file_id):
        raise HTTPException(status_code=401, detail="Invalid or expired download link")

    file_row = db.query(AutomationFile).filter(
        AutomationFile.id == file_id,
        AutomationFile.is_deleted == False,  # noqa: E712
    ).first()
    if not file_row:
        raise HTTPException(status_code=404, detail="File not found")

    path = Path(file_row.file_path or "")
    if not path.exists():
        raise HTTPException(status_code=410, detail="File no longer exists on disk")

    return FileResponse(
        path=str(path),
        media_type=file_row.mime_type or mimetypes.guess_type(file_row.name)[0]
        or "application/octet-stream",
        filename=file_row.name,
    )


# ---------------------------------------------------------------------------
# Status toggle
# ---------------------------------------------------------------------------

class ToggleRequest(BaseModel):
    status: str  # "active" or "paused"


@router.post("/{task_id}/toggle")
def toggle_status(task_id: str, req: ToggleRequest, db: Session = Depends(get_db)):
    """Pause/resume an automation. If resuming, recompute next_run_at."""
    task = db.query(AutomationTask).filter(
        AutomationTask.id == task_id,
        AutomationTask.is_deleted == False,
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Automation task not found")
    new_status = req.status
    if new_status not in ("active", "paused", "failed", "completed"):
        raise HTTPException(status_code=400, detail=f"Invalid status: {new_status}")
    task.status = new_status
    task.updated_date = datetime.now(timezone.utc)
    db.commit()
    if new_status == "active" and task.cron_expression:
        from app.services.automation_dispatcher import recompute_next_run
        nxt = recompute_next_run(task_id)
        if nxt:
            return {
                "success": True,
                "status": new_status,
                "next_run_at": nxt.isoformat(),
            }
    return {
        "success": True,
        "status": new_status,
        "next_run_at": task.next_run_at.isoformat() if task.next_run_at else None,
    }


@router.delete("/{task_id}")
def delete_automation(task_id: str, db: Session = Depends(get_db)):
    """Soft-delete an automation task. Used by the Manus-style
    'Delete schedule' action in the Scheduled side panel.

    Also clears the chat_session → task link by stamping a sentinel on
    the session's metadata so the Scheduled button disappears for the
    originating chat.
    """
    task = db.query(AutomationTask).filter(
        AutomationTask.id == task_id,
        AutomationTask.is_deleted == False,  # noqa: E712
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Automation task not found")
    task.is_deleted = True
    task.status = "deleted"
    task.updated_date = datetime.now(timezone.utc)
    db.commit()
    return {"success": True, "id": task_id}


# ── Nightly forecast bootstrap ─────────────────────────────────────────


@router.post("/bootstrap-nightly-forecast")
def bootstrap_nightly_forecast(
    db: Session = Depends(get_db),
    user: User = Depends(get_current_user_required),
):
    """Create the idempotent nightly forecast automation task.

    Ensures:
      1. Forecast targets exist (seeded from per-app domain config)
      2. The automation_runtime_agent exists for this (org, app)
      3. An AutomationTask with cron=0 2 * * *, skip_confirmation=true exists

    Returns the existing task if already created. Idempotent.
    """
    from app.config import settings

    if not getattr(settings, "NIGHTLY_FORECAST_ENABLED", True):
        raise HTTPException(status_code=403, detail="Nightly forecast is disabled")

    from app.services.automation_runtime import ensure_automation_runtime_agent
    from app.services.forecasting.seed_targets import (
        seed_forecast_targets,
        discover_and_seed_sku_targets,
    )

    org_id = getattr(user, "org_id", None) or "default-org"
    app_id = getattr(user, "app_id", None) or "default-app"
    cron = getattr(settings, "NIGHTLY_FORECAST_CRON", "0 2 * * *")

    # 1. Ensure targets exist (idempotent)
    seed_forecast_targets(db, org_id=org_id, app_id=app_id)
    # 1b. Discover and seed ERP SKU targets (idempotent)
    sku_count = discover_and_seed_sku_targets(db, org_id=org_id, app_id=app_id)
    if sku_count:
        logger.info("[bootstrap] Seeded %d new ERP SKU targets for org=%s", sku_count, org_id)

    # 2. Ensure runtime agent exists (idempotent)
    runtime = ensure_automation_runtime_agent(db, org_id, app_id)

    # 3. Find or create the automation task (idempotent by name + org)
    existing = db.query(AutomationTask).filter(
        AutomationTask.name == "Nightly Forecast",
        AutomationTask.org_id == org_id,
        AutomationTask.is_deleted == False,  # noqa: E712
    ).first()
    if existing:
        return {"task_id": existing.id, "status": "exists", "cron": cron}

    task = AutomationTask(
        name="Nightly Forecast",
        type="scheduled",
        description=(
            "Silent nightly ML forecast for all active forecast targets "
            "in this org. Writes to forecast_runs."
        ),
        org_id=org_id,
        app_id=app_id,
        agent_id=runtime.id,
        created_by_id=getattr(user, "id", None),
        schedule=cron,
        cron_expression=cron,
        timezone="UTC",
        skip_confirmation="true",
        output_format="json",
        prompt=(
            "Run the `forecast_run` tool with no arguments (target_id=null) "
            "to refresh forecasts for all active targets in this org. "
            "Do not chat, summarize, or output any narrative — just call the "
            "tool, report success/failure counts, and end."
        ),
        status="active",
    )
    db.add(task)
    db.commit()
    db.refresh(task)
    return {"task_id": task.id, "status": "created", "cron": cron}


class NotificationSettingsRequest(BaseModel):
    notify_enabled: bool = False
    notify_emails: list[str] = []
    notify_on: str = "always"  # "always" | "on_success" | "on_failure"
    attach_file: bool = True


@router.patch("/{task_id}/notification-settings")
def update_notification_settings(
    task_id: str,
    req: NotificationSettingsRequest,
    db: Session = Depends(get_db),
):
    """Persist per-task email notification settings with server-side validation.

    Rejects malformed addresses and unknown ``notify_on`` values with 422 so the
    UI can surface inline errors without a round-trip to the SMTP server.
    """
    from app.services.notification_gateway import is_valid_email

    task = db.query(AutomationTask).filter(
        AutomationTask.id == task_id,
        AutomationTask.is_deleted == False,  # noqa: E712
    ).first()
    if not task:
        raise HTTPException(status_code=404, detail="Automation task not found")

    emails = [e.strip().lower() for e in req.notify_emails if e and e.strip()]
    invalid = [e for e in emails if not is_valid_email(e)]
    if invalid:
        raise HTTPException(
            status_code=422,
            detail=f"Invalid email address(es): {', '.join(invalid)}",
        )
    if req.notify_on not in ("always", "on_success", "on_failure"):
        raise HTTPException(
            status_code=422,
            detail="notify_on must be one of: always, on_success, on_failure",
        )

    task.notify_enabled = req.notify_enabled
    task.notify_emails = emails
    task.notify_on = req.notify_on
    task.attach_file = req.attach_file
    task.updated_date = datetime.now(timezone.utc)
    db.commit()
    db.refresh(task)
    return {
        "success": True,
        "notify_enabled": task.notify_enabled,
        "notify_emails": task.notify_emails,
        "notify_on": task.notify_on,
        "attach_file": task.attach_file,
    }


__all__ = ["router"]
