"""Tests for layout_engine — the single source of truth for deck placement.

Verifies:
* render() returns valid .pptx bytes for a DeckPlan.
* Slide count matches the plan.
* No "Generated by Zhanlu AI" footer is injected.
* Slide-number captions are present (subtle, bottom-right).
* Typography floor: body runs are >= 14pt (BODY_PT).
"""

from __future__ import annotations

import re
import zipfile
from io import BytesIO

from pptx import Presentation
from pptx.util import Pt

from app.services.synexia.contracts import (
    ChartSpecInSlide,
    DeckPlan,
    KPISpecInSlide,
    SlidePlan,
)
from app.services.artifacts.layout_engine import render


def _chart_xml(data: bytes, slide_idx: int = 2) -> str:
    """Return the chart XML for slide ``slide_idx`` (0-based) of a rendered deck."""
    with zipfile.ZipFile(BytesIO(data)) as z:
        rels = [n for n in z.namelist() if f"ppt/slides/_rels/slide{slide_idx + 1}.xml.rels" == n]
        assert rels, "slide rels not found"
        rel_xml = z.read(rels[0]).decode("utf-8")
        m = re.search(r'Target="\.\./charts/(chart\d+\.xml)"', rel_xml)
        assert m, "no chart relationship on slide"
        return z.read(f"ppt/charts/{m.group(1)}").decode("utf-8")


def _plan():
    return DeckPlan(
        title="Layout Engine Test",
        deck_type="data_report",
        slides=[
            SlidePlan(layout="cover", title="Layout Engine Test", subtitle="Sub",
                      kpi_specs=[KPISpecInSlide(label="A", value="1", delta="+1")]),
            SlidePlan(layout="bullets", title="Takeaways",
                      bullets=["One clear point.", "Two clear points."]),
            SlidePlan(layout="chart_full", title="Trend",
                      chart_spec=ChartSpecInSlide(chart_type="bar", x_key="m",
                                                  y_keys=["v"], title="Trend"),
                      chart_rows=[{"m": "Jan", "v": 1}, {"m": "Feb", "v": 2}]),
            SlidePlan(layout="closing", title="Next", bullets=["Do it."]),
        ],
    )


def test_render_returns_valid_pptx():
    data = render(_plan(), [], {"theme_tokens": {"name": "zhanlu-blue"},
                                 "style_recipe": "sharp"})
    assert isinstance(data, bytes) and len(data) > 0
    prs = Presentation(BytesIO(data))
    assert len(prs.slides) == 4


def test_no_generated_by_footer():
    data = render(_plan(), [], {"theme_tokens": {"name": "zhanlu-blue"},
                                 "style_recipe": "sharp"})
    prs = Presentation(BytesIO(data))
    all_text = []
    for s in prs.slides:
        for sh in s.shapes:
            if sh.has_text_frame:
                all_text.append(sh.text_frame.text)
    assert "Generated by Zhanlu AI" not in "\n".join(all_text)


def test_slide_numbers_present():
    data = render(_plan(), [], {"theme_tokens": {"name": "zhanlu-blue"},
                                 "style_recipe": "sharp"})
    prs = Presentation(BytesIO(data))
    # Content slides (2,3,4 here) should carry a "N / total" caption.
    numbered = []
    for s in prs.slides:
        for sh in s.shapes:
            if sh.has_text_frame and "/" in sh.text_frame.text and sh.text_frame.text.strip()[0].isdigit():
                numbered.append(sh.text_frame.text)
    # At least one slide-number caption present.
    assert any("/" in t for t in numbered), "no slide-number caption found"


def test_body_font_floor():
    """BODY text (bullets, titles, KPI values) must be >= BODY_PT (14).

    Footer/slide-number runs (FOOTER_PT = 10) and caption runs (CAPTION_PT =
    12 — cover "Prepared for …" line, KPI labels, axis hints) are explicitly
    exempt — they are the only sub-14pt runs allowed. This guards against the
    layout engine silently shrinking readable body text.
    """
    data = render(_plan(), [], {"theme_tokens": {"name": "zhanlu-blue"},
                                 "style_recipe": "sharp"})
    prs = Presentation(BytesIO(data))

    BODY_PT = 14.0
    CAPTION_PT = 12.0
    min_body = 999.0
    min_overall = 999.0
    footer_seen = False
    for s in prs.slides:
        for sh in s.shapes:
            if not sh.has_text_frame:
                continue
            for p in sh.text_frame.paragraphs:
                for r in p.runs:
                    if not r.font.size:
                        continue
                    pt = r.font.size.pt
                    min_overall = min(min_overall, pt)
                    # Caption/footer exemption (sub-14pt runs allowed): the
                    # slide-number "N / total" runs are the footers.
                    if pt <= CAPTION_PT + 0.01:
                        if "/" in (sh.text_frame.text or ""):
                            footer_seen = True
                        continue
                    min_body = min(min_body, pt)

    assert footer_seen, "expected at least one footer/slide-number run at 10pt"
    assert min_overall >= 10.0, f"min font {min_overall} below 10pt caption floor"
    # The real assertion: actual body text must not drop below 14pt.
    assert min_body >= BODY_PT, f"body font {min_body} below 14pt floor"


def test_fallback_plan_chart_data_enriched_from_rows():
    """Regression: a plan that only carries chart_spec (column keys, no rows)
    must still render a chart with the payload values — the planner fallback
    path emits x_key/y_keys but never materializes chart_rows, and previously
    produced "No chart data available" slides.

    render() projects the payload rows into chart_rows at build time.
    """
    plan = DeckPlan(
        title="Fallback Data Wiring",
        deck_type="data_report",
        slides=[
            SlidePlan(layout="cover", title="Fallback Data Wiring"),
            SlidePlan(layout="chart_full", title="Revenue by Month",
                      chart_spec=ChartSpecInSlide(chart_type="bar", x_key="m",
                                                  y_keys=["v"], title="Revenue by Month")),
        ],
    )
    rows = [{"m": "Jan", "v": 1200}, {"m": "Feb", "v": 1500}, {"m": "Mar", "v": 1100}]

    data = render(plan, rows, {"theme_tokens": {"name": "zhanlu-blue"},
                               "style_recipe": "sharp"})

    # Chart slide must NOT contain the empty-data placeholder.
    prs = Presentation(BytesIO(data))
    assert len(prs.slides) == 2

    chart_xml = _chart_xml(data, slide_idx=1)
    assert "No chart data available" not in chart_xml
    # The projected values must be baked into the numeric cache (floats).
    for v in (1200, 1500, 1100):
        assert f"<c:v>{float(v)}</c:v>" in chart_xml, f"value {v} missing from chart XML"
    # Category labels present too.
    for label in ("Jan", "Feb", "Mar"):
        assert f"<c:v>{label}</c:v>" in chart_xml, f"category {label} missing"
