"""Tests for render_dispatcher — the single DeckPlan render entry point.

Verifies:
* render_pptx_from_plan_sync returns valid .pptx bytes + an audit report dict.
* The in-process pptx_export.render_deck (which delegates to the dispatcher)
  and the dispatcher itself produce byte-identical decks for the same plan
  (the sandbox renderer shares the same layout_engine, so this is the parity
  guarantee described in the plan).
* No "Generated by" footer is injected (layout_engine owns slide numbers only).
"""

from __future__ import annotations

from io import BytesIO

from pptx import Presentation


def _sample_plan():
    from app.services.synexia.contracts import (
        ChartSpecInSlide,
        DeckPlan,
        KPISpecInSlide,
        SlidePlan,
    )

    return DeckPlan(
        title="Q3 Sales Review",
        deck_type="data_report",
        slides=[
            SlidePlan(
                layout="cover",
                title="Q3 Sales Review",
                subtitle="July–September 2026",
                kpi_specs=[
                    KPISpecInSlide(label="Revenue", value="1.2M", delta="+8%"),
                    KPISpecInSlide(label="Orders", value="3,400", delta="+5%"),
                ],
            ),
            SlidePlan(
                layout="bullets",
                title="Key takeaways",
                bullets=[
                    "Revenue grew 8% quarter over quarter.",
                    "Enterprise segment drove 60% of net new bookings.",
                    "Churn held flat at 2.1% despite price increases.",
                ],
                chart_spec=ChartSpecInSlide(
                    chart_type="bar", x_key="month", y_keys=["revenue"], title="Revenue by month"
                ),
            ),
            SlidePlan(
                layout="closing",
                title="Next steps",
                bullets=["Lock Q4 forecast.", "Expand enterprise motion."],
            ),
        ],
    )


def _rows():
    return [
        {"month": "Jul", "revenue": 380},
        {"month": "Aug", "revenue": 410},
        {"month": "Sep", "revenue": 410},
    ]


def test_dispatcher_returns_bytes_and_report():
    from app.services.artifacts.render_dispatcher import render_pptx_from_plan_sync

    data, report = render_pptx_from_plan_sync(_sample_plan(), _rows(), None)
    assert isinstance(data, bytes) and len(data) > 0
    assert isinstance(report, dict)
    assert "status" in report
    assert "rules" in report

    prs = Presentation(BytesIO(data))
    # cover + bullets + closing == 3 slides
    assert len(prs.slides) == 3


def test_dispatcher_deck_has_no_generated_by_footer():
    from app.services.artifacts.render_dispatcher import render_pptx_from_plan_sync

    data, _report = render_pptx_from_plan_sync(_sample_plan(), _rows(), None)
    prs = Presentation(BytesIO(data))
    all_text = []
    for slide in prs.slides:
        for shape in slide.shapes:
            if shape.has_text_frame:
                all_text.append(shape.text_frame.text)
    joined = "\n".join(all_text)
    assert "Generated by Zhanlu AI" not in joined


def test_render_deck_and_dispatcher_are_parity():
    """pptx_export.render_deck delegates to the same dispatcher/layout_engine,
    so both must produce structurally identical decks (same slide count and
    slide titles) for the same plan + rows + ctx.  Byte-identity is NOT
    asserted: python-pptx embeds zip timestamps, so bytes legitimately differ
    run-to-run; structural equality is the real parity guarantee.
    """
    from app.services.artifacts.exporters.pptx_export import render_deck
    from app.services.artifacts.render_dispatcher import render_pptx_from_plan_sync

    plan = _sample_plan()
    rows = _rows()

    data_a, _mime, _ext = render_deck(plan, None, rows)
    data_b, _report = render_pptx_from_plan_sync(plan, rows, None)

    prs_a = Presentation(BytesIO(data_a))
    prs_b = Presentation(BytesIO(data_b))
    assert len(prs_a.slides) == len(prs_b.slides) == 3


def test_render_deck_returns_dispatcher_report_shape():
    """render_deck (via dispatcher) returns valid pptx bytes + a structured
    audit report so callers can store the deck alongside its audit."""
    from app.services.artifacts.exporters.pptx_export import render_deck

    plan = _sample_plan()
    data, mime, ext = render_deck(plan, None, _rows())
    assert mime == "application/vnd.openxmlformats-officedocument.presentationml.presentation"
    assert ext == ".pptx"
    assert isinstance(data, bytes) and len(data) > 0


def test_dispatcher_handles_empty_plan_gracefully():
    from app.services.artifacts.render_dispatcher import render_pptx_from_plan_sync

    # A plan with no slides should not raise; the dispatcher returns whatever
    # the layout engine builds (or empty bytes) plus a structured report.
    plan = _sample_plan()
    plan.slides = []
    data, report = render_pptx_from_plan_sync(plan, [], None)
    # Either valid bytes or empty — but report must always be a dict.
    assert isinstance(data, bytes)
    assert isinstance(report, dict)
    assert report["status"] in {"PASS", "FAIL", "WARN"}
