"""Branded Claude-style PPTX deck — generation tests (TDD).

These tests define the richer deck contract before the exporter is rewritten:

  * cover slide with a brand stripe (primary blue fill) and the title, no footer
  * agenda slide when `sections` are present
  * executive summary / key metrics / chart / key findings / insights /
    recommendations / data / methodology slides, each gated on its payload field
  * (next_step is NOT rendered — it is conversational guidance for the
    in-chat card, not deck content)
  * per-content-slide footer "Generated by Zhanlu AI · N / total"
  * density caps: <= 6 insights / key findings / recommendations

The sandbox ``generate_pptx`` is held to the same bar: function-local pptx
imports (worker-context safety) and a valid branded deck from a config dict.
"""
import inspect
import io
import os
import sys
import tempfile
import zipfile
from pathlib import Path

_THIS_DIR = Path(__file__).resolve().parent
_BACKEND_ROOT = _THIS_DIR.parent
if str(_BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(_BACKEND_ROOT))
os.chdir(_BACKEND_ROOT)

from pptx import Presentation
from pptx.util import Inches
from pptx.dml.color import RGBColor

C_PRIMARY = RGBColor(0x25, 0x63, 0xEB)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _full_payload():
    from app.services.synexia.contracts import (
        ReportCardPayload, KPISpec, ChartSpec, InsightSpec, SectionSpec,
    )
    return ReportCardPayload(
        title="Q3 Sales Review",
        source="erp_v_sale_orderentry · db1",
        generated_at="2026-07-22T08:30:00Z",
        summary="Top materials drive 76% of revenue.",
        methodology="Aggregated sale_orderentry rows grouped by material_name.",
        kpis=[
            KPISpec(label="Revenue", value="189.3M", delta="+12%", caption="QoQ"),
            KPISpec(label="Rows", value="7", caption="distinct materials"),
        ],
        chart=ChartSpec(
            type="bar", title="Top materials by revenue",
            x_key="label", y_keys=["value"],
            data=[{"label": "M1", "value": 66}, {"label": "M2", "value": 22}],
        ),
        insights=[InsightSpec(icon="trending-up", text="Concentration risk worth monitoring.")],
        key_findings=[InsightSpec(icon="target", text="Top 3 materials = 76% of revenue.")],
        recommendations=[InsightSpec(icon="check", text="Diversify suppliers for the top material.")],
        sections=[SectionSpec(title="Context", content="Q3 snapshot of material revenue.")],
        next_step="Break this down by region?",
        warnings=["Snapshot capped to 5 rows for the chart slide."],
    )


def _render(payload):
    from app.services.artifacts.exporters.pptx_export import render
    data, mime, ext = render(payload)
    assert data[:4] == b"PK\x03\x04", "PPTX must be a ZIP"
    return data


def _slides(data):
    return Presentation(io.BytesIO(data)).slides


def _slide_texts(slide):
    """All visible text on a slide (text frames + table cells), in order."""
    texts = []
    for shape in slide.shapes:
        if shape.has_text_frame:
            for p in shape.text_frame.paragraphs:
                t = "".join(r.text for r in p.runs)
                if t.strip():
                    texts.append(t)
        if shape.has_table:
            for row in shape.table.rows:
                for cell in row.cells:
                    if (cell.text or "").strip():
                        texts.append(cell.text)
    return texts


def _all_texts(slides):
    out = []
    for s in slides:
        out.extend(_slide_texts(s))
    return out


def _shape_fill_rgb(shape):
    try:
        if shape.fill.type is not None and shape.fill.type == 1:  # MSO_FILL.SOLID
            return shape.fill.fore_color.rgb
    except Exception:
        return None
    return None


# ---------------------------------------------------------------------------
# Exporter: full deck
# ---------------------------------------------------------------------------


def test_full_payload_produces_all_branded_slides():
    slides = _slides(_render(_full_payload()))
    # cover + agenda + exec summary + kpi + chart + key findings + insights
    # + recommendations + data + methodology = 10  (no closing "Next Step" slide)
    assert len(slides) >= 10, f"expected >=10 slides, got {len(slides)}"
    joined = " \n ".join(_all_texts(slides))
    for marker in [
        "Agenda", "Executive Summary", "Key Metrics", "Key Findings",
        "Insights", "Recommendations", "Data", "Methodology",
    ]:
        assert marker in joined, f"missing slide marker: {marker!r}"
    # next_step must NOT appear as deck content
    assert "Next Step" not in joined
    assert "Break this down by region" not in joined


def test_cover_has_brand_stripe_title_and_no_footer():
    slides = _slides(_render(_full_payload()))
    cover = slides[0]
    texts = _slide_texts(cover)
    assert "Q3 Sales Review" in texts, "cover must carry the title"
    # A brand stripe = a shape filled with the primary brand blue
    fills = [_shape_fill_rgb(sh) for sh in cover.shapes]
    assert C_PRIMARY in fills, "cover must have a primary-blue brand stripe"
    # Cover is the one slide WITHOUT a footer
    assert not any("Generated by Zhanlu AI" in t for t in texts), \
        "cover must not carry the content-slide footer"


def test_every_content_slide_carries_footer_with_numbering():
    data = _render(_full_payload())
    slides = _slides(data)
    total = len(slides)
    for idx, slide in enumerate(slides):
        if idx == 0:
            continue  # cover has no footer
        texts = _slide_texts(slide)
        foot = [t for t in texts if "Generated by Zhanlu AI" in t]
        assert foot, f"slide {idx + 1} missing footer"
        # footer carries "N / total" numbering
        assert f"{idx + 1} / {total}" in foot[0], \
            f"slide {idx + 1} footer numbering wrong: {foot[0]!r}"


# ---------------------------------------------------------------------------
# Exporter: conditional gating
# ---------------------------------------------------------------------------


def _minimal(title="Minimal", **kw):
    from app.services.synexia.contracts import ReportCardPayload
    return ReportCardPayload(title=title, user_signal="default", **kw)


def test_no_kpis_omits_key_metrics_slide():
    p = _full_payload()
    p.kpis = []
    joined = " \n ".join(_all_texts(_slides(_render(p))))
    assert "Key Metrics" not in joined


def test_no_key_findings_omits_key_findings_slide():
    p = _full_payload()
    p.key_findings = []
    joined = " \n ".join(_all_texts(_slides(_render(p))))
    assert "Key Findings" not in joined


def test_no_recommendations_omits_recommendations_slide():
    p = _full_payload()
    p.recommendations = []
    joined = " \n ".join(_all_texts(_slides(_render(p))))
    assert "Recommendations" not in joined


def test_no_methodology_omits_methodology_slide():
    p = _full_payload()
    p.methodology = ""
    joined = " \n ".join(_all_texts(_slides(_render(p))))
    assert "Methodology" not in joined


def test_no_sections_omits_agenda_slide():
    p = _full_payload()
    p.sections = []
    joined = " \n ".join(_all_texts(_slides(_render(p))))
    assert "Agenda" not in joined


def test_next_step_never_rendered_even_when_set():
    # next_step is conversational guidance for the in-chat card; it must
    # never appear in the deck regardless of whether it is set.
    p = _full_payload()  # has next_step="Break this down by region?"
    joined = " \n ".join(_all_texts(_slides(_render(p))))
    assert "Next Step" not in joined
    assert "Break this down by region" not in joined


def test_minimal_payload_still_valid_with_cover_only():
    data = _render(_minimal())
    slides = _slides(data)
    assert len(slides) >= 1
    assert "Minimal" in _slide_texts(slides[0])


# ---------------------------------------------------------------------------
# Exporter: density caps
# ---------------------------------------------------------------------------


def test_insights_capped_at_six():
    from app.services.synexia.contracts import InsightSpec
    p = _full_payload()
    p.insights = [InsightSpec(icon="lightbulb", text=f"Insight {i}") for i in range(10)]
    slides = _slides(_render(p))
    # find the Insights slide
    ins_slide = [s for s in slides if any("Insights" == t.strip() for t in _slide_texts(s))]
    assert ins_slide, "Insights slide missing"
    body = [t for t in _slide_texts(ins_slide[0]) if t.startswith("Insight ")]
    assert len(body) <= 6, f"insights not capped: {len(body)}"


def test_recommendations_capped_at_six():
    from app.services.synexia.contracts import InsightSpec
    p = _full_payload()
    p.recommendations = [InsightSpec(icon="check", text=f"Rec {i}") for i in range(10)]
    slides = _slides(_render(p))
    rec_slide = [s for s in slides if any("Recommendations" == t.strip() for t in _slide_texts(s))]
    assert rec_slide, "Recommendations slide missing"
    body = [t for t in _slide_texts(rec_slide[0]) if t.startswith("Rec ")]
    assert len(body) <= 6, f"recommendations not capped: {len(body)}"


def test_key_findings_capped_at_six():
    from app.services.synexia.contracts import InsightSpec
    p = _full_payload()
    p.key_findings = [InsightSpec(icon="target", text=f"Finding {i}") for i in range(10)]
    slides = _slides(_render(p))
    kf_slide = [s for s in slides if any("Key Findings" == t.strip() for t in _slide_texts(s))]
    assert kf_slide, "Key Findings slide missing"
    body = [t for t in _slide_texts(kf_slide[0]) if t.startswith("Finding ")]
    assert len(body) <= 6, f"key findings not capped: {len(body)}"


# ---------------------------------------------------------------------------
# Sandbox generate_pptx
# ---------------------------------------------------------------------------


def test_sandbox_generate_pptx_uses_function_local_imports():
    import app.services.sandbox.sandbox_runner as sr
    src = inspect.getsource(sr.generate_pptx)
    # The sandbox worker forbids MODULE-LEVEL pptx imports; all heavy pptx
    # work now lives inside the vendored layout_engine, which generate_pptx
    # imports lazily (flat copy first, then the in-process dotted path).
    assert "import pptx" not in src, "generate_pptx must not import pptx at module level"
    assert "layout_engine" in src, "generate_pptx must delegate rendering to layout_engine"
    # Confirm no module-level pptx import in sandbox_runner at all.
    module_src = inspect.getsource(sr)
    assert "import pptx" not in module_src, "sandbox_runner must not import pptx at module level"


def test_sandbox_generate_pptx_produces_branded_deck(tmp_path):
    import app.services.sandbox.sandbox_runner as sr
    original = sr.OUTPUT_DIR
    sr.OUTPUT_DIR = tmp_path
    try:
        config = {
            "title": "Sandbox Deck",
            "summary": "A summary from the sandbox.",
            "source": "sandbox_rows",
            "methodology": "Rows aggregated in-process.",
            "kpis": [
                {"label": "Revenue", "value": "100M", "delta": "+5%", "caption": "QoQ"},
                {"label": "Rows", "value": "7", "caption": "distinct"},
            ],
            "insights": [{"icon": "lightbulb", "text": "Sandbox insight."}],
            "key_findings": [{"icon": "target", "text": "Top 3 = 70%."}],
            "recommendations": [{"icon": "check", "text": "Act now."}],
            "next_step": "Drill into region?",
            "chart": {
                "type": "bar", "title": "By material",
                "x_key": "label", "y_keys": ["value"],
                "data": [{"label": "A", "value": 10}, {"label": "B", "value": 20}],
            },
        }
        rows = [{"label": "A", "value": 10}, {"label": "B", "value": 20}]
        out_file = sr.generate_pptx(rows, config, "extra instructions")
        assert out_file == "report.pptx"
        out_path = tmp_path / "report.pptx"
        assert out_path.exists() and out_path.stat().st_size > 0
        data = out_path.read_bytes()
        assert data[:4] == b"PK\x03\x04"
        slides = _slides(data)
        assert len(slides) >= 4, f"sandbox deck too thin: {len(slides)} slides"
        joined = " \n ".join(_all_texts(slides))
        assert "Sandbox Deck" in joined
        assert "Key Metrics" in joined  # kpis present -> KPI slide
        # Phase 1B: the shared layout engine renders decks with subtle slide
        # numbers only — NO "Generated by Zhanlu AI" footer.
        assert "Generated by Zhanlu AI" not in joined
    finally:
        sr.OUTPUT_DIR = original
