"""Tests for the rich HTML sidecar preview generated by
``create_artifact`` for docx/pptx/xlsx artifacts.

The sidecar is what the user sees when they click the docx card in
the chat — it must be a full interactive dashboard (cover, KPIs,
key findings, insights, recommendations, custom sections, data,
SQL, next step), not just a plain mammoth conversion of the file.
"""
import pytest

from app.services.tool_handlers.artifact_tool import (
    _render_sidecar_html,
    _sidecar_css,
    _esc,
)
from app.services.synexia.contracts import (
    ChartSpec,
    InsightSpec,
    KPISpec,
    ReportCardPayload,
    SectionSpec,
)


# ---------------------------------------------------------------------------
# _esc — HTML escaping
# ---------------------------------------------------------------------------


def test_esc_strips_html_chars():
    assert _esc("<script>") == "&lt;script&gt;"
    assert _esc("Tom & Jerry") == "Tom &amp; Jerry"
    assert _esc('"quoted"') == "&quot;quoted&quot;"
    assert _esc("it's") == "it&#x27;s"


def test_esc_handles_non_string_inputs():
    """Numbers / None should still produce a safe string."""
    assert _esc(42) == "42"
    assert _esc(None) == "None"


# ---------------------------------------------------------------------------
# _sidecar_css — the CSS block
# ---------------------------------------------------------------------------


def test_css_contains_brand_colors():
    css = _sidecar_css()
    # Brand gradient
    assert "linear-gradient" in css
    assert "#0F172A" in css or "0F172A" in css
    # Brand orange
    assert "F59E0B" in css or "f59e0b" in css


def test_css_contains_grid_for_kpis():
    css = _sidecar_css()
    assert "grid-template-columns" in css
    assert "kpis" in css


# ---------------------------------------------------------------------------
# _render_sidecar_html — full render
# ---------------------------------------------------------------------------


def _full_rcp() -> ReportCardPayload:
    return ReportCardPayload(
        title="Q3 Sales Review",
        source="sales_db",
        generated_at="2026-07-15T10:00:00",
        summary="Revenue grew 23% YoY driven by Q3 product launches and EMEA expansion.",
        methodology="Aggregated from sales_db, deduplicated, last 90 days.",
        kpis=[
            KPISpec(label="Total Revenue", value="$1.2M", delta="+23%"),
            KPISpec(label="Customers", value="1,847"),
        ],
        chart=ChartSpec(
            title="Revenue by Quarter",
            type="bar",
            x_key="quarter",
            y_keys=["revenue"],
            data=[
                {"quarter": "Q1", "revenue": 280},
                {"quarter": "Q2", "revenue": 320},
                {"quarter": "Q3", "revenue": 380},
            ],
        ),
        key_findings=[
            InsightSpec(text="Q3 launch drove 19% MoM conversion lift."),
            InsightSpec(text="EMEA remains the largest market."),
        ],
        insights=[InsightSpec(text="APAC grew 34% QoQ.")],
        recommendations=[InsightSpec(text="Increase Q4 inventory by 20%.")],
        sections=[SectionSpec(title="Data Source", content="sales_db.daily_transactions")],
        sql="SELECT quarter, SUM(amount) FROM sales GROUP BY quarter;",
        next_step="Plan Q4 inventory.",
    )


def test_sidecar_renders_to_valid_html():
    html = _render_sidecar_html(_full_rcp())
    assert isinstance(html, bytes)
    assert b"<!doctype html>" in html
    assert b"<html" in html
    assert b"</html>" in html


def test_sidecar_contains_title_in_hero():
    rcp = _full_rcp()
    rcp.title = "MY UNIQUE TITLE XYZ"
    html = _render_sidecar_html(rcp)
    assert b"MY UNIQUE TITLE XYZ" in html
    # Title is inside the hero block
    assert b"<div class='hero'>" in html


def test_sidecar_contains_executive_summary_callout():
    html = _render_sidecar_html(_full_rcp())
    assert b"EXECUTIVE SUMMARY" in html
    assert b"Revenue grew 23% YoY" in html


def test_sidecar_contains_methodology_callout():
    html = _render_sidecar_html(_full_rcp())
    assert b"METHODOLOGY" in html
    assert b"Aggregated from sales_db" in html


def test_sidecar_renders_kpi_tiles():
    html = _render_sidecar_html(_full_rcp())
    assert b"Total Revenue" in html
    assert b"$1.2M" in html
    assert b"+23%" in html
    # Class .kpi is in the CSS and the markup
    assert b"class='kpis'" in html
    assert b"class='kpi'" in html


def test_sidecar_renders_key_findings_as_paragraphs():
    html = _render_sidecar_html(_full_rcp())
    assert b"Key Findings" in html
    assert b"Q3 launch drove 19% MoM conversion lift" in html
    # Findings are paragraphs, not bullets
    assert b"<div class='findings'>" in html
    assert b"<p>Q3 launch drove 19% MoM conversion lift.</p>" in html


def test_sidecar_renders_insights_as_bullets():
    html = _render_sidecar_html(_full_rcp())
    assert b"<h2>Insights</h2>" in html
    assert b"<li>APAC grew 34% QoQ.</li>" in html


def test_sidecar_renders_recommendations_as_bullets():
    html = _render_sidecar_html(_full_rcp())
    assert b"<h2>Recommendations</h2>" in html
    assert b"<li>Increase Q4 inventory by 20%.</li>" in html


def test_sidecar_renders_custom_sections():
    html = _render_sidecar_html(_full_rcp())
    assert b"<h2>Data Source</h2>" in html
    assert b"sales_db.daily_transactions" in html


def test_sidecar_renders_sql_block():
    html = _render_sidecar_html(_full_rcp())
    assert b"<h2>SQL</h2>" in html
    assert b"SELECT quarter, SUM(amount)" in html
    # SQL should be inside a <pre> for monospaced rendering
    assert b"<pre><code>" in html


def test_sidecar_omits_next_step_callout():
    # next_step is conversational guidance for the in-chat card, not report
    # content — the sidecar (report preview) must not render it.
    html = _render_sidecar_html(_full_rcp())
    assert b"Next step:" not in html
    assert b"Plan Q4 inventory." not in html


def test_sidecar_renders_data_table():
    html = _render_sidecar_html(_full_rcp())
    assert b"<h2>Data</h2>" in html
    # Headers
    assert b"<th>quarter</th>" in html
    assert b"<th>revenue</th>" in html
    # Rows
    assert b"<td>Q1</td>" in html
    assert b"<td>380</td>" in html


def test_sidecar_escapes_html_in_user_content():
    """The user's report title, summary, insights etc. must be HTML-escaped."""
    rcp = _full_rcp()
    rcp.title = "<script>alert('xss')</script>"
    rcp.summary = "Revenue <b>doubled</b>"
    html = _render_sidecar_html(rcp)
    # No literal <script> or <b> tags
    assert b"<script>" not in html
    assert b"<b>doubled</b>" not in html
    # Escaped versions are present
    assert b"&lt;script&gt;" in html
    assert b"Revenue &lt;b&gt;doubled&lt;/b&gt;" in html


def test_sidecar_works_with_minimal_payload():
    """An empty-payload fallback still produces a valid HTML page
    with the title and footer (so the preview never blanks out)."""
    rcp = ReportCardPayload(title="Minimal")
    html = _render_sidecar_html(rcp)
    assert b"<!doctype html>" in html
    assert b"Minimal" in html
    assert b"Zhanlu report" in html


def test_sidecar_sections_appear_in_declared_order():
    """Key Findings → Insights → Data → Recommendations → Custom → SQL.

    (next_step is no longer rendered in the sidecar — it is conversational
    guidance for the in-chat card, not report content.)
    """
    rcp = ReportCardPayload(
        title="Order Test",
        summary="S",
        key_findings=[InsightSpec(text="F1")],
        insights=[InsightSpec(text="I1")],
        recommendations=[InsightSpec(text="R1")],
        sections=[SectionSpec(title="C1", content="C1 content")],
        sql="SELECT 1",
        next_step="NS",
    )
    html = _render_sidecar_html(rcp)
    sections = [
        b"Key Findings",
        b"Insights",
        b"Data",
        b"Recommendations",
        b"C1",        # custom section
        b"SQL",
    ]
    indices = [html.find(s) for s in sections]
    assert all(i > 0 for i in indices), f"Some sections not found: {dict(zip(sections, indices))}"
    # Each section must appear AFTER the previous one
    assert indices == sorted(indices), f"Sections out of order: {list(zip(sections, indices))}"
