"""Generated dashboard apps package.

Each dashboard instance generated by ``services.dashboard_app.generator`` is
written under ``app/dashboards/{slug}/`` as an importable module exposing a
FastAPI ``router`` (prefix ``/api/dashboards/apps/{slug}``) plus a
``realtime.py`` background poller and a ``config.json`` for the pre-built
React frontend.
"""
