"""PPTX export — render a ReportCardPayload as a themed Zhanlu deck.

Uses python-pptx (MIT).  Slide colors come from the vendored
``theme-system`` palettes via :mod:`_theme` (default ``zhanlu-blue``
reproduces the legacy branded deck byte-for-byte).  Slides are emitted
only when their content exists:

  1.  Cover            — brand stripe, title, source, generated-at meta
  2.  Agenda           — numbered list of populated section titles
  3.  Executive Summary— summary paragraph + (optional) warning box
  4.  Key Metrics      — 2x2 / 2x3 KPI tile grid
  5.  Chart            — a native PowerPoint chart (Bar / Line / Pie)
  6.  Key Findings     — finding-accent callout + numbered bullets (<=6)
  7.  Insights         — emoji bullets (<=6)
  8.  Recommendations  — primary-accent callout + numbered bullets (<=6)
  9.  Data             — the chart's data as a banded PowerPoint table
  10. Methodology      — narrative paragraph
  11. Next Step        — closing slide mirroring the cover band

Every content slide (everything except the cover) carries a muted footer
``Generated by Zhanlu AI · N / total``.  The slide aspect is 16:9
(13.333" x 7.5").  All units are EMU (914400 per inch), wrapped in
``Inches()`` / ``Pt()``.
"""

from __future__ import annotations

import io
import re
from typing import Any, Optional

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE, XL_LEGEND_POSITION, XL_LABEL_POSITION

from app.services.synexia.contracts import (
    ChartSpec, ChartSpecInSlide, DeckPlan, InsightSpec, KPISpec, KPISpecInSlide,
    ReportCardPayload, SectionSpec, SlidePlan,
)
from app.services.artifacts.exporters._common import (
    ExportContext,
    chart_rows, chart_x_key, chart_y_keys, chart_x_value, coerce_number,
    cap_chart_categories,
    short_generated_at, insight_icon_to_emoji,
)
from app.services.artifacts.exporters._theme import (
    DeckTheme, RecipeTokens, load_theme, resolve_ctx_theme, resolve_recipe,
    _to_rgbcolor,
)


FOOTER_TEXT = "Generated by Zhanlu AI"

_EMU_PER_INCH = 914400

# --- CEO-grade helpers -------------------------------------------------------

_PERIOD_RE = re.compile(
    r"(?:January|February|March|April|May|June|July|August|September|October|November|December"
    r"|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\.?\s+\d{4}"
    r"|(?:Q[1-4]|H[1-2])\s*\d{4}"
    r"|(?:20\d{2})\s*(?:年|Year)?"
    r"|\d{4}\s*(?:年|Year)?\s*(?:\d{1,2}\s*月)?"
    r"|\d{1,2}\s*月\s*\d{4}"
    r"|\d{4}-\d{2}"
    r"|\d{4}\s*(?:vs\.?|versus|compared to)\s*\d{4}",
    re.IGNORECASE,
)


def _extract_period(text: str) -> str | None:
    """Try to pull a reporting period out of a title or source string."""
    if not text:
        return None
    m = _PERIOD_RE.search(text)
    return m.group(0) if m else None


# --- Public entry point ------------------------------------------------------


def render(payload: ReportCardPayload, ctx: Optional[ExportContext] = None) -> tuple[bytes, str, str]:
    ctx = ctx or ExportContext()

    # Fully-dynamic path: an explicit ``blocks`` list drives the layout engine
    # (the same engine the Pro deck pipeline uses) instead of the catalog order.
    _raw_blocks = getattr(payload, "blocks", None)
    if _raw_blocks:
        try:
            from app.services.artifacts.document_plan import DocumentPlan
            _plan = DocumentPlan.from_blocks(
                list(_raw_blocks),
                meta={"title": getattr(payload, "title", ""),
                      "theme": getattr(payload, "theme", "")},
            )
            return render_deck(_plan.to_deck_plan(), ctx, rows=[])
        except Exception:
            pass  # fall through to the catalog renderer

    # Resolve the design tokens once and thread them through every builder.
    # Defaults (zhanlu-blue + sharp) reproduce the legacy branded deck; a
    # tenant brand kit (ctx.theme_tokens) takes precedence when set.
    theme = resolve_ctx_theme(ctx)
    recipe = resolve_recipe(ctx.style_recipe)

    prs = Presentation()
    prs.slide_width = Inches(13.333)   # 16:9
    prs.slide_height = Inches(7.5)

    blank_layout = prs.slide_layouts[6]  # blank

    # Build slides in catalog order; each gated on its payload field.
    _add_cover_slide(prs, blank_layout, payload, ctx, theme, recipe)
    if payload.sections:
        _add_agenda_slide(prs, blank_layout, payload, theme, recipe)
    if payload.summary or payload.warnings:
        _add_summary_slide(prs, blank_layout, payload, theme, recipe)
    if payload.kpis:
        _add_kpi_slide(prs, blank_layout, payload, theme, recipe)
    if payload.chart and payload.chart.data:
        _add_chart_slide(prs, blank_layout, payload, theme, recipe)
    # Section divider before the analysis block (findings / insights).
    if (payload.key_findings or payload.insights) and _deck_is_long(payload):
        _add_section_divider(prs, blank_layout, 1, "Analysis", theme, recipe)
    if payload.key_findings:
        _add_key_findings_slide(prs, blank_layout, payload, theme, recipe)
    if payload.insights:
        _add_insights_slide(prs, blank_layout, payload, theme, recipe)
    # Section divider before the actions block (recommendations).
    if payload.recommendations and _deck_is_long(payload):
        _add_section_divider(prs, blank_layout, 2, "Actions", theme, recipe)
    if payload.recommendations:
        _add_recommendations_slide(prs, blank_layout, payload, theme, recipe)
    if payload.chart and payload.chart.data:
        _add_data_slide(prs, blank_layout, payload, theme, recipe)
    if payload.methodology:
        _add_methodology_slide(prs, blank_layout, payload, theme, recipe)
    # NOTE: no "next step" closing slide — payload.next_step is
    # conversational guidance for the in-chat card, not deck content.

    # Footers on every content slide (everything except the cover).
    _add_footers(prs, theme)

    buf = io.BytesIO()
    prs.save(buf)
    return (
        buf.getvalue(),
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        ".pptx",
    )


def render_deck(
    plan: Optional[DeckPlan],
    ctx: Optional[ExportContext] = None,
    rows: Optional[list[dict[str, Any]]] = None,
) -> tuple[bytes, str, str]:
    """Render a DeckPlan through the shared layout engine + quality pipeline.

    This is now a thin wrapper over :func:`render_dispatcher.render_pptx_from_plan`
    so the in-process exporter produces byte-identical decks to the sandbox
    renderer (both delegate to ``layout_engine``).  The dispatcher owns the
    audit + deterministic repair + (optional) polish loop.

    When ``plan`` is ``None`` or has no slides, falls back to the catalog
    renderer so callers can use a single entry point.
    """
    ctx = ctx or ExportContext()

    if not plan or not plan.slides:
        return render(
            ReportCardPayload(title=plan.title if plan else "Report"), ctx
        )

    from app.services.artifacts.render_dispatcher import render_pptx_from_plan_sync

    data, _report = render_pptx_from_plan_sync(plan, rows or [], ctx)
    return (
        data,
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        ".pptx",
    )


def _build_slide(
    prs, layout, slide: SlidePlan, rows: list[dict[str, Any]],
    section_num: int, ctx: ExportContext, theme: DeckTheme,
    recipe: RecipeTokens,
) -> int:
    """Dispatch one SlidePlan to its layout builder.

    Returns the (possibly incremented) section-number counter so section
    dividers are numbered sequentially across the deck.
    """
    kind = (slide.layout or "").strip().lower().replace("-", "_").replace(" ", "")

    if kind == "cover":
        _add_cover_slide(
            prs, layout, ReportCardPayload(title=slide.title, source=slide.subtitle),
            ctx, theme, recipe,
        )
    elif kind == "agenda":
        _add_agenda_slide(
            prs, layout,
            ReportCardPayload(
                title=slide.title,
                sections=[SectionSpec(title=b) for b in slide.bullets],
            ),
            theme, recipe,
        )
    elif kind == "kpi_grid":
        _add_kpi_slide(
            prs, layout,
            ReportCardPayload(
                title=slide.title,
                kpis=[
                    KPISpec(label=k.label, value=k.value, delta=k.delta, caption=k.caption)
                    for k in slide.kpi_specs
                ],
            ),
            theme, recipe,
        )
    elif kind in ("chart_full", "chart_with_bullets"):
        cs = slide.chart_spec
        chart = ChartSpec(
            type=(cs.chart_type if cs else "bar"),
            title=(cs.title if cs else slide.title),
            x_key=(cs.x_key if cs else ""),
            y_keys=(cs.y_keys if cs else []),
            data=_project_chart_rows(
                rows, cs.x_key if cs else "", cs.y_keys if cs else []
            ),
        )
        _add_chart_slide(
            prs, layout, ReportCardPayload(title=slide.title, chart=chart),
            theme, recipe,
        )
        if kind == "chart_with_bullets" and slide.bullets:
            _add_bullets_slide(prs, layout, slide.title, slide.bullets, theme, recipe)
    elif kind == "findings_cards":
        _add_key_findings_slide(
            prs, layout,
            ReportCardPayload(
                title=slide.title,
                key_findings=[InsightSpec(text=b) for b in slide.bullets],
            ),
            theme, recipe,
        )
    elif kind == "insights_bullets":
        _add_insights_slide(
            prs, layout,
            ReportCardPayload(
                title=slide.title,
                insights=[InsightSpec(text=b) for b in slide.bullets],
            ),
            theme, recipe,
        )
    elif kind == "recommendations":
        _add_recommendations_slide(
            prs, layout,
            ReportCardPayload(
                title=slide.title,
                recommendations=[InsightSpec(text=b) for b in slide.bullets],
            ),
            theme, recipe,
        )
    elif kind == "data_table":
        _add_data_slide(
            prs, layout,
            ReportCardPayload(title=slide.title, chart=ChartSpec(data=rows)),
            theme, recipe,
        )
    elif kind == "methodology":
        _add_methodology_slide(
            prs, layout,
            ReportCardPayload(
                title=slide.title,
                methodology=" ".join(slide.bullets) or slide.subtitle,
            ),
            theme, recipe,
        )
    elif kind == "section_divider":
        section_num += 1
        _add_section_divider(prs, layout, section_num, slide.title, theme, recipe)
    elif kind == "closing":
        _add_closing_slide(prs, layout, slide.title, theme, recipe)
    else:
        # Unknown / future layout: render a generic bullet slide so the deck
        # still renders rather than silently dropping the content.
        _add_bullets_slide(prs, layout, slide.title, slide.bullets or [slide.title],
                           theme, recipe)

    return section_num


def _project_chart_rows(
    rows: list[dict[str, Any]], x_key: str, y_keys: list[str]
) -> list[dict[str, Any]]:
    """Project raw rows down to the chart's x/y columns."""
    if not rows:
        return []
    if not x_key and not y_keys:
        return list(rows)
    out: list[dict[str, Any]] = []
    for r in rows:
        if not isinstance(r, dict):
            continue
        point: dict[str, Any] = {}
        if x_key:
            point[x_key] = r.get(x_key)
        for yk in y_keys:
            point[yk] = r.get(yk)
        if point:
            out.append(point)
    return out


def _add_bullets_slide(prs, layout, title: str, bullets: list[str],
                       theme: DeckTheme, recipe: RecipeTokens) -> None:
    """A generic title + bullets slide (chart_with_bullets, unknown layouts)."""
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_section_title(s, title or "Details", theme)
    top = Inches(1.5)
    for b in bullets[:8]:
        _add_textbox(
            s, Inches(0.6), top, Inches(12.1), Inches(0.6),
            text=f"\u2022  {b}", size=18, color=theme.text,
            font_name=theme.font_body,
        )
        top += Inches(0.65)


def _add_closing_slide(prs, layout, title: str,
                       theme: DeckTheme, recipe: RecipeTokens) -> None:
    """A closing / thank-you slide."""
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_rect(s, 0, 0, prs.slide_width, Inches(0.18), fill=theme.primary)
    _add_textbox(
        s, Inches(0.6), Inches(3.0), Inches(12.1), Inches(1.2),
        text=title or "Thank you", size=48, bold=True, color=theme.text,
        align=PP_ALIGN.CENTER, font_name=theme.font_heading,
    )


# --- Slide builders ----------------------------------------------------------


def _add_cover_slide(prs, layout, payload: ReportCardPayload, ctx: ExportContext,
                     theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)

    # Optional seeded generative cover background (Phase 4).  A subtle,
    # reproducible flow-field PNG sits behind the stripe + title.  Opt-in
    # via ExportContext.cover_art; decorative, so never breaks the render.
    if getattr(ctx, "cover_art", False):
        try:
            from app.services.artifacts.exporters._advanced import generate_cover_background
            png = generate_cover_background(theme.primary_hex, payload.title or "zhanlu")
            pic = s.shapes.add_picture(io.BytesIO(png), 0, 0,
                                       prs.slide_width, prs.slide_height)
            _send_to_back(s, pic)
        except Exception:
            pass

    # Brand stripe at the top
    _add_rect(s, 0, 0, prs.slide_width, Inches(0.18), fill=theme.primary)

    # Big title
    _add_textbox(
        s, Inches(0.6), Inches(2.3), Inches(12.1), Inches(1.4),
        text=payload.title or "Zhanlu report",
        size=44, bold=True, color=theme.text, align=PP_ALIGN.LEFT,
        font_name=theme.font_heading,
    )
    # Subtitle (source)
    if payload.source:
        _add_textbox(
            s, Inches(0.6), Inches(3.7), Inches(12.1), Inches(0.4),
            text=f"Source: {payload.source}",
            size=16, color=theme.muted, align=PP_ALIGN.LEFT,
            font_name=theme.font_body,
        )
    # Period badge (extracted from title or source)
    period = _extract_period(payload.title) or _extract_period(payload.source or "")
    if period:
        period_y = Inches(4.15)
        if not payload.source:
            period_y = Inches(3.85)
        _add_textbox(
            s, Inches(0.6), period_y, Inches(12.1), Inches(0.35),
            text=f"Period: {period}",
            size=15, color=theme.muted, align=PP_ALIGN.LEFT,
            font_name=theme.font_body,
        )

    # CEO-review badge
    _add_textbox(
        s, Inches(0.6), Inches(6.1), Inches(12.1), Inches(0.35),
        text="Prepared for CEO Review",
        size=13, color=theme.muted, align=PP_ALIGN.LEFT,
        font_name=theme.font_body,
    )

    # Meta strip at the bottom
    meta = f"Generated {short_generated_at(payload)}"
    if ctx.conversation_id:
        meta += f"  ·  conversation {ctx.conversation_id}"
    meta += f"  ·  user_signal: {payload.user_signal or 'default'}"
    _add_textbox(
        s, Inches(0.6), Inches(6.6), Inches(12.1), Inches(0.4),
        text=meta, size=11, color=theme.muted, align=PP_ALIGN.LEFT,
        font_name=theme.font_body,
    )


def _add_agenda_slide(prs, layout, payload: ReportCardPayload,
                      theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_section_title(s, "Agenda", theme)
    sections = payload.sections[:10]
    n = len(sections)
    if n <= 3:
        # vertical list (MiniMax: <=3 sections -> list)
        top = Inches(1.7)
        for i, sec in enumerate(sections, start=1):
            _add_textbox(
                s, Inches(0.8), top, Inches(11.9), Inches(0.5),
                text=f"{i}. {sec.title}",
                size=18, color=theme.text, font_name=theme.font_body,
            )
            top += Inches(0.55)
    else:
        # 2-column grid (MiniMax: 4-6 sections -> grid)
        col_w = Inches(5.9)
        gap_x = Inches(0.3)
        rows_per_col = (n + 1) // 2
        for i, sec in enumerate(sections):
            col = i // rows_per_col
            row = i % rows_per_col
            left = Inches(0.8) + col * (col_w + gap_x)
            top = Inches(1.7) + row * Inches(0.6)
            _add_textbox(
                s, left, top, col_w, Inches(0.5),
                text=f"{i + 1}. {sec.title}",
                size=18, color=theme.text, font_name=theme.font_body,
            )


def _add_summary_slide(prs, layout, payload: ReportCardPayload,
                       theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_section_title(s, "Executive Summary", theme)

    # --- Headline KPI (first KPI from payload) ---
    cursor = Inches(1.5)
    if payload.kpis:
        headline = payload.kpis[0]
        # Big value
        _add_textbox(
            s, Inches(0.6), cursor, Inches(12.1), Inches(0.9),
            text=str(headline.value or ""), size=56, bold=True,
            color=theme.primary, align=PP_ALIGN.LEFT,
            font_name=theme.font_heading,
        )
        cursor += Inches(0.85)
        # Label + delta on one line
        label_line = headline.label or ""
        if headline.delta:
            label_line += f"  ({headline.delta})"
        if label_line:
            _add_textbox(
                s, Inches(0.6), cursor, Inches(12.1), Inches(0.3),
                text=label_line, size=14, color=theme.muted,
                align=PP_ALIGN.LEFT, font_name=theme.font_body,
            )
            cursor += Inches(0.35)

    # --- Summary text ---
    if payload.summary:
        _add_textbox(
            s, Inches(0.6), cursor, Inches(12.1), Inches(2.2),
            text=payload.summary, size=18, color=theme.text,
            font_name=theme.font_body,
        )
        cursor += Inches(2.3)
    else:
        cursor += Inches(0.2)

    # --- Risk / Opportunity callout boxes (from insights) ---
    risk_insight = None
    opp_insight = None
    for ins in payload.insights or []:
        icon = (ins.icon or "").lower()
        if icon == "trending-down" and not risk_insight:
            risk_insight = ins
        elif icon in ("target", "trending-up", "zap") and not opp_insight:
            opp_insight = ins
        if risk_insight and opp_insight:
            break

    if risk_insight or opp_insight:
        box_h = Inches(1.0)
        gap = Inches(0.25)
        full_w = Inches(12.1)
        half_w = (full_w - gap) / 2
        left_x = Inches(0.6)

        if risk_insight:
            _add_callout_box(
                s, left_x, cursor, half_w, box_h,
                title="Risk", text=risk_insight.text or "",
                bg=RGBColor(0xFE, 0xF2, 0xF2),
                accent=RGBColor(0xDC, 0x26, 0x26),
                theme=theme, recipe=recipe,
            )
        if opp_insight:
            opp_x = left_x + (half_w + gap if risk_insight else Inches(0))
            opp_w = half_w if risk_insight else full_w
            _add_callout_box(
                s, opp_x, cursor, opp_w, box_h,
                title="Opportunity", text=opp_insight.text or "",
                bg=RGBColor(0xF0, 0xFD, 0xF4),
                accent=RGBColor(0x16, 0xA3, 0x4A),
                theme=theme, recipe=recipe,
            )
        cursor += box_h + Inches(0.15)

    # --- Warnings ---
    if payload.warnings:
        box_h = min(Inches(1.6), Inches(7.5) - cursor - Inches(0.3))
        if box_h > Inches(0.4):
            box = _add_rect(s, Inches(0.6), cursor, Inches(12.1), box_h,
                            fill=theme.warn_bg, border=theme.warn_accent,
                            radius_in=recipe.corner_radius_in)
            tf = box.text_frame
            tf.word_wrap = True
            tf.margin_left = Inches(0.2)
            tf.margin_right = Inches(0.2)
            tf.margin_top = Inches(0.1)
            tf.margin_bottom = Inches(0.1)
            p = tf.paragraphs[0]
            p.text = "Warnings"
            p.runs[0].font.size = Pt(16)
            p.runs[0].font.bold = True
            p.runs[0].font.color.rgb = theme.text
            _apply_font(p.runs[0], theme.font_heading)
            for w in payload.warnings:
                p2 = tf.add_paragraph()
                p2.text = f"• {w}"
                p2.runs[0].font.size = Pt(14)
                p2.runs[0].font.color.rgb = theme.text
                _apply_font(p2.runs[0], theme.font_body)


def _add_callout_box(slide, left, top, width, height, *,
                     title: str, text: str,
                     bg: RGBColor, accent: RGBColor,
                     theme: DeckTheme, recipe: RecipeTokens) -> None:
    """Render a titled callout box (Risk / Opportunity)."""
    box = _add_rect(slide, left, top, width, height,
                    fill=bg, border=accent,
                    radius_in=recipe.corner_radius_in)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.15)
    tf.margin_right = Inches(0.15)
    tf.margin_top = Inches(0.1)
    tf.margin_bottom = Inches(0.1)
    p = tf.paragraphs[0]
    p.text = title
    p.runs[0].font.size = Pt(14)
    p.runs[0].font.bold = True
    p.runs[0].font.color.rgb = accent
    _apply_font(p.runs[0], theme.font_heading)
    if text:
        p2 = tf.add_paragraph()
        p2.text = text
        p2.runs[0].font.size = Pt(12)
        p2.runs[0].font.color.rgb = theme.text
        _apply_font(p2.runs[0], theme.font_body)


def _add_kpi_slide(prs, layout, payload: ReportCardPayload,
                   theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_section_title(s, "Key Metrics", theme)

    n = len(payload.kpis)

    if n == 1:
        # Hero stat callout (MiniMax stat-callout: a single 60-96pt figure).
        k = payload.kpis[0]
        _add_textbox(
            s, Inches(0.6), Inches(2.1), Inches(12.1), Inches(2.2),
            text=k.value or "\u2014", size=96, bold=True, color=theme.primary,
            font_name=theme.font_heading,
        )
        _add_textbox(
            s, Inches(0.6), Inches(4.4), Inches(12.1), Inches(0.5),
            text=(k.label or "").upper(), size=18, bold=True, color=theme.muted,
            font_name=theme.font_body,
        )
        if k.delta:
            d = k.delta.strip()
            dcolor = (theme.delta_up if d.startswith(("+", "\u25B2"))
                      else theme.delta_down if d.startswith(("-", "\u25BC"))
                      else theme.muted)
            _add_textbox(
                s, Inches(0.6), Inches(5.0), Inches(12.1), Inches(0.5),
                text=k.delta, size=22, bold=True, color=dcolor,
                font_name=theme.font_body,
            )
        if k.caption:
            _add_textbox(
                s, Inches(0.6), Inches(5.6), Inches(12.1), Inches(0.5),
                text=k.caption, size=14, color=theme.muted,
                font_name=theme.font_body,
            )
        return

    # Grid (2x1 / 2x2 / 2x3) for 2-6 KPIs.
    if n == 2:
        ncols, nrows = 2, 1
    elif n <= 4:
        ncols, nrows = 2, 2
    else:
        ncols, nrows = 2, 3   # cap at 6

    cell_w = Inches(5.8)
    cell_h = Inches(2.5)
    gap = Inches(0.2)
    left0 = Inches(0.6)
    top0 = Inches(1.5)

    for idx, k in enumerate(payload.kpis[: ncols * nrows]):
        col = idx % ncols
        row = idx // ncols
        left = left0 + (cell_w + gap) * col
        top = top0 + (cell_h + gap) * row

        box = _add_rect(s, left, top, cell_w, cell_h, fill=theme.kpi_bg,
                        border=theme.border, radius_in=recipe.corner_radius_in)

        tf = box.text_frame
        tf.word_wrap = True
        tf.margin_left = Inches(0.25)
        tf.margin_right = Inches(0.25)
        tf.margin_top = Inches(0.15)
        tf.margin_bottom = Inches(0.15)

        # Label
        p = tf.paragraphs[0]
        p.text = (k.label or "").upper()
        p.runs[0].font.size = Pt(11)
        p.runs[0].font.bold = True
        p.runs[0].font.color.rgb = theme.muted
        _apply_font(p.runs[0], theme.font_body)

        # Value
        p2 = tf.add_paragraph()
        run = p2.add_run()
        run.text = k.value or "—"
        run.font.size = Pt(36)
        run.font.bold = True
        run.font.color.rgb = theme.text
        _apply_font(run, theme.font_heading)

        if k.delta:
            run2 = p2.add_run()
            run2.text = f"   {k.delta}"
            d = k.delta.strip()
            if d.startswith("+") or d.startswith("\u25B2"):
                run2.font.color.rgb = theme.delta_up
            elif d.startswith("-") or d.startswith("\u25BC"):
                run2.font.color.rgb = theme.delta_down
            else:
                run2.font.color.rgb = theme.muted
            run2.font.size = Pt(18)
            run2.font.bold = True
            _apply_font(run2, theme.font_body)

        if k.caption:
            p3 = tf.add_paragraph()
            p3.text = k.caption
            p3.runs[0].font.size = Pt(12)
            p3.runs[0].font.color.rgb = theme.muted
            _apply_font(p3.runs[0], theme.font_body)


def _add_chart_slide(prs, layout, payload: ReportCardPayload,
                     theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_section_title(s, payload.chart.title or "Chart", theme)

    rows = chart_rows(payload)
    y_keys = chart_y_keys(payload)
    if not rows or not y_keys:
        return

    # Shared data-prep cap: top-8 categories by value + "Other" bucket.
    x_key = chart_x_key(payload)
    rows = cap_chart_categories(rows, x_key, y_keys)

    chart_type = (payload.chart.type or "bar").lower()
    chart_data = CategoryChartData()
    chart_data.categories = [str(chart_x_value(r, payload)) for r in rows]
    for k in y_keys:
        chart_data.add_series(k, [coerce_number(r.get(k)) or 0 for r in rows])

    x_pos = Inches(0.6)
    y_pos = Inches(1.5)
    cx = Inches(12.1)
    cy = Inches(5.6)

    if chart_type == "line":
        chart_shape = s.shapes.add_chart(
            XL_CHART_TYPE.LINE, x_pos, y_pos, cx, cy, chart_data
        )
    elif chart_type == "pie":
        chart_shape = s.shapes.add_chart(
            XL_CHART_TYPE.PIE, x_pos, y_pos, cx, cy, chart_data
        )
    elif chart_type == "grouped_bar":
        chart_shape = s.shapes.add_chart(
            XL_CHART_TYPE.BAR_CLUSTERED, x_pos, y_pos, cx, cy, chart_data
        )
    elif chart_type == "stacked_bar":
        chart_shape = s.shapes.add_chart(
            XL_CHART_TYPE.BAR_STACKED, x_pos, y_pos, cx, cy, chart_data
        )
    elif chart_type == "stacked_column":
        chart_shape = s.shapes.add_chart(
            XL_CHART_TYPE.COLUMN_STACKED, x_pos, y_pos, cx, cy, chart_data
        )
    elif chart_type == "grouped_column":
        chart_shape = s.shapes.add_chart(
            XL_CHART_TYPE.COLUMN_CLUSTERED, x_pos, y_pos, cx, cy, chart_data
        )
    else:
        chart_shape = s.shapes.add_chart(
            XL_CHART_TYPE.COLUMN_CLUSTERED, x_pos, y_pos, cx, cy, chart_data
        )

    # Accessibility: alt text on the chart (cNvPr@descr) so check_alt_text
    # passes and screen readers can describe the graphic.
    _set_alt_text(chart_shape, f"Chart: {payload.chart.title or payload.chart.type or 'chart'}")

    chart = chart_shape.chart
    chart.has_title = False
    chart.has_legend = True
    if len(y_keys) > 1:
        chart.legend.position = XL_LEGEND_POSITION.BOTTOM
        chart.legend.include_in_layout = False
    else:
        chart.has_legend = False

    # Apply the theme chart palette to every series so the deck's brand
    # colors flow through to the native chart (instead of default blue).
    palette = theme.chart_palette or []
    if palette:
        for i, series in enumerate(chart.series):
            try:
                rgb = _to_rgbcolor(palette[i % len(palette)])
                series.format.fill.solid()
                series.format.fill.fore_color.rgb = rgb
            except Exception:
                # A single series we can't recolor shouldn't break the deck.
                pass

    # Traceability footnote: cite the data source on the headline chart.
    _add_source_footnote(s, payload.source, theme)


def _add_key_findings_slide(prs, layout, payload: ReportCardPayload,
                            theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    items = payload.key_findings[:6]
    n = len(items)
    headline = _derive_headline(items, "Key Findings")

    if n == 1:
        # Single-finding assertion slide: eyebrow + big takeaway.
        _add_textbox(
            s, Inches(0.6), Inches(0.45), Inches(12.1), Inches(0.35),
            text="Key Findings", size=13, bold=True, color=theme.primary,
            font_name=theme.font_heading,
        )
        _add_textbox(
            s, Inches(0.6), Inches(2.4), Inches(12.1), Inches(2.6),
            text=items[0].text, size=40, bold=True, color=theme.text,
            font_name=theme.font_heading,
        )
        _add_rect(s, Inches(0.6), Inches(5.2), Inches(1.2), Inches(0.05),
                  fill=theme.primary)
        return

    if n in (2, 3):
        # Comparison cards side-by-side (a distinct layout family).
        _title_block(s, "Key Findings", theme, headline)
        gap = Inches(0.3)
        card_w = (Inches(12.1) - gap * (n - 1)) / n
        card_top = Inches(2.2)
        card_h = Inches(4.6)
        for i, kf in enumerate(items):
            left = Inches(0.6) + i * (card_w + gap)
            card = _add_rect(s, left, card_top, card_w, card_h,
                             fill=theme.finding_bg, border=theme.finding_accent,
                             radius_in=recipe.corner_radius_in)
            tf = card.text_frame
            tf.word_wrap = True
            tf.margin_left = Inches(0.25)
            tf.margin_right = Inches(0.25)
            tf.margin_top = Inches(0.25)
            tf.margin_bottom = Inches(0.25)
            p = tf.paragraphs[0]
            r = p.add_run()
            r.text = f"{i + 1:02d}"
            r.font.size = Pt(36)
            r.font.bold = True
            r.font.color.rgb = theme.finding_accent
            _apply_font(r, theme.font_heading)
            p2 = tf.add_paragraph()
            r2 = p2.add_run()
            r2.text = kf.text
            r2.font.size = Pt(18)
            r2.font.color.rgb = theme.text
            _apply_font(r2, theme.font_body)
        return

    # Callout box: assertion headline + supporting bullets (4-6 findings).
    body_top = _title_block(s, "Key Findings", theme, headline)
    box_h = 6.8 - body_top
    box = _add_rect(s, Inches(0.6), Inches(body_top), Inches(12.1), Inches(box_h),
                    fill=theme.finding_bg, border=theme.finding_accent,
                    radius_in=recipe.corner_radius_in)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.3)
    tf.margin_right = Inches(0.3)
    tf.margin_top = Inches(0.2)
    tf.margin_bottom = Inches(0.2)
    body_items = items[1:] if headline else items
    for i, kf in enumerate(body_items, start=1):
        p = tf.paragraphs[0] if i == 1 else tf.add_paragraph()
        p.space_after = Pt(8)
        run = p.add_run()
        run.text = f"{i}. {kf.text}"
        run.font.size = Pt(18)
        run.font.color.rgb = theme.text
        _apply_font(run, theme.font_body)


def _add_insights_slide(prs, layout, payload: ReportCardPayload,
                        theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    items = payload.insights[:6]
    headline = _derive_headline(items, "Insights")
    body_top = _title_block(s, "Insights", theme, headline)
    top = Inches(body_top + 0.1)
    body_items = items[1:] if headline else items
    for ins in body_items:
        emoji = insight_icon_to_emoji(ins.icon)
        _add_textbox(
            s, Inches(0.6), top, Inches(12.1), Inches(0.6),
            text=f"{emoji}  {ins.text}",
            size=18, color=theme.text, font_name=theme.font_body,
        )
        top += Inches(0.7)


def _add_recommendations_slide(prs, layout, payload: ReportCardPayload,
                               theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    items = payload.recommendations[:6]
    n = len(items)
    headline = _derive_headline(items, "Recommendations")

    if n == 1:
        # Single-recommendation assertion slide.
        _add_textbox(
            s, Inches(0.6), Inches(0.45), Inches(12.1), Inches(0.35),
            text="Recommendations", size=13, bold=True, color=theme.primary,
            font_name=theme.font_heading,
        )
        _add_textbox(
            s, Inches(0.6), Inches(2.4), Inches(12.1), Inches(2.6),
            text=items[0].text, size=40, bold=True, color=theme.text,
            font_name=theme.font_heading,
        )
        _add_rect(s, Inches(0.6), Inches(5.2), Inches(1.2), Inches(0.05),
                  fill=theme.primary)
        return

    body_top = _title_block(s, "Recommendations", theme, headline)
    box_h = 6.8 - body_top
    box = _add_rect(s, Inches(0.6), Inches(body_top), Inches(12.1), Inches(box_h),
                    fill=theme.rec_bg, border=theme.primary,
                    radius_in=recipe.corner_radius_in)
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.3)
    tf.margin_right = Inches(0.3)
    tf.margin_top = Inches(0.2)
    tf.margin_bottom = Inches(0.2)
    body_items = items[1:] if headline else items
    for i, rec in enumerate(body_items, start=1):
        p = tf.paragraphs[0] if i == 1 else tf.add_paragraph()
        p.space_after = Pt(8)
        run = p.add_run()
        run.text = f"{i}. {rec.text}"
        run.font.size = Pt(18)
        run.font.color.rgb = theme.text
        _apply_font(run, theme.font_body)


def _add_data_slide(prs, layout, payload: ReportCardPayload,
                    theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_section_title(s, "Data", theme)

    rows = chart_rows(payload)
    if not rows:
        return
    keys = list(rows[0].keys())
    nrows = min(len(rows) + 1, 25)  # header + up to 24 data rows on a slide
    ncols = len(keys)

    table_shape = s.shapes.add_table(
        nrows, ncols, Inches(0.6), Inches(1.5), Inches(12.1), Inches(5.5)
    )
    table = table_shape.table
    # Header row
    for ci, k in enumerate(keys):
        cell = table.cell(0, ci)
        cell.text = k
        for p in cell.text_frame.paragraphs:
            for r in p.runs:
                r.font.size = Pt(11)
                r.font.bold = True
                r.font.color.rgb = theme.text
                _apply_font(r, theme.font_heading)
        _set_cell_bg(cell, theme.band_bg)

    # Data rows (banded)
    for ri, row in enumerate(rows[: nrows - 1], start=1):
        for ci, k in enumerate(keys):
            v = row.get(k, "")
            s_v = "" if v is None else str(v)
            if len(s_v) > 80:
                s_v = s_v[:80] + "…"
            cell = table.cell(ri, ci)
            cell.text = s_v
            for p in cell.text_frame.paragraphs:
                for r in p.runs:
                    r.font.size = Pt(10)
                    r.font.color.rgb = theme.text
                    _apply_font(r, theme.font_body)
            if ri % 2 == 0:
                _set_cell_bg(cell, theme.band_bg)

    if len(rows) > nrows - 1:
        # Combine the truncation note with the source citation when both
        # apply so the bottom-left stays a single traceability line.
        note = f"\u2026 {len(rows) - (nrows - 1)} more rows truncated for slide."
        if (payload.source or "").strip():
            note = f"Source: {payload.source}  \u00b7  {note}"
        _add_textbox(
            s, Inches(0.6), Inches(7.1), Inches(12.1), Inches(0.3),
            text=note, size=10, color=theme.muted, font_name=theme.font_body,
        )
    else:
        _add_source_footnote(s, payload.source, theme)


def _add_methodology_slide(prs, layout, payload: ReportCardPayload,
                           theme: DeckTheme, recipe: RecipeTokens) -> None:
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_section_title(s, "Methodology", theme)
    _add_textbox(
        s, Inches(0.6), Inches(1.5), Inches(12.1), Inches(5.5),
        text=payload.methodology, size=18, color=theme.text,
        font_name=theme.font_body,
    )


def _add_footers(prs, theme: DeckTheme) -> None:
    """Stamp ``Generated by Zhanlu AI · N / total`` on every non-cover slide."""
    total = len(prs.slides)
    for i, slide in enumerate(prs.slides, start=1):
        if i == 1:
            continue  # cover has no footer
        _add_textbox(
            slide, Inches(9.0), Inches(7.05), Inches(4.0), Inches(0.3),
            text=f"{FOOTER_TEXT} · {i} / {total}",
            size=10, color=theme.muted, align=PP_ALIGN.RIGHT,
            font_name=theme.font_body,
        )


# --- Low-level shape helpers -------------------------------------------------


def _add_section_title(slide, text: str, theme: DeckTheme) -> None:
    """H1 heading + a 2px brand accent rule under it (content slides)."""
    _add_textbox(
        slide, Inches(0.6), Inches(0.5), Inches(12.1), Inches(0.7),
        text=text, size=28, bold=True, color=theme.text,
        font_name=theme.font_heading,
    )
    _add_rect(slide, Inches(0.6), Inches(1.25), Inches(1.2), Inches(0.05),
              fill=theme.primary)


def _derive_headline(items, fallback: str) -> Optional[str]:
    """One-line takeaway from the first item, or None to keep the label title.

    Used for the assertion-evidence title pattern: the first finding /
    insight / recommendation becomes a big headline and the label
    ("Key Findings") becomes a small eyebrow above it.  Returns None when
    there's no usable text so the caller falls back to the legacy
    label-only title.
    """
    if not items:
        return None
    first = items[0]
    text = getattr(first, "text", None) or (first if isinstance(first, str) else "")
    text = (text or "").strip()
    if not text:
        return None
    if len(text) > 90:
        text = text[:87].rstrip() + "\u2026"
    return text


def _title_block(slide, label: str, theme: DeckTheme,
                 headline: Optional[str] = None) -> float:
    """Draw a content-slide title; return the y (inches) where the body starts.

    Without ``headline``: an H1 label + a 2px accent rule (legacy) — body
    starts at 1.5".  With ``headline``: a small primary eyebrow (the
    label) above a larger assertion headline + accent rule — body starts
    at 2.0".  The label text is always rendered so callers/tests that
    grep for it (e.g. "Key Findings") still match.
    """
    if not headline:
        _add_textbox(
            slide, Inches(0.6), Inches(0.5), Inches(12.1), Inches(0.7),
            text=label, size=28, bold=True, color=theme.text,
            font_name=theme.font_heading,
        )
        _add_rect(slide, Inches(0.6), Inches(1.25), Inches(1.2), Inches(0.05),
                  fill=theme.primary)
        return 1.5
    _add_textbox(
        slide, Inches(0.6), Inches(0.45), Inches(12.1), Inches(0.35),
        text=label, size=13, bold=True, color=theme.primary,
        font_name=theme.font_heading,
    )
    _add_textbox(
        slide, Inches(0.6), Inches(0.8), Inches(12.1), Inches(1.0),
        text=headline, size=30, bold=True, color=theme.text,
        font_name=theme.font_heading,
    )
    _add_rect(slide, Inches(0.6), Inches(1.85), Inches(1.2), Inches(0.05),
              fill=theme.primary)
    return 2.0


def _add_section_divider(prs, layout, number: int, title: str,
                         theme: DeckTheme, recipe: RecipeTokens) -> None:
    """A visually distinct transition slide between major deck sections.

    White background + a full-height primary bar on the left edge + a
    huge primary section number + the section title.  Kept on the white
    background (rather than full-bleed primary) so the standard muted
    footer stays readable and the existing footer contract holds.
    """
    s = prs.slides.add_slide(layout)
    _set_bg(s, theme.slide_bg)
    _add_rect(s, 0, 0, Inches(0.35), prs.slide_height, fill=theme.primary)
    _add_textbox(
        s, Inches(0.9), Inches(2.3), Inches(11.0), Inches(1.8),
        text=f"{number:02d}", size=96, bold=True, color=theme.primary,
        font_name=theme.font_heading,
    )
    _add_textbox(
        s, Inches(0.9), Inches(4.2), Inches(11.0), Inches(1.2),
        text=title, size=40, bold=True, color=theme.text,
        font_name=theme.font_heading,
    )


def _deck_is_long(payload: ReportCardPayload) -> bool:
    """True when the deck has enough content to warrant section dividers."""
    n = 0
    if payload.sections:
        n += 1
    if payload.summary or payload.warnings:
        n += 1
    if payload.kpis:
        n += 1
    if payload.chart and payload.chart.data:
        n += 1  # chart slide
    if payload.key_findings:
        n += 1
    if payload.insights:
        n += 1
    if payload.recommendations:
        n += 1
    if payload.chart and payload.chart.data:
        n += 1  # data slide
    if payload.methodology:
        n += 1
    return n >= 6


def _add_textbox(slide, left, top, width, height, *,
                 text: str, size: int, bold: bool = False,
                 color=None, align=PP_ALIGN.LEFT,
                 font_name: Optional[str] = None) -> None:
    tb = slide.shapes.add_textbox(left, top, width, height)
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0)
    tf.margin_right = Inches(0)
    tf.margin_top = Inches(0)
    tf.margin_bottom = Inches(0)
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text or ""
    run.font.size = Pt(size)
    run.font.bold = bold
    if font_name is not None:
        run.font.name = font_name
    if color is not None:
        run.font.color.rgb = color


def _apply_font(run, font_name: Optional[str]) -> None:
    """Set the run's typeface when a theme font name is supplied."""
    if font_name:
        try:
            run.font.name = font_name
        except Exception:
            pass


def _add_rect(slide, left, top, width, height, *,
              fill=None, border=None, radius_in: float = 0.0) -> Any:
    """A filled rectangle, optionally with rounded corners.

    ``radius_in`` is the desired corner radius in inches.  When > 0 a
    ``ROUNDED_RECTANGLE`` autoshape is used with its adjustment (a
    fraction of the shorter side) clamped to [0, 0.5]; otherwise a plain
    ``RECTANGLE`` (the legacy default, byte-identical output).
    """
    if radius_in and radius_in > 0.0:
        shape = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE, left, top, width, height
        )
        try:
            w_in = float(int(width)) / _EMU_PER_INCH
            h_in = float(int(height)) / _EMU_PER_INCH
            shorter = min(w_in, h_in) or 1.0
            adj = max(0.0, min(0.5, radius_in / shorter))
            shape.adjustments[0] = adj
        except Exception:
            pass  # keep default adjustment if geometry unreadable
    else:
        shape = slide.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, left, top, width, height
        )
    shape.shadow.inherit = False
    if fill is not None:
        shape.fill.solid()
        shape.fill.fore_color.rgb = fill
    else:
        shape.fill.background()
    if border is not None:
        shape.line.color.rgb = border
        shape.line.width = Pt(0.75)
    else:
        shape.line.fill.background()
    # Remove default text
    shape.text_frame.text = ""
    return shape


def _set_bg(slide, color) -> None:
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _set_cell_bg(cell, color) -> None:
    cell.fill.solid()
    cell.fill.fore_color.rgb = color


def _set_alt_text(shape, descr: str) -> None:
    """Set ``cNvPr@descr`` (alt text) on a picture or graphicFrame (chart).

    Used so the audit's ``check_alt_text`` passes for exporter-emitted
    charts and the deck is screen-reader accessible.
    """
    try:
        cNvPr = shape._element.find(".//{*}cNvPr")
        if cNvPr is not None:
            cNvPr.set("descr", descr)
    except Exception:
        pass


def _send_to_back(slide, shape) -> None:
    """Move ``shape`` to the bottom of the slide's z-order (behind others).

    Used to place the generative cover background behind the brand stripe
    and title.  Re-inserts the element right after the spTree's
    ``nvGrpSpPr`` + ``grpSpPr`` (the first two children).
    """
    try:
        spTree = slide.shapes._spTree
        spTree.remove(shape._element)
        spTree.insert(2, shape._element)
    except Exception:
        pass


def _add_source_footnote(slide, source: str, theme: DeckTheme) -> None:
    """Traceability footnote (``Source: <source>``) on data-bearing slides.

    Bottom-left, muted — sits beside (not over) the right-aligned page
    footer.  No-op when no source is set.
    """
    if not (source or "").strip():
        return
    _add_textbox(
        slide, Inches(0.6), Inches(7.1), Inches(8.0), Inches(0.3),
        text=f"Source: {source}", size=10, color=theme.muted,
        font_name=theme.font_body,
    )
