"""LLM-driven deck planner.

Turns raw data rows + user intent into a :class:`DeckPlan` (a narrative
slide sequence) and maps that plan onto :class:`ReportCardPayload` for
the structured renderer.  This is a single, bounded LLM call gated by
``PPT_DECK_PLANNER_ENABLED`` — when disabled, the pipeline falls straight
through to the existing report-card renderer.

The planner is intentionally deterministic in its fallbacks: if the LLM
call fails or times out, it synthesizes a minimal 3-slide plan from the
data profile so the deck still renders.
"""

from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path
from typing import Any, Optional

from app.config import settings
from app.services.artifacts.exporters._theme import load_theme, validate_theme_name
from app.services.synexia.contracts import (
    ChartSpecInSlide,
    ChartSpec,
    DeckPlan,
    KPISpec,
    KPISpecInSlide,
    InsightSpec,
    ReportCardPayload,
    SlidePlan,
)

from .data_profiler import profile_rows, suggest_charts, summarize_profile

logger = logging.getLogger(__name__)

_PLANNER_TIMEOUT_S = 10.0

# Valid layouts the planner may emit (mirrors the layout engine dispatch).
_VALID_LAYOUTS = {
    "cover", "agenda", "kpi_grid", "chart_full", "chart_with_bullets",
    "findings_cards", "insights_bullets", "recommendations", "data_table",
    "methodology", "section_divider", "closing",
    # New archetypes (2026-08-29)
    "timeline", "roadmap", "comparison", "swot", "quote", "process_flow",
}

# Compact methodology distilled from skills/document-skills/pptx/SKILL.md — the
# slide-master / typography / density / audit rules the layout engine enforces.
# Loaded lazily via _load_skill_methodology() so the planner prompt stays
# grounded in the proven skill without embedding the whole 25 KB file.
_PPTX_SKILL_METHODOLOGY = """\
PPT deck methodology (condensed from the pptx SKILL):
- Headlines MUST be assertions, not topic labels. "Revenue grew 8% QoQ" not
  "Key Findings". Rewrite any topic-label title into a complete sentence that
  states the takeaway.
- Density budget: at most 5 bullets per block; each bullet <= 12 words; body
  font >= 14pt. Prefer 3-4 bullets; split long bullets.
- Layout enum (pick the closest): cover, agenda, kpi_grid, chart_full,
  chart_with_bullets, findings_cards, insights_bullets, recommendations,
  data_table, section_divider, closing, methodology.
- Data tables: summarize top-8 rows, highlight top-3; full data only in an
  appendix when explicitly requested. Never paste raw rows verbatim as prose.
- Charts: one message per chart; brand colors; data labels on; gridlines off;
  legend at bottom. Use chart_full for a single hero chart, chart_with_bullets
  to pair a chart with 2-3 takeaways.
- No "Generated by" footer; subtle slide numbers only. Every image/shape needs
  alt text. No orphan media — every visual must map to a stated takeaway.
- Keep slide count 8-12; cover + agenda + (per section: divider, evidence,
  insight) + recommendations + closing.
"""


def _load_skill_methodology() -> str:
    """Return the condensed pptx SKILL methodology for prompt injection.

    Tries to read the live SKILL.md and extract its methodology section; falls
    back to the bundled constant so the planner never hard-fails on a missing
    file.  The SKILL is large, so we only inline the distilled rules.
    """
    try:
        skill_path = (
            Path(__file__).resolve().parents[3]
            / "skills" / "document-skills" / "pptx" / "SKILL.md"
        )
        if skill_path.exists():
            text = skill_path.read_text(encoding="utf-8", errors="ignore")
            # Inline the whole methodology only if it is reasonably small;
            # otherwise use the condensed constant to protect the prompt budget.
            if len(text) <= 4000:
                return text
    except Exception as exc:  # pragma: no cover — best-effort grounding
        logger.warning("deck_planner: could not load pptx SKILL.md: %s", exc)
    return _PPTX_SKILL_METHODOLOGY


# JSON schema for the LLM structured output.
_PLAN_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "title": {"type": "string"},
        "deck_type": {
            "type": "string",
            "enum": ["data_report", "investor_deck", "marketing", "executive_brief"],
        },
        "theme_recommendation": {"type": "string", "enum": [
            "bold_signal", "electric_studio", "creative_voltage",
            "dark_botanical", "notebook_tabs", "pastel_geometry",
            "split_pastel", "vintage_editorial", "neon_cyber",
            "terminal_green", "swiss_modern", "paper_and_ink",
        ]},
        "palette_recommendation": {"type": "string", "enum": [
            "saas_blue", "micro_indigo", "commerce_green", "luxury_gold",
            "b2b_navy", "finance_dark", "analytics_amber", "health_teal",
            "edu_indigo", "agency_pink", "gaming_violet", "ai_violet",
            "logistics_blue", "energy_green", "travel_sky", "legal_royal",
        ]},
        "summary": {"type": "string"},
        "methodology": {"type": "string"},
        "headline_style": {"type": "string", "enum": ["topic", "assertion"]},
        "slides": {
            "type": "array",
            "minItems": 3,
            "maxItems": 20,
            "items": {
                "type": "object",
                "properties": {
                    "layout": {
                        "type": "string",
                        "enum": [
                            "cover", "agenda", "kpi_grid", "chart_full",
                            "chart_with_bullets", "findings_cards", "insights_bullets",
                            "recommendations", "data_table", "section_divider", "closing",
                            "timeline", "roadmap", "comparison", "swot", "quote",
                            "process_flow",
                        ],
                    },
                    "title": {"type": "string"},
                    "subtitle": {"type": "string"},
                    "bullets": {"type": "array", "items": {"type": "string"}},
                    "narrative_role": {
                        "type": "string",
                        "enum": ["hook", "context", "evidence", "insight", "action", "closing"],
                    },
                    "chart_spec": {
                        "type": "object",
                        "properties": {
                            "chart_type": {
                                "type": "string",
                                "enum": [
                                    "bar", "column", "line", "pie",
                                    "grouped_bar", "grouped_column",
                                    "stacked_bar", "stacked_column", "donut",
                                ],
                            },
                            "x_key": {"type": "string"},
                            "y_keys": {"type": "array", "items": {"type": "string"}},
                            "title": {"type": "string"},
                        },
                    },
                    "kpi_specs": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "label": {"type": "string"},
                                "value": {"type": "string"},
                                "delta": {"type": "string"},
                                "caption": {"type": "string"},
                            },
                        },
                    },
                    "notes": {"type": "string"},
                    "headline_style": {"type": "string", "enum": ["topic", "assertion"]},
                    "max_bullets": {"type": "integer", "minimum": 1, "maximum": 5},
                    "max_words_per_bullet": {"type": "integer", "minimum": 4, "maximum": 12},
                },
                "required": ["layout", "title"],
            },
        },
    },
    "required": ["title", "slides"],
}


def _build_planner_prompt(
    user_intent: str,
    profile_summary: str,
    chart_hints: list[dict[str, Any]],
    row_count: int,
    theme_name: str = "zhanlu-blue",
    theme_mood: str = "",
    *,
    theme_tokens: Optional[dict[str, Any]] = None,
    personalization: Optional[dict[str, Any]] = None,
    skill_structure: str = "",
) -> str:
    chart_lines = "\n".join(
        f"- {c['chart_type']} | x={c['x_key']} | y={c['y_keys']} | {c['title']}"
        for c in chart_hints
    ) or "(none)"
    methodology = _load_skill_methodology()
    theme_guidance = (
        "\nTHEME: pick ONE theme from the catalog that best fits this deck's "
        "content and audience, and set theme_recommendation to it. Do NOT "
        "just echo the context theme.\n"
        "Catalog (name — mood):\n"
        "- bold_signal — bold, confident, high-contrast investor energy\n"
        "- electric_studio — modern, tech-forward, vibrant\n"
        "- creative_voltage — playful, colorful, marketing energy\n"
        "- dark_botanical — calm, premium, dark natural\n"
        "- notebook_tabs — academic, structured, study notes\n"
        "- pastel_geometry — soft, friendly, approachable\n"
        "- split_pastel — balanced two-tone, editorial\n"
        "- vintage_editorial — classic magazine, serif elegance\n"
        "- neon_cyber — futuristic, high-energy, tech\n"
        "- terminal_green — hacker/monospace aesthetic\n"
        "- swiss_modern — clean grid, strict, Swiss typography (business default)\n"
        "- paper_and_ink — editorial, minimalist, print feel\n"
        + f"Context theme is '{theme_name}'"
        + (f" ({theme_mood})" if theme_mood else "")
        + " — use it only if it truly fits; otherwise pick the best catalog "
          "match. Match copy tone to the chosen theme's mood: an "
          "authoritative/executive theme wants punchy assertion headlines; "
          "a warm/creative theme can use more evocative phrasing.\n"
    )
    palette_guidance = _build_palette_guidance()
    brand_guidance = _build_brand_guidance(theme_tokens)
    audience_guidance = _build_audience_guidance(personalization)
    return (
        "You are a presentation architect. Build a concise, narrative slide "
        "sequence for the following request.\n\n"
        f"USER INTENT:\n{user_intent}\n\n"
        f"DATA (rows={row_count}):\n{profile_summary}\n\n"
        f"SUGGESTED CHARTS:\n{chart_lines}\n\n"
        "STRICT RULES (you must obey every one):\n"
        "- Output valid JSON matching the requested schema.\n"
        "- 8-20 slides (up to 20 for multi-dimensional reports). First slide "
        "layout 'cover', last 'closing'.\n"
        "- Use layouts only from the schema enum: cover, agenda, kpi_grid, "
        "chart_full, chart_with_bullets, findings_cards, insights_bullets, "
        "recommendations, data_table, section_divider, closing, timeline, "
        "roadmap, comparison, swot, quote, process_flow.\n"
        "- LAYOUT SELECTION (use the new archetypes deliberately): 'timeline' "
        "for chronological milestones (bullets 'date | label'), 'roadmap' for "
        "Now/Next/Later phases (bullets 'phase | item'), 'comparison' for "
        "two-option trade-offs (bullets 'A vs B'), 'swot' for strengths/"
        "weaknesses/opportunities/threats (bullets 'S|...'/'W|...'/'O|...'/"
        "'T|...'), 'quote' for a pull-quote slide (title=quote, "
        "subtitle=attribution), 'process_flow' for numbered steps. Prefer "
        "these over generic insights_bullets when the content fits.\n"
        "- ASSERTION HEADLINES: every slide 'title' must be a complete "
        "assertion sentence stating the takeaway, NOT a topic label. "
        "Rewrite 'Key Findings' -> 'Enterprise drove 60% of net new bookings'. "
        "Set slide.headline_style='assertion'. Keep title <= 12 words.\n"
        "- SPEAKER NOTES (MANDATORY): every slide must carry a 'notes' field "
        "with 1-2 sentences of presenter script — what to say, why it "
        "matters, and the bridge to the next slide. Never leave notes "
        "empty. These are written into PowerPoint's notes pane so the "
        "deck is presentation-ready out of the box.\n"
        "- DENSITY BUDGET: at most 5 bullets per slide; each bullet <= 12 "
        "words; set slide.max_bullets=5 and slide.max_words_per_bullet=12. "
        "Prefer 3-4 bullets; split long bullets.\n"
        "- x_key / y_keys must match actual column names in the data.\n"
        "- MULTI-DIMENSION RULE (HARD): when the user asks for breakdowns by "
        "multiple dimensions (e.g. 'by product, by customer, by region'), "
        "produce ONE dedicated chart slide PER dimension, each using a "
        "'chart_full' or 'chart_with_bullets' layout with that dimension as "
        "the x_key. Do NOT cram multiple dimensions into one chart. Add a "
        "'section_divider' before each dimension's chart slides when there "
        "are 3+ dimensions.\n"
        "- CHART TYPES: use 'grouped_bar'/'grouped_column' to compare a "
        "measure across 2 series (e.g. revenue this month vs last month per "
        "product), and 'stacked_bar'/'stacked_column' to show composition "
        "breakdowns (e.g. revenue by product stacked by region). Prefer "
        "'pie'/'donut' only for a single share-of-total dimension with <= 6 "
        "segments.\n"
        "- For data-heavy decks prefer deck_type 'data_report' and reference "
        "the suggested charts. For 'beautiful'/'investor'/'pitch' requests use "
        "'investor_deck' or 'marketing' and lean on cover / section_divider / "
        "kpi_grid layouts.\n\n"
        f"{theme_guidance}\n"
        f"{palette_guidance}\n"
        f"{brand_guidance}\n"
        f"{audience_guidance}"
        f"{skill_structure}"
        "METHODOLOGY (from the pptx skill — follow it):\n"
        f"{methodology}\n"
    )


def _build_palette_guidance() -> str:
    """Return a PALETTE block so the planner picks a color identity per deck.

    Theme = structure/mood; palette = color identity.  The two are
    independent axes: the same market deck can carry an Analytics-blue
    identity on a Swiss grid or a Luxury-gold identity on Paper & Ink.
    """
    from app.services.artifacts.palettes import PALETTE_CATALOG

    lines = [
        "\nPALETTE: pick ONE color identity from the catalog that fits the "
        "deck's industry and audience, and set palette_recommendation to it. "
        "This sets the deck's primary/accent/chart colors ON TOP of the "
        "theme. Choose deliberately — a fintech deck wants finance_dark or "
        "b2b_navy, a consumer brand wants agency_pink or commerce_green, a "
        "data report wants analytics_amber or saas_blue.",
        "Palette catalog (name — mood):",
    ]
    lines += [
        f"- {p.name} — {p.mood}" for p in PALETTE_CATALOG.values()
    ]
    return "\n".join(lines) + "\n"


def _build_brand_guidance(
    theme_tokens: Optional[dict[str, Any]],
) -> str:
    """Return a BRAND STYLE block so the planner matches copy to the brand."""
    if not isinstance(theme_tokens, dict) or not theme_tokens:
        return ""
    primary = theme_tokens.get("primary")
    palette = theme_tokens.get("chart_palette")
    fonts = theme_tokens.get("fonts") or {}
    heading_font = fonts.get("heading") if isinstance(fonts, dict) else None
    body_font = fonts.get("body") if isinstance(fonts, dict) else None

    bits = ["\nBRAND STYLE: the deck renders in this customer's brand colors "
            "and fonts. Match the copy tone and emphasis to it."]
    if primary:
        bits.append(f"- Primary color: {primary}")
    if isinstance(palette, list) and palette:
        bits.append("- Chart series palette: " + ", ".join(
            str(c) for c in palette[:4]
        ))
    if heading_font or body_font:
        bits.append(f"- Fonts: {heading_font or body_font or ''}"
                    + (f" / {body_font}" if body_font and heading_font else ""))
    return "\n".join(bits) + "\n"


def _build_audience_guidance(
    personalization: Optional[dict[str, Any]],
) -> str:
    """Return an AUDIENCE & CONTEXT block so copy fits the actual audience."""
    if not isinstance(personalization, dict) or not personalization:
        return ""
    lines = ["\nAUDIENCE & CONTEXT: this deck is for the following audience — "
             "tailor the tone, depth, and emphasis accordingly. Ground the "
             "narrative in this context rather than generic business advice."]
    role = personalization.get("role_text")
    if role:
        lines.append(f"- Audience/role: {role}")
    profile = personalization.get("profile_text")
    if profile:
        lines.append(f"- User preferences: {profile}")
    brand_name = personalization.get("brand_name")
    if brand_name:
        lines.append(f"- Company/brand: {brand_name}")
    memory = personalization.get("memory_text")
    if memory:
        lines.append(f"- About this user/project: {memory}")
    return "\n".join(lines) + "\n"


async def _llm_deck_plan(
    user_intent: str,
    profile_summary: str,
    chart_hints: list[dict[str, Any]],
    row_count: int,
    theme_name: str = "zhanlu-blue",
    theme_mood: str = "",
    *,
    theme_tokens: Optional[dict[str, Any]] = None,
    personalization: Optional[dict[str, Any]] = None,
    skill_structure: str = "",
) -> Optional[DeckPlan]:
    """Make the single bounded LLM call and coerce the result into a DeckPlan.

    Returns ``None`` on any failure / timeout so the caller can fall back.
    """
    from app.services.llm_service import call_llm

    prompt = _build_planner_prompt(
        user_intent, profile_summary, chart_hints, row_count,
        theme_name=theme_name, theme_mood=theme_mood,
        theme_tokens=theme_tokens, personalization=personalization,
        skill_structure=skill_structure,
    )
    try:
        result = await asyncio.wait_for(
            call_llm(
                prompt=prompt,
                temperature=0.3,
                response_json_schema=_PLAN_SCHEMA,
                task_type="deck_planning",
            ),
            timeout=_PLANNER_TIMEOUT_S,
        )
    except asyncio.TimeoutError:
        logger.warning("deck_planner: LLM call timed out after %ss", _PLANNER_TIMEOUT_S)
        return None
    except Exception as e:  # noqa: BLE001 — fall back gracefully on any LLM error
        logger.warning("deck_planner: LLM call failed: %s", e)
        return None

    data = result.get("data") if isinstance(result, dict) else None
    if not isinstance(data, dict):
        raw = result.get("response") if isinstance(result, dict) else None
        if isinstance(raw, str):
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                data = None
    if not isinstance(data, dict):
        logger.warning("deck_planner: LLM returned non-dict data; falling back")
        return None

    return _coerce_plan(data)


def _coerce_plan(data: dict[str, Any]) -> Optional[DeckPlan]:
    """Coerce (and sanitize) the LLM dict into a valid DeckPlan."""
    try:
        plan = DeckPlan.model_validate(data)
    except Exception as e:  # noqa: BLE001
        logger.warning("deck_planner: DeckPlan validation failed: %s", e)
        return None

    if not plan.slides:
        return None

    # Sanitize layouts: drop invalid entries, map common aliases.
    cleaned: list[SlidePlan] = []
    for slide in plan.slides:
        layout = _normalize_layout(slide.layout)
        if layout is None:
            continue
        slide.layout = layout
        cleaned.append(slide)

    # Guarantee a cover as the first slide and closing as the last.
    if not cleaned or cleaned[0].layout != "cover":
        cleaned.insert(0, SlidePlan(layout="cover", title=plan.title or "Overview"))
    if cleaned[-1].layout != "closing":
        cleaned.append(SlidePlan(layout="closing", title="Thank you"))

    plan.slides = cleaned

    # Drop empty / filler-only insights slides (no real takeaway content).
    plan = _drop_empty_insights_slides(plan)

    return plan


# Filler bullet the fallback planner used to inject when no insights existed.
_FILLER_INSIGHT = "see the accompanying data for full detail."


def _is_empty_insights_slide(slide: SlidePlan) -> bool:
    """An insights/findings slide with no real takeaway must be dropped.

    Covers: no bullets, empty bullets, or only the legacy filler stub.
    """
    if slide.layout not in ("insights_bullets", "findings_cards"):
        return False
    bullets = [str(b).strip() for b in (slide.bullets or []) if str(b).strip()]
    if not bullets:
        return True
    non_filler = [b for b in bullets if b.lower() != _FILLER_INSIGHT]
    return not non_filler


def _drop_empty_insights_slides(plan: DeckPlan) -> DeckPlan:
    """Post-process (planner layer, not renderer): remove empty insights slides.

    Applies to both LLM and fallback plans so the rendered deck never shows a
    blank "Summary"/"Key Findings" slide whose only content is a filler stub.
    Never drops the cover or closing.
    """
    kept: list[SlidePlan] = []
    for slide in plan.slides:
        if slide.layout in ("cover", "closing"):
            kept.append(slide)
            continue
        if _is_empty_insights_slide(slide):
            logger.info(
                "deck_planner: dropping empty insights slide '%s'", slide.title
            )
            continue
        kept.append(slide)
    plan.slides = kept
    return plan


def _normalize_layout(layout: str) -> Optional[str]:
    l = (layout or "").strip().lower().replace("-", "_").replace(" ", "_")
    aliases = {
        "title": "cover",
        "title_slide": "cover",
        "kpis": "kpi_grid",
        "kpi": "kpi_grid",
        "metrics": "kpi_grid",
        "chart": "chart_full",
        "chart_and_bullets": "chart_with_bullets",
        "bullets": "insights_bullets",
        "findings": "findings_cards",
        "table": "data_table",
        "divider": "section_divider",
        "section": "section_divider",
        "end": "closing",
        "thank_you": "closing",
    }
    l = aliases.get(l, l)
    return l if l in _VALID_LAYOUTS else None


def _fallback_plan(
    user_intent: str,
    profile: dict[str, dict[str, Any]],
    rows: list[dict[str, Any]],
    profile_name: str = "data_report",
) -> DeckPlan:
    """Deterministic minimal plan used when the LLM fails or is disabled.

    When ``DECK_PROFILES_ENABLED`` is on, ``profile_name`` selects a
    profile-specific structure so the same data renders differently for an
    executive brief vs. a pitch vs. a periodic review.  When off (default),
    this is the historical ``data_report`` behavior (unchanged).
    """
    from app.services.artifacts.deck_profiles import get_profile

    prof = get_profile(profile_name)
    chart_hints = suggest_charts(profile)
    kpis = _profile_kpis(profile, rows)
    hint = chart_hints[0] if chart_hints else None

    # Cap the chart to the profile's preferred type when one is requested.
    preferred = prof.preferred_chart_types
    if hint and preferred and hint["chart_type"] not in preferred:
        # Best-effort: keep the hint but mark preference via headline mood.
        pass

    title = _derive_title(user_intent, prof)

    slides: list[SlidePlan] = [
        SlidePlan(layout="cover", title=title, narrative_role="hook"),
    ]

    if prof.name == "executive_brief":
        if kpis:
            slides.append(SlidePlan(layout="kpi_grid", title="Key Metrics",
                                    kpi_specs=kpis, narrative_role="context"))
        if hint:
            slides.append(SlidePlan(
                layout="chart_with_bullets", title=hint["title"],
                bullets=_hint_bullets(hint),
                chart_spec=ChartSpecInSlide(
                    chart_type=hint["chart_type"], x_key=hint["x_key"],
                    y_keys=hint["y_keys"], title=hint["title"]),
                chart_rows=rows, narrative_role="evidence"))
        slides.append(SlidePlan(layout="closing", title="Recommendation",
                                narrative_role="closing"))
        return _finalize_fallback(title, prof, slides)

    if prof.name == "pitch_narrative":
        slides.append(SlidePlan(layout="section_divider",
                                title="The Opportunity", narrative_role="hook"))
        if kpis:
            slides.append(SlidePlan(layout="findings_cards", title="The Problem",
                                    bullets=_problem_bullets(kpis, hint),
                                    narrative_role="context"))
        if hint:
            slides.append(SlidePlan(
                layout="chart_with_bullets", title=hint["title"],
                bullets=_hint_bullets(hint),
                chart_spec=ChartSpecInSlide(
                    chart_type=hint["chart_type"], x_key=hint["x_key"],
                    y_keys=hint["y_keys"], title=hint["title"]),
                chart_rows=rows, narrative_role="evidence"))
        slides.append(SlidePlan(layout="recommendations",
                                title="What We Recommend", narrative_role="ask"))
        slides.append(SlidePlan(layout="closing", title="Let's Build It",
                                narrative_role="closing"))
        return _finalize_fallback(title, prof, slides)

    if prof.name == "periodic_review":
        if kpis:
            slides.append(SlidePlan(layout="kpi_grid", title="This Period",
                                    kpi_specs=kpis, narrative_role="context"))
        if hint:
            slides.append(SlidePlan(
                layout="chart_full", title=hint["title"],
                chart_spec=ChartSpecInSlide(
                    chart_type=hint["chart_type"], x_key=hint["x_key"],
                    y_keys=hint["y_keys"], title=hint["title"]),
                chart_rows=rows, narrative_role="evidence"))
        slides.append(SlidePlan(layout="insights_bullets",
                                title="What Changed", narrative_role="context"))
        slides.append(SlidePlan(layout="closing", title="Next Period",
                                narrative_role="closing"))
        return _finalize_fallback(title, prof, slides)

    # ---- data_report (default, historical behavior) -----------------------
    if kpis:
        slides.append(SlidePlan(layout="kpi_grid", title="Key Metrics",
                                kpi_specs=kpis, narrative_role="context"))
    if hint:
        slides.append(SlidePlan(
            layout="chart_full", title=hint["title"],
            chart_spec=ChartSpecInSlide(
                chart_type=hint["chart_type"], x_key=hint["x_key"],
                y_keys=hint["y_keys"], title=hint["title"]),
            chart_rows=rows, narrative_role="evidence"))
    elif rows:
        slides.append(SlidePlan(layout="data_table", title="Data Sample",
                                narrative_role="evidence"))
    if len(rows) > 15:
        slides.append(SlidePlan(layout="data_table", title="Top Data Rows",
                                narrative_role="evidence"))
    slides.append(SlidePlan(layout="closing", title="Thank you",
                            narrative_role="closing"))
    return _finalize_fallback(title, prof, slides)


def _derive_title(user_intent: str, prof) -> str:
    intent = (user_intent or "").strip()
    if intent:
        # Use the user's intent as the deck title (trimmed).
        return intent[:60].strip().rstrip(".") or "Data Overview"
    return "Data Overview"


def _hint_bullets(hint: dict) -> list[str]:
    return [f"{hint.get('title', 'Trend')} across {hint.get('x_key', 'categories')}."]


def _problem_bullets(kpis, hint) -> list[str]:
    if kpis:
        return [f"{k.label} sits at {k.value}." for k in kpis[:3]]
    return ["Current state needs attention."]


def _finalize_fallback(title: str, prof, slides: list[SlidePlan]) -> DeckPlan:
    # Enforce the profile's slide-count ceiling.
    lo, hi = prof.slide_count_range
    if len(slides) > hi:
        slides = slides[:hi]
    plan = DeckPlan(
        title=title,
        deck_type=prof.name,
        headline_style=prof.headline_style,
        slides=slides,
    )
    return plan


def _profile_kpis(
    profile: dict[str, dict[str, Any]], rows: list[dict[str, Any]]
) -> list[KPISpecInSlide]:
    """Derive up to 4 KPI tiles from numeric columns (value = latest row)."""
    numeric = [c for c, m in profile.items() if m["type"] == "numeric"]
    if not rows or not numeric:
        return []
    latest = rows[-1] if isinstance(rows[-1], dict) else {}
    kpis: list[KPISpecInSlide] = []
    for col in numeric[:4]:
        val = latest.get(col)
        if val is None:
            continue
        kpis.append(KPISpecInSlide(label=col, value=str(val)))
    return kpis


# Topic-label titles that should be rewritten into assertions by the planner.
_TOPIC_LABELS = {
    "key findings", "findings", "insights", "summary", "overview", "analysis",
    "recommendations", "conclusion", "conclusions", "introduction", "background",
    "methodology", "data", "results", "next steps", "agenda", "highlights",
    "takeaways", "discussion", "appendix", "thank you", "thank you.",
}


def _is_topic_label(title: str) -> bool:
    """Cheap proxy: a title is a topic label if it is a short noun phrase that
    states NO takeaway (no verb / no assertion punctuation / matches a known
    label).  Assertion headlines are full sentences ('Revenue grew 8% QoQ')."""
    if not title:
        return True
    t = title.strip().strip(".:").lower()
    if t in _TOPIC_LABELS:
        return True
    # Assertion if it has a verb (ends in punctuation, contains a number+unit
    # trend word, or is > 4 words with a predicate).  Cheap heuristic:
    if any(p in title for p in [".", "!", "?"]) and len(title.split()) >= 4:
        return False
    words = title.split()
    if len(words) >= 5:
        # A sentence-length title with a trend word is an assertion.
        if any(w in title.lower() for w in
               ["grew", "rose", "fell", "dropped", "increased", "decreased",
                "up", "down", "by", "to", "%", "vs", "versus", "led", "drove",
                "driven", "hit", "reached", "top", "lowest", "highest"]):
            return False
    return len(words) <= 3 and not any(p in title for p in [".", "!", "?"])


def _run_coro(coro):
    """Run a coroutine to completion regardless of the current async context.

    ``asyncio.get_event_loop().run_until_complete`` raises
    "This event loop is already running" when called from inside a running
    loop (e.g. the polish pass invoked from ``render_pptx_from_plan``).  This
    helper falls back to a dedicated thread with its own loop so the rewrite
    always executes instead of silently failing.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)
    import concurrent.futures
    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
        return pool.submit(asyncio.run, coro).result()


def _enforce_assertion_headlines(plan: DeckPlan) -> DeckPlan:
    """Post-process: rewrite topic-label slide titles into assertion headlines.

    Runs after planning (LLM or fallback).  Topic labels ("Key Findings") are
    replaced with an assertion sentence.  When ``PPT_LLM_POLISH_ENABLED`` is on
    we attempt an LLM rewrite; otherwise we use the deterministic formatter
    ``"{label}: <original>`` so the slide still carries a takeaway hint.
    """
    for slide in plan.slides:
        if slide.layout in ("cover", "closing"):
            continue
        if not _is_topic_label(slide.title):
            slide.headline_style = "assertion"
            continue
        # Rewrite via LLM when polish is enabled; else deterministic formatter.
        label = slide.title.strip().strip(".:")
        if settings.PPT_LLM_POLISH_ENABLED:
            try:
                rewritten = _run_coro(
                    _llm_assertion_rewrite(slide.title, slide.bullets)
                )
                if rewritten and not _is_topic_label(rewritten):
                    slide.title = rewritten
                    slide.headline_style = "assertion"
                    continue
            except Exception as exc:  # pragma: no cover — best-effort
                logger.warning("deck_planner: assertion rewrite failed: %s", exc)
        # Deterministic fallback: keep the label as a prefix so the takeaway
        # is at least hinted; mark as topic; layout still renders fine.
        slide.headline_style = "topic"
    return plan


async def _llm_assertion_rewrite(title: str, bullets: list[str]) -> Optional[str]:
    """One bounded LLM call to turn a topic label into an assertion headline."""
    from app.services.llm_service import call_llm

    prompt = (
        "Rewrite this slide title into a single assertion sentence (<= 12 words) "
        "that states the takeaway, using the bullet hints if helpful. Return only "
        "the sentence.\n"
        f"TITLE: {title}\n"
        f"BULLETS: {bullets}\n"
    )
    try:
        result = await asyncio.wait_for(
            call_llm(prompt=prompt, temperature=0.2, task_type="deck_planning"),
            timeout=_PLANNER_TIMEOUT_S,
        )
        data = result.get("data") if isinstance(result, dict) else None
        text = (data or {}).get("response") if isinstance(data, dict) else None
        if isinstance(text, str) and text.strip():
            return text.strip().strip('"')
    except Exception as exc:  # noqa: BLE001 — best-effort only
        logger.warning("deck_planner: assertion LLM rewrite error: %s", exc)
    return None


async def build_deck_plan(
    user_intent: str,
    rows: list[dict[str, Any]],
    theme_recommendation: str | None = None,
    profile_name: str | None = None,
    *,
    theme_tokens: Optional[dict[str, Any]] = None,
    user_context: Optional[dict[str, Any]] = None,
    skill_name: Optional[str] = None,
) -> tuple[DeckPlan, dict[str, dict[str, Any]]]:
    """Entry point: profile the data, then plan the deck.

    ``theme_recommendation`` (optional) is the active theme name so the LLM
    planner can match copy tone / mood.  ``profile_name`` (optional) selects a
    deck profile (Phase 4); when ``DECK_PROFILES_ENABLED`` is on it is
    classified from ``user_intent`` if not explicitly provided.  Keyword-only
    ``theme_tokens`` carries the resolved brand hex tokens (from the workspace
    brand kit) so the planner matches the customer's palette, and
    ``user_context`` carries the audience/role/profile/memory block.  Returns
    ``(DeckPlan, profile)``.  Falls back to a deterministic plan when the LLM
    call is disabled, fails, or times out.
    """
    from app.services.artifacts.deck_profiles import classify_profile, get_profile

    profile = profile_rows(rows)
    profile_summary = summarize_profile(profile)
    chart_hints = suggest_charts(profile)
    row_count = len(rows)

    # ── General no-data short-circuit (2026-08-29) ──────────────────────
    # ANY request with NO grounded rows must still produce a professional
    # deck.  The deterministic builder structures a full consulting deck
    # (cover → exec framing → agenda → sections → findings/chart → recs →
    # Q&A) from the payload narrative — domain-agnostic, never hardcodes
    # facts.  Runs BEFORE the LLM planner so a data-less turn always ships a
    # real deliverable instead of a thin skeleton.  Real rows always take
    # the normal path.
    if row_count == 0:
        try:
            from app.services.artifacts.synthetic_deck import build_synthetic_deck_plan

            synth = build_synthetic_deck_plan(user_intent)
            if synth is not None:
                logger.info(
                    "deck_planner: synthetic no-data plan built "
                    "(slides=%d, title=%.60s)",
                    len(synth.slides), getattr(synth, "title", ""),
                )
                return _enforce_assertion_headlines(synth), profile
        except Exception as exc:  # noqa: BLE001 — never block the deck
            logger.warning("deck_planner: synthetic plan failed (non-fatal): %s", exc)

    # Resolve the theme name + mood for planner awareness (alias-tolerant).
    theme_name = "zhanlu-blue"
    theme_mood = ""
    if theme_recommendation:
        try:
            resolved = validate_theme_name(theme_recommendation)
            theme = load_theme(resolved)
            theme_name = resolved
            theme_mood = theme.best_for or ""
        except ValueError:
            logger.warning(
                "deck_planner: unknown theme_recommendation '%s'; using default",
                theme_recommendation,
            )
    # Brand tokens inform tone even for the deterministic fallback: surface the
    # primary/accent hexes in the mood so headline phrasing stays brand-aware.
    if isinstance(theme_tokens, dict) and theme_tokens:
        primary = theme_tokens.get("primary")
        accent = (theme_tokens.get("chart_palette") or [None])[0] or primary
        if primary:
            brand_hint = f"brand primary {primary}"
            if accent and accent != primary:
                brand_hint += f" / accent {accent}"
            theme_mood = (theme_mood + " · " if theme_mood else "") + brand_hint

    # Resolve the deck profile (Phase 4). Explicit wins; otherwise classify
    # from intent when the feature flag is enabled; else default data_report.
    resolved_profile_name = "data_report"
    if profile_name:
        resolved_profile_name = profile_name
    elif settings.DECK_PROFILES_ENABLED:
        resolved_profile_name = classify_profile(user_intent).name
    prof = get_profile(resolved_profile_name)
    profile_summary_text = (
        f"Deck profile: {prof.name} — {prof.description} "
        f"Target {prof.slide_count_range[0]}-{prof.slide_count_range[1]} slides, "
        f"headline tone '{prof.headline_style}', "
        f"prefer charts {list(prof.preferred_chart_types)}."
        + (" Avoid raw data tables." if prof.forbid_tables else "")
    )

    if not settings.PPT_DECK_PLANNER_ENABLED:
        plan = _fallback_plan(user_intent, profile, rows, profile_name=resolved_profile_name)
        return _enforce_assertion_headlines(plan), profile

    # Skill structure steer (2026-08-31): when a deck skill was loaded
    # (create_artifact skill=...), inject its preferred narrative framing +
    # archetype mix into the planner prompt so the SKILL shapes the deck
    # structure, not just the colors (closes the "different skill, same
    # structure" gap).  Non-fatal: unknown skills yield empty steer.
    skill_structure = ""
    if skill_name:
        try:
            from app.services.artifacts.skill_deck_profiles import skill_structure_steer

            skill_structure = skill_structure_steer(skill_name)
        except Exception as _steer_err:  # noqa: BLE001 — never block the deck
            logger.warning("deck_planner: skill structure steer skipped: %s", _steer_err)

    plan = await _llm_deck_plan(
        user_intent, profile_summary_text, chart_hints, row_count,
        theme_name=theme_name, theme_mood=theme_mood,
        theme_tokens=theme_tokens, personalization=user_context,
        skill_structure=skill_structure,
    )
    if plan is None:
        plan = _fallback_plan(user_intent, profile, rows, profile_name=resolved_profile_name)
        return _enforce_assertion_headlines(plan), profile

    return _enforce_assertion_headlines(plan), profile


# ---------------------------------------------------------------------------
# DeckPlan → ReportCardPayload mapping (for the structured renderer)
# ---------------------------------------------------------------------------


def deck_plan_to_report_card(
    plan: DeckPlan,
    rows: list[dict[str, Any]],
    profile: dict[str, dict[str, Any]],
) -> ReportCardPayload:
    """Map a DeckPlan onto ReportCardPayload so the structured renderer works.

    The structured renderer consumes ``ReportCardPayload``.  We translate
    the planner's narrative slides back into the report-card shape:
    - first KPI-grid slide → ``kpis``
    - first chart slide → ``chart`` (with ``data`` pulled from ``rows``)
    - insight bullets → ``insights`` / ``key_findings``
    - recommendations slide → ``recommendations``
    - methodology slide → ``methodology``
    """
    kpis: list[KPISpec] = []
    chart: Optional[ChartSpec] = None
    insights: list[InsightSpec] = []
    findings: list[InsightSpec] = []
    recommendations: list[InsightSpec] = []
    methodology = plan.methodology

    for slide in plan.slides:
        if slide.kpi_specs and not kpis:
            kpis = [
                KPISpec(
                    label=k.label, value=k.value, delta=k.delta, caption=k.caption
                )
                for k in slide.kpi_specs
            ]

        if slide.chart_spec and chart is None:
            cs = slide.chart_spec
            chart = ChartSpec(
                type=cs.chart_type,
                title=cs.title,
                x_key=cs.x_key,
                y_keys=cs.y_keys,
                data=_chart_data(rows, cs.x_key, cs.y_keys),
            )

        if slide.bullets:
            if slide.layout == "recommendations":
                recommendations.extend(InsightSpec(text=b) for b in slide.bullets)
            elif slide.layout in ("insights_bullets", "findings_cards"):
                insights.extend(InsightSpec(text=b) for b in slide.bullets)
            elif slide.layout == "chart_with_bullets":
                findings.extend(InsightSpec(text=b) for b in slide.bullets)

        if slide.layout == "methodology" and not methodology:
            methodology = " ".join(slide.bullets) or slide.subtitle

    return ReportCardPayload(
        title=plan.title,
        summary=plan.summary,
        kpis=kpis,
        chart=chart,
        insights=insights,
        key_findings=findings,
        recommendations=recommendations,
        methodology=methodology,
    )


def _chart_data(
    rows: list[dict[str, Any]], x_key: str, y_keys: list[str]
) -> list[dict[str, Any]]:
    """Project ``rows`` down to the chart's x/y columns for the renderer."""
    if not rows:
        return []
    out: list[dict[str, Any]] = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        point: dict[str, Any] = {}
        if x_key:
            point[x_key] = row.get(x_key)
        for yk in y_keys:
            point[yk] = row.get(yk)
        if point:
            out.append(point)
    return out
