"""PHASE 1 layout engine — single source of truth for deck slide layout.

This module owns every shape and textbox placed on a PowerPoint slide
generated by the Zhanlu agent. Both the in-process renderer
(``app/services/artifacts/exporters/pptx_export.py``) and the sandbox
renderer (``app/services/sandbox/sandbox_runner.py``) delegate here, so
chat-driven and exporter-driven decks share the same look.

DESIGN GOALS (echoing the spec):

* Varied layout per slide — 12 layout types: cover, agenda, kpi_grid,
  chart_full, chart_with_bullets, findings_cards, insights_bullets,
  recommendations, data_table, methodology, section_divider, closing.
* Assertion-style headlines — each slide's title is rewritten via
  ``_assertify_headline()`` unless the planner already supplied a
  sentence-form title (≥4 words OR ends with punctuation).
* Body budgets — at most 5 bullets, ~12 words / bullet, body ≥14 pt.
* Branded charts — ``charts.branded_charts.style_chart``.
* Top-8 + top-3-highlight data table — see ``_layout_data_table``.
* Subtle slide numbers — see ``add_slide_number``. No "Generated by...".

USAGE:

    from app.services.artifacts.layout_engine import render
    pptx_bytes = render(plan, rows, ctx)

Where ``plan`` is a ``synexia.contracts.DeckPlan`` instance (or a
plain dict with the same shape), ``rows`` is the underlying data and
``ctx`` is a dict with ``theme_tokens`` and ``style_recipe``.
"""

from __future__ import annotations

import io
import logging
import re
import threading
from pathlib import Path
from typing import Any, Iterable, Optional

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE

# chart helpers — sibling-first (sandbox), fallback to in-process dotted path.
# Matches the dual-context pattern at _apply_chart_theme / _render_chart
# below; the sandbox runner vendors `_chart_helpers.py` alongside this
# module under /input/skill/, so the sibling import resolves there.
try:
    from _chart_helpers import cap_chart_categories
except Exception:
    from app.services.artifacts.exporters._chart_helpers import cap_chart_categories


logger = logging.getLogger(__name__)


# ----------------------------------------------------------------------------
# Typography scale
# ----------------------------------------------------------------------------

TITLE_PT = 32       # main slide headlines (assertion form)
SUBTITLE_PT = 18    # subtitles, KPI deltas, secondary info
BODY_PT = 16        # body bullets, table cells
CAPTION_PT = 12     # KPI labels, axis hints
FOOTER_PT = 10      # slide numbers + source footers (10pt caption floor)

# Layout constants (16:9 13.333" × 7.5"; 0.6" margins all around)
SLIDE_W_IN = 13.333
SLIDE_H_IN = 7.5
MARGIN_IN = 0.6

# Try to load the brand template if it's been built. Failure to find it
# is non-fatal: the layout engine falls back to a fresh Presentation.
DEFAULT_TEMPLATE_PATH = (
    Path(__file__).resolve().parent / "templates" / "zhanlu_default.pptx"
)
DARK_TEMPLATE_PATH = (
    Path(__file__).resolve().parent / "templates" / "zhanlu_dark.pptx"
)


# ----------------------------------------------------------------------------
# Theme helpers (lightweight wrapper around a hex color dict)
# ----------------------------------------------------------------------------


def _hex(theme: dict, key: str, default: str) -> str:
    val = (theme or {}).get(key) or default
    return val.lstrip("#")


def _rgb(theme: dict, key: str, default: str) -> RGBColor:
    return RGBColor.from_string(_hex(theme, key, default))


def _brand_palette(theme: dict) -> list[RGBColor]:
    return [
        _rgb(theme, "primary",        "#2563EB"),
        _rgb(theme, "finding_accent", "#7C3AED"),
        _rgb(theme, "warn_accent",    "#F59E0B"),
        _rgb(theme, "delta_up",       "#059669"),
        _rgb(theme, "delta_down",     "#DC2626"),
        _rgb(theme, "muted",          "#64748B"),
    ]


# ----------------------------------------------------------------------------
# Typography / font resolution
# ----------------------------------------------------------------------------
#
# The PPTX renderer must respect the resolved brand theme's typeface instead
# of the PowerPoint default ("Calibri").  ``DeckTheme`` already carries
# ``font_heading`` / ``font_body`` / ``font_cjk`` (defaults: Inter /
# Microsoft YaHei), but the layout builders below used to hardcode
# "Calibri", which is what made decks read as unstyled Office templates.
#
# Fonts are resolved once per render and stashed on a thread-local so that
# concurrent renders (the exporter runs via a thread-pool coroutine runner)
# cannot clobber each other's typeface.

_CJK_RE = re.compile(
    r"[\u2e80-\u9fff\u3000-\u303f\uf900-\ufaff\uff00-\uffef]"
)

_T = threading.local()

_DEFAULT_FONTS = {
    "heading": "Inter",
    "body": "Inter",
    "cjk": "Microsoft YaHei",
}


def _resolve_fonts(theme: dict) -> dict:
    """Build the {heading, body, cjk} font map from a theme token dict."""
    theme = theme or {}
    return {
        "heading": theme.get("font_heading") or _DEFAULT_FONTS["heading"],
        "body": theme.get("font_body") or _DEFAULT_FONTS["body"],
        "cjk": theme.get("font_cjk") or _DEFAULT_FONTS["cjk"],
    }


def _font_for(text: str, role: str = "body") -> str:
    """Pick the correct font for a run.

    East-Asian runs always use the CJK typeface (Inter has no CJK glyphs,
    so without this PowerPoint silently falls back to SimSun/DengXian,
    which looks unprofessional in a Chinese deck).  Latin runs use the
    heading or body face depending on ``role``.
    """
    fonts = getattr(_T, "fonts", None) or _DEFAULT_FONTS
    if text and _CJK_RE.search(text):
        return fonts["cjk"]
    return fonts["heading"] if role == "heading" else fonts["body"]


# ----------------------------------------------------------------------------
# Headline enforcement — assertion vs topic label
# ----------------------------------------------------------------------------


def _assertify_headline(title: str, layout: str) -> str:
    """Rewrite a topic-label headline as an assertion if needed.

    Heuristic: a "topic label" is ≤3 words and does not end with
    punctuation. Topic-label slides get a `{layout}:` prefix added so
    the slide still reads cleanly even if the planner didn't rewrite
    the title itself.

    Real assertion rewriting (LLM-based) is wired in PHASE 1B via
    ``copy_polish.polish_deck``; this lightweight version keeps the
    visual diff deterministic without an LLM call.
    """
    title = (title or "").strip()
    if not title:
        return title
    # The cover and closing slides aren't required to be assertions.
    if layout in {"cover", "closing"}:
        return title
    nwords = len(title.split())
    ends_punct = title.endswith((".", "?", "!", ":"))
    if nwords >= 4 or ends_punct:
        return title
    # Topic label — prefix with the layout name as a label tag.
    label = layout.replace("_", " ").title()
    return f"{label}: {title}"


# ----------------------------------------------------------------------------
# Data enrichment — project payload rows into chart/data-table slides
# ----------------------------------------------------------------------------

# Cap chart categories so big datasets (200+ rows) stay readable.
_MAX_CHART_POINTS = 24
# Cap table columns so wide datasets (10+ cols) fit the slide.
_MAX_TABLE_COLS = 8


def _enrich_slide_data(plan_dict: dict, rows: list[dict]) -> dict:
    """Materialize chart_rows / table_rows from the payload at build time.

    The planner's ``chart_spec`` carries column keys (x_key / y_keys), not
    the data itself.  Slides that already carry explicit rows (e.g. from the
    sandbox path) are left untouched.
    """
    if not rows:
        return plan_dict
    for sp in plan_dict.get("slides", []):
        layout = sp.get("layout")
        if layout in ("chart_full", "chart_with_bullets"):
            cs = sp.get("chart_spec") or {}
            x_key = cs.get("x_key") or "label"
            y_keys = cs.get("y_keys") or ["value"]
            if not sp.get("chart_rows") and x_key and y_keys:
                sp["chart_rows"] = _project_chart_rows(rows, x_key, y_keys)
        elif layout == "data_table":
            if not sp.get("table_cols") and rows:
                sp["table_cols"] = _project_table_cols(rows)
            if not sp.get("table_rows"):
                sp["table_rows"] = rows
    return plan_dict


def _project_chart_rows(
    rows: list[dict], x_key: str, y_keys: list[str],
) -> list[dict]:
    """Project raw rows down to ``{x_key, *y_keys}`` dicts, capped at
    ``_MAX_CHART_POINTS`` (evenly sampled so big datasets stay readable)."""
    projected = [
        {k: (r.get(k) if isinstance(r, dict) else None) for k in [x_key, *y_keys]}
        for r in rows
        if isinstance(r, dict)
    ]
    n = len(projected)
    if n <= _MAX_CHART_POINTS:
        return projected
    step = n / _MAX_CHART_POINTS
    return [projected[int(i * step)] for i in range(_MAX_CHART_POINTS)]


def _project_table_cols(rows: list[dict]) -> list[str]:
    """Pick up to ``_MAX_TABLE_COLS`` column names from the first row,
    skipping a ``metadata`` key if present."""
    first = next((r for r in rows if isinstance(r, dict) and r), {})
    cols = [k for k in first.keys() if k != "metadata"]
    return cols[:_MAX_TABLE_COLS]


# ----------------------------------------------------------------------------
# Public entry — render a DeckPlan to .pptx bytes
# ----------------------------------------------------------------------------


def render(plan, rows: list[dict], ctx: Optional[dict] = None) -> bytes:
    """Render a DeckPlan to .pptx bytes.

    Args:
        plan: ``DeckPlan`` (Pydantic) or dict with the same shape.
            Expected keys: ``title``, ``slides`` (list of SlidePlan-like
            dicts), ``theme_recommendation``.
        rows: Raw data rows (used by ``data_table`` layout).
        ctx: Optional context dict with at least ``theme_tokens`` and
            ``style_recipe``. Defaults are zhanlu-blue / sharp.

    Returns:
        .pptx bytes.
    """
    if hasattr(plan, "model_dump"):
        plan_dict = plan.model_dump()
    else:
        plan_dict = dict(plan or {})

    # Phase-1 contract: the planner emits column keys (chart_spec.x_key /
    # y_keys) instead of materialized rows.  Project the payload rows into
    # each chart/data-table slide at build time so the deck renders even
    # when the plan never filled chart_rows / table_rows.
    plan_dict = _enrich_slide_data(plan_dict, rows)

    ctx = ctx or {}
    theme = ctx.get("theme_tokens") or {}
    style_recipe = (ctx.get("style_recipe") or "sharp").lower()
    # Provenance: the source label (data source name) cited in the footer of
    # every content slide.  Accepts both ``source_label`` (orchestrator/
    # sandbox convention) and ``source`` (ExportContext field) spellings.
    source_label = (ctx.get("source_label") or ctx.get("source") or "").strip()

    # Resolve the typeface for this render pass (thread-local) so every
    # text run below uses the brand theme's font instead of Calibri.
    _T.fonts = _resolve_fonts(theme)

    prs = apply_master(theme, style_recipe=style_recipe)

    layout_builders = {
        "cover": _layout_cover,
        "agenda": _layout_agenda,
        "kpi_grid": _layout_kpi_grid,
        "chart_full": _layout_chart_full,
        "chart_with_bullets": _layout_chart_with_bullets,
        "findings_cards": _layout_findings_cards,
        "insights_bullets": _layout_insights_bullets,
        "recommendations": _layout_recommendations,
        "data_table": _layout_data_table,
        "methodology": _layout_methodology,
        "section_divider": _layout_section_divider,
        "closing": _layout_closing,
        # New archetypes (2026-08-29)
        "timeline": _layout_timeline,
        "roadmap": _layout_roadmap,
        "comparison": _layout_comparison,
        "swot": _layout_swot,
        "quote": _layout_quote,
        "process_flow": _layout_process_flow,
    }

    total_slides = len(plan_dict.get("slides", [])) or 1
    for idx, slide_plan in enumerate(plan_dict.get("slides", []), start=1):
        layout = slide_plan.get("layout") or "insights_bullets"
        builder = layout_builders.get(layout, _layout_insights_bullets)
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        # Always set the slide background to the brand bg.
        bg = _rgb(theme, "slide_bg", "#FFFFFF")
        fill = slide.background.fill
        fill.solid()
        fill.fore_color.rgb = bg
        builder(slide, slide_plan, theme, idx, total_slides)
        # Subtle slide number on every slide except the cover.
        if layout != "cover":
            add_slide_number(slide, idx, total_slides, theme)
            # Provenance footer — cite the data source on content slides.
            add_source_footer(slide, source_label, theme)
        # Speaker notes (professional decks carry a presenter script).
        notes_text = slide_plan.get("notes") or ""
        if notes_text:
            try:
                slide.notes_slide.notes_text_frame.text = notes_text
            except Exception:
                pass

    # Fade transitions (settings-gated, best-effort XML addition).
    # Guarded: the sandbox runner vendors layout_engine flat WITHOUT the
    # app package, so the dotted import must never crash a deck there.
    try:
        from app.services.artifacts.pptx_motion import add_fade_transitions
        add_fade_transitions(prs)
    except Exception:
        pass

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def apply_master(theme: dict, style_recipe: str = "sharp") -> Presentation:
    """Return a Presentation with the brand template loaded if available.

    Resolution order (Phase 3 — one master template per vendored theme):
      1. ``templates/theme_<name>.pptx``  (per-theme, built by
         ``scripts/build_pptx_templates.py``)
      2. ``templates/zhanlu_dark.pptx``   (legacy, when "dark" in name)
      3. ``templates/zhanlu_default.pptx`` (legacy, light themes)
      4. a fresh 16:9 deck (always safe)

    Falls back gracefully — the per-slide ``slide.background.fill`` is what
    actually paints the brand bg, so the deck is brand-correct regardless.
    """
    theme_name = (theme or {}).get("name", "zhanlu-blue")
    per_theme = (
        Path(__file__).resolve().parent / "templates" / f"theme_{theme_name}.pptx"
    )
    legacy = DARK_TEMPLATE_PATH if "dark" in theme_name else DEFAULT_TEMPLATE_PATH
    candidates = [p for p in (per_theme, legacy) if p.exists()]
    for candidate in candidates:
        try:
            return Presentation(str(candidate))
        except Exception:
            logger.warning("apply_master: failed to load %s, trying next",
                           candidate, exc_info=True)
    prs = Presentation()
    prs.slide_width = Inches(SLIDE_W_IN)
    prs.slide_height = Inches(SLIDE_H_IN)
    return prs


# ----------------------------------------------------------------------------
# Slide-number helper
# ----------------------------------------------------------------------------


def add_slide_number(slide, idx: int, total: int, theme: dict) -> None:
    """Add a subtle slide-number caption (bottom-right, FOOTER_PT)."""
    tb = slide.shapes.add_textbox(
        Inches(SLIDE_W_IN - 1.6), Inches(SLIDE_H_IN - 0.45),
        Inches(1.0), Inches(0.3),
    )
    tf = tb.text_frame
    tf.margin_left = Inches(0)
    tf.margin_right = Inches(0)
    tf.margin_top = Inches(0)
    tf.margin_bottom = Inches(0)
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.RIGHT
    run = p.add_run()
    run.text = f"{idx} / {total}"
    run.font.size = Pt(FOOTER_PT)
    run.font.color.rgb = _rgb(theme, "muted", "#64748B")


def add_source_footer(slide, source_label: str, theme: dict) -> None:
    """Add a subtle source-citation caption (bottom-left, FOOTER_PT).

    Provenance footer — ``Source: <label>`` — so every content slide can be
    traced back to the data that produced it.  Mirrors the slide-number
    placement (same baseline, muted color) and is a no-op when no source
    label is supplied.  The ``source_citation`` audit rule enforces that
    non-cover slides carry this footer.
    """
    label = (source_label or "").strip()
    if not label:
        return
    _add_textbox(
        slide, MARGIN_IN, SLIDE_H_IN - 0.45, 10.0, 0.3,
        f"Source: {label}", FOOTER_PT,
        color=_rgb(theme, "muted", "#64748B"),
    )


# ----------------------------------------------------------------------------
# Low-level primitives
# ----------------------------------------------------------------------------


def _add_textbox(
    slide, left_in: float, top_in: float, width_in: float, height_in: float,
    text: str, size: int, bold: bool = False, color: RGBColor | None = None,
    align: PP_ALIGN = PP_ALIGN.LEFT,
):
    tb = slide.shapes.add_textbox(
        Inches(left_in), Inches(top_in), Inches(width_in), Inches(height_in),
    )
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0)
    tf.margin_right = Inches(0)
    tf.margin_top = Inches(0)
    tf.margin_bottom = Inches(0)
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text or ""
    run.font.name = _font_for(text, "heading" if bold else "body")
    run.font.size = Pt(size)
    run.font.bold = bold
    if color is not None:
        run.font.color.rgb = color
    return tb


def _add_rect(
    slide, left_in: float, top_in: float, width_in: float, height_in: float,
    fill: RGBColor | None = None, border: RGBColor | None = None,
    rounded: bool = False, radius_in: float = 0.08,
):
    shape_type = MSO_SHAPE.ROUNDED_RECTANGLE if rounded else MSO_SHAPE.RECTANGLE
    shape = slide.shapes.add_shape(
        shape_type, Inches(left_in), Inches(top_in),
        Inches(width_in), Inches(height_in),
    )
    shape.shadow.inherit = False
    if fill is not None:
        shape.fill.solid()
        shape.fill.fore_color.rgb = fill
    else:
        shape.fill.background()
    if border is not None:
        shape.line.color.rgb = border
        shape.line.width = Pt(0.75)
    else:
        shape.line.fill.background()
    shape.text_frame.text = ""
    if rounded:
        try:
            shorter = min(width_in, height_in) or 1.0
            shape.adjustments[0] = max(0.0, min(0.5, radius_in / shorter))
        except Exception:
            pass
    return shape


def _section_title(slide, text: str, theme: dict) -> None:
    _add_textbox(
        slide, MARGIN_IN, 0.5, SLIDE_W_IN - 2 * MARGIN_IN, 0.8,
        text, TITLE_PT, bold=True,
        color=_rgb(theme, "text", "#0F172A"),
    )
    _add_rect(
        slide, MARGIN_IN, 1.25, 1.2, 0.05,
        fill=_rgb(theme, "primary", "#2563EB"),
    )


def _coerce(v) -> float:
    if v is None or isinstance(v, bool):
        return 0
    if isinstance(v, (int, float)):
        return float(v)
    try:
        return float(str(v).replace(",", "").strip())
    except (ValueError, TypeError):
        return 0


def _cap_table_rows(
    rows: list[dict[str, Any]],
    cols: list[str],
    sort_col: Optional[str],
    cap: int = 8,
) -> list[dict[str, Any]]:
    """Cap a table at ``cap`` rows, folding the remainder into one "Other" row.

    Mirrors :func:`cap_chart_categories` so tables and native charts obey the
    same 8 + Other rule.  Rows are ranked by ``sort_col`` when present (largest
    first); otherwise the first 8 rows are kept in order.  Numeric columns are
    summed into the "Other" row; the first (label) column becomes ``"Other"``.
    """
    if not rows or len(rows) <= cap:
        return list(rows)
    if sort_col:
        ordered = sorted(rows, key=lambda r: _coerce(r.get(sort_col)), reverse=True)
    else:
        ordered = list(rows)
    kept = [dict(r) for r in ordered[:cap]]
    rest = ordered[cap:]
    if not rest:
        return kept
    other: dict[str, Any] = {}
    for ci, c in enumerate(cols):
        if ci == 0:
            other[c] = "Other"
        else:
            other[c] = sum(_coerce(r.get(c)) for r in rest)
    kept.append(other)
    return kept


# ----------------------------------------------------------------------------
# Layout builders
# ----------------------------------------------------------------------------


def _layout_cover(slide, sp, theme, idx, total) -> None:
    """Cover slide: brand bar + title + period + subtitle + CEO meta line."""
    title = _assertify_headline(sp.get("title", ""), "cover")
    subtitle = sp.get("subtitle", "")
    period = sp.get("period", "")
    _add_rect(slide, 0, 0, SLIDE_W_IN, 0.25, fill=_rgb(theme, "primary", "#2563EB"))
    _add_textbox(
        slide, MARGIN_IN, 2.0, SLIDE_W_IN - 2 * MARGIN_IN, 1.6,
        title, TITLE_PT + 8, bold=True,
        color=_rgb(theme, "text", "#0F172A"),
    )
    # Report period line (e.g. "July 2026 · vs June 2026").
    meta_y = 3.7
    if period:
        _add_textbox(
            slide, MARGIN_IN, 3.55, SLIDE_W_IN - 2 * MARGIN_IN, 0.5,
            period, SUBTITLE_PT + 2, bold=True,
            color=_rgb(theme, "primary", "#2563EB"),
        )
        meta_y = 4.15
    if subtitle:
        _add_textbox(
            slide, MARGIN_IN, meta_y, SLIDE_W_IN - 2 * MARGIN_IN, 0.6,
            subtitle, SUBTITLE_PT, color=_rgb(theme, "muted", "#64748B"),
        )
    # CEO review line — the primary audience for this deck.
    _add_textbox(
        slide, MARGIN_IN, SLIDE_H_IN - 0.9, SLIDE_W_IN - 2 * MARGIN_IN, 0.5,
        "Prepared for CEO Review", CAPTION_PT, bold=True,
        color=_rgb(theme, "muted", "#64748B"),
    )


def _layout_agenda(slide, sp, theme, idx, total) -> None:
    _section_title(slide, _assertify_headline(sp.get("title", "Agenda"), "agenda"), theme)
    items = sp.get("bullets", [])
    top = 1.6
    for i, item in enumerate(items[:10], start=1):
        _add_textbox(
            slide, MARGIN_IN + 0.2, top, SLIDE_W_IN - 2 * MARGIN_IN, 0.6,
            f"{i}.  {item}", SUBTITLE_PT, color=_rgb(theme, "text", "#0F172A"),
        )
        top += 0.55


def _layout_kpi_grid(slide, sp, theme, idx, total) -> None:
    _section_title(slide, _assertify_headline(sp.get("title", "Key Metrics"), "kpi_grid"), theme)
    kpis = sp.get("kpi_specs", [])
    n = len(kpis) or 1
    if n == 1:
        cols, rows = 1, 1
    elif n <= 3:
        cols, rows = n, 1
    else:
        cols, rows = 3, 2
    available_w = SLIDE_W_IN - 2 * MARGIN_IN
    available_h = SLIDE_H_IN - 1.8 - 0.4
    # Reserve space at the bottom for risk/opportunity callouts.
    callouts = sp.get("callouts", []) or []
    callout_reserve = 0.0
    if callouts:
        callout_reserve = 1.15
        available_h -= callout_reserve
    cell_w = (available_w - (cols - 1) * 0.2) / cols
    cell_h = min(2.2, (available_h - (rows - 1) * 0.2) / rows)
    for i, k in enumerate(kpis[: cols * rows]):
        c = i % cols
        r = i // cols
        left = MARGIN_IN + c * (cell_w + 0.2)
        top = 1.6 + r * (cell_h + 0.2)
        box = _add_rect(
            slide, left, top, cell_w, cell_h,
            fill=_rgb(theme, "kpi_bg", "#F1F5F9"),
            border=_rgb(theme, "border", "#E2E8F0"),
            rounded=True, radius_in=0.08,
        )
        tf = box.text_frame
        tf.word_wrap = True
        tf.margin_left = Inches(0.2)
        tf.margin_right = Inches(0.2)
        tf.margin_top = Inches(0.15)
        # Label
        p = tf.paragraphs[0]
        p.text = (k.get("label", "") or "").upper()
        p.runs[0].font.size = Pt(CAPTION_PT)
        p.runs[0].font.bold = True
        p.runs[0].font.color.rgb = _rgb(theme, "muted", "#64748B")
        # Value
        p2 = tf.add_paragraph()
        run = p2.add_run()
        run.text = str(k.get("value", "—"))
        run.font.size = Pt(TITLE_PT)
        run.font.bold = True
        run.font.color.rgb = _rgb(theme, "text", "#0F172A")
        # Delta (color-coded)
        delta = k.get("delta")
        if delta:
            run2 = p2.add_run()
            run2.text = f"   {delta}"
            d = delta.strip()
            if d.startswith(("+", "▲")):
                run2.font.color.rgb = _rgb(theme, "delta_up", "#059669")
            elif d.startswith(("-", "▼")):
                run2.font.color.rgb = _rgb(theme, "delta_down", "#DC2626")
            else:
                run2.font.color.rgb = _rgb(theme, "muted", "#64748B")
            run2.font.size = Pt(SUBTITLE_PT)
            run2.font.bold = True
        if k.get("caption"):
            p3 = tf.add_paragraph()
            p3.text = k["caption"]
            p3.runs[0].font.size = Pt(CAPTION_PT)
            p3.runs[0].font.color.rgb = _rgb(theme, "muted", "#64748B")

    # ── Risk / opportunity callouts (CEO executive-summary style) ─────────
    # Rendered as colored boxes at the bottom of the KPI slide.
    if callouts:
        n_call = len(callouts)
        call_w = (available_w - (n_call - 1) * 0.25) / n_call
        call_top = SLIDE_H_IN - callout_reserve + 0.15
        for i, call in enumerate(callouts[:3]):
            ctype = (call.get("type") or "info").lower()
            ctext = call.get("text", "")
            if ctype == "risk":
                fill = _rgb(theme, "risk_bg", "#FEF2F2")
                border = _rgb(theme, "risk", "#DC2626")
                label = "⚠ RISK"
            elif ctype == "opportunity":
                fill = _rgb(theme, "opp_bg", "#ECFDF5")
                border = _rgb(theme, "opportunity", "#059669")
                label = "▲ OPPORTUNITY"
            else:
                fill = _rgb(theme, "kpi_bg", "#F1F5F9")
                border = _rgb(theme, "border", "#E2E8F0")
                label = "NOTE"
            left = MARGIN_IN + i * (call_w + 0.25)
            box = _add_rect(
                slide, left, call_top, call_w, callout_reserve - 0.3,
                fill=fill, border=border, rounded=True, radius_in=0.08,
            )
            tf = box.text_frame
            tf.word_wrap = True
            tf.margin_left = Inches(0.15)
            tf.margin_right = Inches(0.15)
            tf.margin_top = Inches(0.08)
            p0 = tf.paragraphs[0]
            p0.text = label
            p0.runs[0].font.size = Pt(CAPTION_PT)
            p0.runs[0].font.bold = True
            p0.runs[0].font.color.rgb = border
            p1 = tf.add_paragraph()
            p1.text = ctext
            p1.runs[0].font.size = Pt(BODY_PT - 2)
            p1.runs[0].font.color.rgb = _rgb(theme, "text", "#0F172A")


def _chart_type_const(chart_kind: str):
    """Map a planner chart_type string to a python-pptx XL_CHART_TYPE.

    Supports the extended set: line, pie/donut, bar/column,
    grouped_bar/grouped_column (COLUMN_CLUSTERED / BAR_CLUSTERED), and
    stacked_bar/stacked_column (COLUMN_STACKED / BAR_STACKED).
    """
    kind = (chart_kind or "bar").lower()
    if kind in ("line", "area"):
        return XL_CHART_TYPE.LINE
    if kind in ("pie", "donut"):
        return XL_CHART_TYPE.PIE
    if kind in ("grouped_bar", "bar_clustered", "combo"):
        return XL_CHART_TYPE.BAR_CLUSTERED
    if kind in ("stacked_bar", "bar_stacked"):
        return XL_CHART_TYPE.BAR_STACKED
    if kind in ("stacked_column", "column_stacked"):
        return XL_CHART_TYPE.COLUMN_STACKED
    if kind in ("grouped_column", "column_clustered"):
        return XL_CHART_TYPE.COLUMN_CLUSTERED
    # Default: clustered column (best fit for categorical comparisons).
    return XL_CHART_TYPE.COLUMN_CLUSTERED


def _layout_chart_full(slide, sp, theme, idx, total) -> None:
    _section_title(slide, _assertify_headline(sp.get("title", "Chart"), "chart_full"), theme)
    chart_spec = sp.get("chart_spec") or {}
    rows = sp.get("chart_rows") or []
    if not rows:
        _add_textbox(slide, MARGIN_IN, 3.0, 8, 1.0,
                     "No chart data available.", BODY_PT,
                     color=_rgb(theme, "muted", "#64748B"))
        return
    cd = CategoryChartData()
    x_key = chart_spec.get("x_key", "label")
    y_keys = chart_spec.get("y_keys") or ["value"]
    # Shared data-prep cap: top-8 categories by value + "Other" bucket.
    rows = cap_chart_categories(rows, x_key, y_keys)
    cd.categories = [str(r.get(x_key, "")) for r in rows]
    for y in y_keys:
        cd.add_series(str(y), [_coerce(r.get(y)) for r in rows])
    chart_kind = (chart_spec.get("chart_type") or "bar").lower()
    chart_type_const = _chart_type_const(chart_kind)
    cs = slide.shapes.add_chart(
        chart_type_const, Inches(MARGIN_IN), Inches(1.7),
        Inches(SLIDE_W_IN - 2 * MARGIN_IN), Inches(5.3), cd,
    )
    cs.chart.has_title = False
    # Defer import to avoid a circular dep at module load.  Prefer the
    # vendored flat module (sandbox container has no ``app`` package); fall
    # back to the in-process dotted path.
    try:
        from branded_charts import style_chart
    except Exception:
        from app.services.artifacts.charts.branded_charts import style_chart
    style_chart(cs.chart, theme, chart_kind)


def _layout_chart_with_bullets(slide, sp, theme, idx, total) -> None:
    """Two-column chart-left + bullets-right layout."""
    _section_title(slide, _assertify_headline(sp.get("title", "Chart + Insight"), "chart_with_bullets"), theme)
    chart_spec = sp.get("chart_spec") or {}
    rows = sp.get("chart_rows") or []
    bullets = sp.get("bullets", [])
    # Left: chart (5" wide)
    if rows:
        cd = CategoryChartData()
        x_key = chart_spec.get("x_key", "label")
        y_keys = chart_spec.get("y_keys") or ["value"]
        # Shared data-prep cap: top-8 categories by value + "Other" bucket.
        rows = cap_chart_categories(rows, x_key, y_keys)
        cd.categories = [str(r.get(x_key, "")) for r in rows]
        for y in y_keys:
            cd.add_series(str(y), [_coerce(r.get(y)) for r in rows])
        chart_kind = (chart_spec.get("chart_type") or "bar").lower()
        chart_type_const = _chart_type_const(chart_kind)
        cs = slide.shapes.add_chart(
            chart_type_const, Inches(MARGIN_IN), Inches(1.7),
            Inches(6.8), Inches(5.0), cd,
        )
        cs.chart.has_title = False
        try:
            from branded_charts import style_chart
        except Exception:
            from app.services.artifacts.charts.branded_charts import style_chart
        style_chart(cs.chart, theme, chart_kind)
    # Right: bullets (5.2" wide)
    right_left = MARGIN_IN + 7.1
    right_w = SLIDE_W_IN - right_left - MARGIN_IN
    top = 1.8
    for i, b in enumerate(bullets[:5], start=1):
        _add_textbox(
            slide, right_left, top, right_w, 0.7,
            f"•  {b}", BODY_PT,
            color=_rgb(theme, "text", "#0F172A"),
        )
        top += 0.85


def _layout_findings_cards(slide, sp, theme, idx, total) -> None:
    """Two-column findings cards — number + text."""
    _section_title(slide, _assertify_headline(sp.get("title", "Findings"), "findings_cards"), theme)
    bullets = sp.get("bullets", [])
    if not bullets:
        return
    n = len(bullets[:6])
    cols = 2
    rows = (n + cols - 1) // cols
    available_w = SLIDE_W_IN - 2 * MARGIN_IN
    available_h = SLIDE_H_IN - 1.8 - 0.4
    cell_w = (available_w - (cols - 1) * 0.2) / cols
    cell_h = min(2.3, (available_h - (rows - 1) * 0.2) / rows)
    for i, b in enumerate(bullets[:6], start=1):
        c = (i - 1) % cols
        r = (i - 1) // cols
        left = MARGIN_IN + c * (cell_w + 0.2)
        top = 1.6 + r * (cell_h + 0.2)
        # Number badge
        _add_textbox(
            slide, left, top, 0.6, 0.7,
            f"{i}", TITLE_PT, bold=True,
            color=_rgb(theme, "primary", "#2563EB"),
        )
        # Card text
        _add_textbox(
            slide, left + 0.7, top + 0.05, cell_w - 0.7, cell_h - 0.1,
            b, BODY_PT,
            color=_rgb(theme, "text", "#0F172A"),
        )


def _layout_insights_bullets(slide, sp, theme, idx, total) -> None:
    _section_title(slide, _assertify_headline(sp.get("title", "Insights"), "insights_bullets"), theme)
    bullets = sp.get("bullets", [])
    top = 1.6
    for b in bullets[:5]:
        _add_textbox(
            slide, MARGIN_IN, top, SLIDE_W_IN - 2 * MARGIN_IN, 0.7,
            f"•  {b}", BODY_PT,
            color=_rgb(theme, "text", "#0F172A"),
        )
        top += 0.95


def _layout_recommendations(slide, sp, theme, idx, total) -> None:
    _section_title(slide, _assertify_headline(sp.get("title", "Recommendations"), "recommendations"), theme)
    box = _add_rect(
        slide, MARGIN_IN, 1.6, SLIDE_W_IN - 2 * MARGIN_IN, SLIDE_H_IN - 2.4,
        fill=_rgb(theme, "rec_bg", "#EFF6FF"),
        border=_rgb(theme, "primary", "#2563EB"),
        rounded=True, radius_in=0.08,
    )
    tf = box.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.3)
    tf.margin_right = Inches(0.3)
    bullets = sp.get("bullets", [])
    for i, rec in enumerate(bullets[:5], start=1):
        p = tf.paragraphs[0] if i == 1 else tf.add_paragraph()
        p.space_after = Pt(10)
        run = p.add_run()
        run.text = f"{i}.  {rec}"
        run.font.name = _font_for(rec, "body")
        run.font.size = Pt(BODY_PT)
        run.font.color.rgb = _rgb(theme, "text", "#0F172A")


def _layout_data_table(slide, sp, theme, idx, total) -> None:
    _section_title(slide, _assertify_headline(sp.get("title", "Data"), "data_table"), theme)
    rows = sp.get("table_rows") or []
    cols = sp.get("table_cols") or []
    if not rows or not cols:
        _add_textbox(slide, MARGIN_IN, 3.0, 8, 1.0,
                     "No table data available.", BODY_PT,
                     color=_rgb(theme, "muted", "#64748B"))
        return

    # --- Determine the "most-relevant numeric column" so we can sort ---
    def _numeric_score(c: str) -> float:
        score = 0.0
        for r in rows:
            v = r.get(c)
            if v is None:
                continue
            try:
                float(str(v).replace(",", ""))
                score += 1
            except (ValueError, TypeError):
                pass
        return score

    sort_col = None
    sort_desc = True
    for c in cols:
        if _numeric_score(c) >= max(2, 0.5 * len(rows)):
            sort_col = c
            break

    if sort_col:
        rows = sorted(
            rows,
            key=lambda r: _coerce(r.get(sort_col)),
            reverse=sort_desc,
        )

    # PHASE 1 acceptance + Fix #3: cap at the SAME top-8 limit the charts use,
    # folding the remainder into an "Other" row so the table and the native
    # chart always show the identical category rule (8 + Other).
    top_rows = _cap_table_rows(rows, cols, sort_col, 8)

    # --- Table shape ---
    n_data_rows = len(top_rows)
    n_rows = n_data_rows + 1
    n_cols = len(cols)
    table_w = SLIDE_W_IN - 2 * MARGIN_IN
    table_h = SLIDE_H_IN - 1.8 - 0.4
    table_shape = slide.shapes.add_table(
        n_rows, n_cols,
        Inches(MARGIN_IN), Inches(1.6),
        Inches(table_w), Inches(table_h),
    )
    table = table_shape.table
    # Set relative widths: first column slightly wider.
    if n_cols > 1:
        table.columns[0].width = Inches(table_w * 0.32)
        rest = table_w * 0.68 / (n_cols - 1)
        for cidx in range(1, n_cols):
            table.columns[cidx].width = Inches(rest)
    # Header row
    for ci, c in enumerate(cols):
        cell = table.cell(0, ci)
        cell.text = c
        for p in cell.text_frame.paragraphs:
            for r in p.runs:
                r.font.name = _font_for(r.text, "body")
                r.font.size = Pt(CAPTION_PT)
                r.font.bold = True
                r.font.color.rgb = _rgb(theme, "text", "#0F172A")
        cell.fill.solid()
        cell.fill.fore_color.rgb = _rgb(theme, "kpi_bg", "#F1F5F9")
    # Data rows with top-3 highlight
    for ri, row in enumerate(top_rows, start=1):
        for ci, c in enumerate(cols):
            v = row.get(c, "")
            sv = "" if v is None else str(v)
            if len(sv) > 60:
                sv = sv[:60] + "…"
            cell = table.cell(ri, ci)
            cell.text = sv
            for p in cell.text_frame.paragraphs:
                for r in p.runs:
                    r.font.name = _font_for(r.text, "body")
                    r.font.size = Pt(CAPTION_PT)
                    r.font.color.rgb = _rgb(theme, "text", "#0F172A")
            if ri <= 3:
                # Top-3 highlight — theme accent @ 12% alpha equivalent
                cell.fill.solid()
                cell.fill.fore_color.rgb = _rgb(theme, "finding_bg", "#F5F3FF")
            elif ri % 2 == 0:
                cell.fill.solid()
                cell.fill.fore_color.rgb = _rgb(theme, "band_bg", "#F8FAFC")


def _layout_methodology(slide, sp, theme, idx, total) -> None:
    _section_title(slide, _assertify_headline(sp.get("title", "Methodology"), "methodology"), theme)
    body = sp.get("notes") or sp.get("bullets", [""])[0] or ""
    _add_textbox(
        slide, MARGIN_IN, 1.6, SLIDE_W_IN - 2 * MARGIN_IN, 5.5,
        body, BODY_PT, color=_rgb(theme, "text", "#0F172A"),
    )


def _layout_section_divider(slide, sp, theme, idx, total) -> None:
    """Full-bleed brand color with a short assertion in the centre."""
    _add_rect(slide, 0, 0, SLIDE_W_IN, SLIDE_H_IN,
              fill=_rgb(theme, "primary", "#2563EB"))
    title = _assertify_headline(sp.get("title", ""), "section_divider")
    subtitle = sp.get("subtitle", "")
    _add_textbox(
        slide, MARGIN_IN, 2.8, SLIDE_W_IN - 2 * MARGIN_IN, 1.5,
        title, TITLE_PT + 4, bold=True,
        color=RGBColor.from_string("FFFFFF"),
    )
    if subtitle:
        _add_textbox(
            slide, MARGIN_IN, 4.4, SLIDE_W_IN - 2 * MARGIN_IN, 0.6,
            subtitle, SUBTITLE_PT, color=RGBColor.from_string("FFFFFF"),
        )


def _layout_closing(slide, sp, theme, idx, total) -> None:
    """Closing / Next Step — primary bar + title + body card."""
    _add_rect(slide, 0, 0, SLIDE_W_IN, 0.25,
              fill=_rgb(theme, "primary", "#2563EB"))
    title = _assertify_headline(sp.get("title", "Next Step"), "closing")
    _add_textbox(
        slide, MARGIN_IN, 1.2, SLIDE_W_IN - 2 * MARGIN_IN, 1.0,
        title, TITLE_PT + 8, bold=True,
        color=_rgb(theme, "text", "#0F172A"),
    )
    body = sp.get("notes") or sp.get("subtitle") or ""
    if body:
        box = _add_rect(
            slide, MARGIN_IN, 2.4, SLIDE_W_IN - 2 * MARGIN_IN, 3.6,
            fill=_rgb(theme, "rec_bg", "#EFF6FF"),
            border=_rgb(theme, "primary", "#2563EB"),
            rounded=True, radius_in=0.08,
        )
        tf = box.text_frame
        tf.word_wrap = True
        tf.margin_left = Inches(0.3)
        tf.margin_right = Inches(0.3)
        tf.margin_top = Inches(0.2)
        p = tf.paragraphs[0]
        run = p.add_run()
        run.text = "Next step: "
        run.font.size = Pt(SUBTITLE_PT + 2)
        run.font.bold = True
        run.font.color.rgb = _rgb(theme, "primary", "#2563EB")
        run2 = p.add_run()
        run2.text = body
        run2.font.size = Pt(SUBTITLE_PT + 2)
        run2.font.color.rgb = _rgb(theme, "text", "#0F172A")


# ----------------------------------------------------------------------------
# New archetypes (2026-08-29): timeline / roadmap / comparison / swot / quote / process_flow
# ----------------------------------------------------------------------------


def _layout_timeline(slide, sp, theme, idx, total) -> None:
    """Horizontal milestone timeline — dated dots across the slide."""
    _section_title(slide, _assertify_headline(sp.get("title", "Timeline"), "timeline"), theme)
    bullets = (sp.get("bullets") or [])[:6]
    n = max(len(bullets), 1)
    col_w = (SLIDE_W_IN - 2 * MARGIN_IN) / n
    accent = _rgb(theme, "accent", "#7C3AED")
    for i, b in enumerate(bullets):
        date, _, label = b.partition("|")
        date = date.strip()
        label = label.strip() or date
        cx = MARGIN_IN + col_w * i + col_w / 2
        # connector line
        if i < len(bullets) - 1:
            _add_rect(slide, cx + 0.15, 1.75, col_w - 0.3, 0.06,
                      fill=_rgb(theme, "muted", "#64748B"))
        # dot
        dot = slide.shapes.add_shape(
            MSO_SHAPE.OVAL, Inches(cx - 0.22), Inches(1.55), Inches(0.44), Inches(0.44)
        )
        dot.fill.solid()
        dot.fill.fore_color.rgb = accent
        dot.line.color.rgb = _rgb(theme, "slide_bg", "#FFFFFF")
        dot.line.width = Pt(3)
        _add_textbox(
            slide, cx - col_w / 2, 2.2, col_w, 0.5,
            date, SUBTITLE_PT, bold=True, color=accent, align=PP_ALIGN.CENTER,
        )
        _add_textbox(
            slide, cx - col_w / 2, 2.8, col_w, 1.4,
            label, BODY_PT - 2, color=_rgb(theme, "text", "#0F172A"),
            align=PP_ALIGN.CENTER,
        )


def _layout_roadmap(slide, sp, theme, idx, total) -> None:
    """Three-phase roadmap — Now / Next / Later columns."""
    _section_title(slide, _assertify_headline(sp.get("title", "Roadmap"), "roadmap"), theme)
    bullets = (sp.get("bullets") or [])[:9]
    buckets: dict[str, list[str]] = {"Now": [], "Next": [], "Later": []}
    for b in bullets:
        phase, _, item = b.partition("|")
        phase = phase.strip()
        item = item.strip() or phase
        key = phase if phase in buckets else "Later"
        buckets[key].append(item)
    colors = [_rgb(theme, "accent", "#7C3AED"), _rgb(theme, "primary", "#2563EB"), _rgb(theme, "muted", "#64748B")]
    col_w = (SLIDE_W_IN - 2 * MARGIN_IN - 0.8) / 3
    for i, phase in enumerate(["Now", "Next", "Later"]):
        left = MARGIN_IN + i * (col_w + 0.4)
        _add_rect(slide, left, 1.6, col_w, 5.2,
                  fill=_rgb(theme, "card_bg", "#FFFFFF"),
                  border=colors[i], rounded=True, radius_in=0.06)
        _add_rect(slide, left, 1.6, col_w, 0.14, fill=colors[i])
        _add_textbox(slide, left + 0.3, 1.9, col_w - 0.6, 0.6,
                     phase, SUBTITLE_PT + 4, bold=True, color=colors[i])
        y = 2.7
        for item in buckets[phase][:5]:
            _add_textbox(slide, left + 0.3, y, col_w - 0.6, 0.7,
                         item, BODY_PT - 2, color=_rgb(theme, "text", "#0F172A"))
            y += 0.85


def _layout_comparison(slide, sp, theme, idx, total) -> None:
    """Two-column comparison — A vs B rows."""
    _section_title(slide, _assertify_headline(sp.get("title", "Comparison"), "comparison"), theme)
    left_head = sp.get("subtitle") or "Option A"
    right_head = sp.get("notes") or "Option B"
    col_w = (SLIDE_W_IN - 2 * MARGIN_IN - 0.8) / 2
    accent = _rgb(theme, "accent", "#7C3AED")
    muted = _rgb(theme, "muted", "#64748B")
    _add_textbox(slide, MARGIN_IN, 1.5, col_w, 0.6, left_head, SUBTITLE_PT, bold=True, color=accent)
    _add_textbox(slide, MARGIN_IN + col_w + 0.8, 1.5, col_w, 0.6, right_head, SUBTITLE_PT, bold=True, color=muted)
    y = 2.3
    for b in (sp.get("bullets") or [])[:8]:
        if "||" in b:
            a, _, bb = b.partition("||")
        elif " vs " in b:
            a, _, bb = b.partition(" vs ")
        else:
            a, bb = b, "—"
        _add_textbox(slide, MARGIN_IN, y, col_w, 0.5, a.strip(), BODY_PT - 1,
                     color=_rgb(theme, "text", "#0F172A"))
        _add_textbox(slide, MARGIN_IN + col_w + 0.8, y, col_w, 0.5, bb.strip(), BODY_PT - 1,
                     color=muted)
        y += 0.62


def _layout_swot(slide, sp, theme, idx, total) -> None:
    """2x2 SWOT grid."""
    _section_title(slide, _assertify_headline(sp.get("title", "SWOT"), "swot"), theme)
    quad: dict[str, list[str]] = {"S": [], "W": [], "O": [], "T": []}
    for b in (sp.get("bullets") or [])[:16]:
        key = b[:1].upper()
        if key in quad:
            quad[key].append(b[1:].strip().lstrip("|").strip() or b)
        else:
            quad["S"].append(b)
    labels = [("S", "Strengths"), ("W", "Weaknesses"), ("O", "Opportunities"), ("T", "Threats")]
    colors = [
        _rgb(theme, "delta_up", "#059669"), _rgb(theme, "delta_down", "#DC2626"),
        _rgb(theme, "accent", "#7C3AED"), _rgb(theme, "warn_accent", "#F59E0B"),
    ]
    cell_w = (SLIDE_W_IN - 2 * MARGIN_IN - 0.6) / 2
    cell_h = 2.4
    for i, ((key, label), color) in enumerate(zip(labels, colors)):
        row, col = divmod(i, 2)
        left = MARGIN_IN + col * (cell_w + 0.6)
        top = 1.6 + row * (cell_h + 0.4)
        _add_rect(slide, left, top, cell_w, cell_h,
                  fill=_rgb(theme, "card_bg", "#FFFFFF"),
                  border=color, rounded=True, radius_in=0.06)
        _add_textbox(slide, left + 0.3, top + 0.15, cell_w - 0.6, 0.5,
                     label, SUBTITLE_PT, bold=True, color=color)
        y = top + 0.8
        for item in quad[key][:3]:
            _add_textbox(slide, left + 0.3, y, cell_w - 0.6, 0.5,
                         item, BODY_PT - 3, color=_rgb(theme, "text", "#0F172A"))
            y += 0.55


def _layout_quote(slide, sp, theme, idx, total) -> None:
    """Big pull quote — title = quote, subtitle = attribution."""
    quote = _assertify_headline(sp.get("title", ""), "quote")
    attribution = sp.get("subtitle", "")
    _add_rect(slide, 0, 0, SLIDE_W_IN, SLIDE_H_IN,
              fill=_rgb(theme, "slide_bg", "#FFFFFF"))
    _add_textbox(
        slide, MARGIN_IN + 1.0, 1.2, 1.2, 1.2,
        "“", TITLE_PT + 40, bold=True, color=_rgb(theme, "accent", "#7C3AED"),
        align=PP_ALIGN.CENTER,
    )
    _add_textbox(
        slide, MARGIN_IN + 0.5, 2.4, SLIDE_W_IN - 2 * MARGIN_IN - 1.0, 2.6,
        quote, TITLE_PT + 10, bold=True, color=_rgb(theme, "text", "#0F172A"),
        align=PP_ALIGN.CENTER,
    )
    if attribution:
        _add_textbox(
            slide, MARGIN_IN + 0.5, 5.4, SLIDE_W_IN - 2 * MARGIN_IN - 1.0, 0.6,
            f"— {attribution}", SUBTITLE_PT, color=_rgb(theme, "muted", "#64748B"),
            align=PP_ALIGN.CENTER,
        )


def _layout_process_flow(slide, sp, theme, idx, total) -> None:
    """Numbered chevron process flow — steps 1..N."""
    _section_title(slide, _assertify_headline(sp.get("title", "Process"), "process_flow"), theme)
    bullets = (sp.get("bullets") or [])[:6]
    n = max(len(bullets), 1)
    col_w = (SLIDE_W_IN - 2 * MARGIN_IN) / n
    accent = _rgb(theme, "accent", "#7C3AED")
    for i, b in enumerate(bullets):
        cx = MARGIN_IN + col_w * i + col_w / 2
        num = slide.shapes.add_shape(
            MSO_SHAPE.OVAL, Inches(cx - 0.6), Inches(1.7), Inches(1.2), Inches(1.2)
        )
        num.fill.solid()
        num.fill.fore_color.rgb = accent
        num.line.fill.background()
        tf = num.text_frame
        tf.margin_left = Inches(0)
        tf.margin_right = Inches(0)
        tf.margin_top = Inches(0.2)
        p = tf.paragraphs[0]
        p.alignment = PP_ALIGN.CENTER
        run = p.add_run()
        run.text = f"{i+1:02d}"
        run.font.size = Pt(SUBTITLE_PT + 2)
        run.font.bold = True
        run.font.color.rgb = RGBColor.from_string("FFFFFF")
        _add_textbox(slide, cx - col_w / 2, 3.1, col_w, 1.6,
                     b, BODY_PT - 2, color=_rgb(theme, "text", "#0F172A"),
                     align=PP_ALIGN.CENTER)


# ----------------------------------------------------------------------------
# File-system helper (also used by tests)
# ----------------------------------------------------------------------------


def render_to_pptx_path(plan, rows: list[dict], ctx: dict, path: str | Path) -> None:
    """Convenience wrapper that writes the rendered .pptx to ``path``."""
    Path(path).write_bytes(render(plan, rows, ctx))
