/**
 * Regression: Chat.jsx must deduplicate messages that share the same
 * logical content but have DIFFERENT ids because they were persisted
 * to two parallel stores (chat_messages table vs.
 * agent_conversations.messages JSON column).
 *
 * The bug
 * --------
 * 1. Conv-rehydration effect (mount-only, ``[]`` deps) called
 *    ``setMessages(conv.messages)``, populating state with entries
 *    whose ids were generated by the backend (``uuid.uuid4()`` in
 *    agents.py:4972, 5276).
 * 2. ``loadMessages`` later fetched ``chat_messages`` rows whose ids
 *    were generated by the frontend (``ChatMessage.create()`` in
 *    Chat.jsx:956, 1051).
 * 3. The id-based merge at Chat.jsx:850-866 preserved any ``prev``
 *    message whose id was NOT in the freshly fetched set, treating
 *    it as "in-flight, not committed yet." Because the two stores
 *    share NO id space, both copies were kept.
 * 4. Result: every message rendered TWICE after a hard refresh of a
 *    ``?conv=<id>`` URL.
 *
 * The fix
 * -------
 * A shared ``dedupeMessagesByFingerprint`` helper (./messageDedup.js)
 * collapses entries by ``(role, content[:4000])``. The fingerprint
 * intentionally does NOT include ``created_date`` — the two stores
 * use different timestamps for the same logical message (backend's
 * ``datetime.utcnow()`` vs the chat_messages row's DB default), so a
 * fingerprint including ``created_date`` would fail to match. First
 * occurrence wins. The helper is applied at BOTH the conv-rehydration
 * useEffect (Chat.jsx:413) and inside ``loadMessages``'s
 * ``setMessages`` updater.
 *
 * What the test pins
 * ------------------
 * - Chat.jsx imports ``dedupeMessagesByFingerprint`` from
 *   ``./messageDedup``.
 * - The conv-rehydration useEffect wraps ``conv.messages`` in
 *   ``dedupeMessagesByFingerprint`` BEFORE the ``setMessages`` call.
 * - The ``loadMessages`` setMessages updater calls
 *   ``dedupeMessagesByFingerprint`` on the merged list (not a hand-
 *   rolled inline Set loop, which would be brittle).
 * - The fingerprint does NOT include ``created_date`` (this is the
 *   specific invariant the previous fix got wrong — including
 *   ``created_date`` causes the cross-store copies to disagree and
 *   the dedup to no-op).
 *
 * Why source-text tests (not React Testing Library)?
 * --------------------------------------------------
 * Same pattern as the other Chat / ChatInput tests in this repo:
 * no DOM, no router, no mocks. The contract is the *code shape*;
 * a refactor that silently drops the dedup pass fails loudly.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const SOURCE = readFileSync(resolve(__dirname, './Chat.jsx'), 'utf8');

describe('Chat.jsx cross-store dedup wiring', () => {
  // Extract the body of loadMessages (async function loadMessages … setLoadStatus('loaded') }).
  const fnMatch = SOURCE.match(
    /async function loadMessages\([\s\S]*?setLoadStatus\('loaded'\);\s*\}/,
  );
  const fnBody = fnMatch ? fnMatch[0] : '';

  it('loadMessages function body is extractable from Chat.jsx', () => {
    expect(fnBody, 'loadMessages not found in Chat.jsx').not.toBe('');
  });

  it('Chat.jsx imports dedupeMessagesByFingerprint from ./messageDedup', () => {
    expect(
      SOURCE,
      'Chat.jsx must import the shared dedup helper',
    ).toMatch(/import\s*\{[^}]*\bdedupeMessagesByFingerprint\b[^}]*\}\s*from\s*['"]\.\/messageDedup['"]/);
  });

  it('conv-rehydration useEffect wraps conv.messages in dedupeMessagesByFingerprint', () => {
    // Pin the fix at the source of the second leak: the conv
    // rehydration point. The dedup runs inside the setMessages
    // functional updater (after the 2026-08-12 SESSION GUARD
    // refactor), so match that form. Without this wrap, the state
    // would be populated with cross-store duplicates and
    // loadMessages' later dedup could only collapse them relative to
    // the FRESH chat_messages fetch, not relative to the existing
    // conv.messages entries that share a fingerprint with the
    // fetched set.
    expect(
      SOURCE,
      'conv-rehydration must dedup before setMessages',
    ).toMatch(/setMessages\(\s*\(prev\)\s*=>\s*\{[\s\S]*?return\s+dedupeMessagesByFingerprint\(/);
  });

  it('loadMessages uses dedupeMessagesByFingerprint on the merged list', () => {
    // The helper call must be inside the setMessages updater so it
    // runs against the freshly-merged prev+fetched list. Searching
    // for the helper invocation anywhere in loadMessages catches
    // the "extracted to a separate function" refactor that would
    // still keep the behavior correct.
    expect(
      fnBody,
      'loadMessages must call dedupeMessagesByFingerprint on the merged list',
    ).toMatch(/dedupeMessagesByFingerprint\(/);
  });

  it('dedup pass runs AFTER the existing id-based merge (merged.sort)', () => {
    // The dedup must not touch the id-based merge logic — it is a
    // separate pass that only collapses cross-store copies.
    const mergeSortIdx = fnBody.indexOf('merged.sort');
    expect(mergeSortIdx, 'merged.sort not found in loadMessages').toBeGreaterThan(-1);

    // The dedup helper call must appear at a higher character
    // position than merged.sort so it runs after the merge.
    const dedupIdx = fnBody.indexOf('dedupeMessagesByFingerprint(');
    expect(dedupIdx, 'dedupeMessagesByFingerprint not found in loadMessages').toBeGreaterThan(-1);
    expect(dedupIdx, 'dedup must appear after merged.sort').toBeGreaterThan(mergeSortIdx);
  });

  it('fingerprint does NOT include created_date (cross-store timestamps differ)', () => {
    // This is the specific invariant the previous fix got wrong.
    // The two stores set DIFFERENT created_date values for the same
    // logical message: backend's ``datetime.utcnow().isoformat()``
    // (agents.py:4975 / 5331) vs the chat_messages row's DB default
    // (set on INSERT). Any fingerprint that includes created_date
    // will fail to match across the stores and the dedup will no-op.
    //
    // The fingerprint is defined in messageDedup.js (not Chat.jsx),
    // so we read that file here and assert the source-level shape.
    const helperSource = readFileSync(
      resolve(__dirname, './messageDedup.js'),
      'utf8',
    );
    // Extract the actual template literal that builds the fingerprint.
    // The helper uses ``const fp = `...`;`` — we capture the template
    // body to test exactly what is being fingerprinted, ignoring the
    // docstring (which deliberately mentions created_date to explain
    // WHY we don't use it).
    const fpMatch = helperSource.match(/const\s+fp\s*=\s*`([^`]*)`/);
    expect(fpMatch, 'fingerprint template literal not found in messageDedup.js').not.toBeNull();
    const fpBody = fpMatch ? fpMatch[1] : '';
    // The fingerprint must mention role and content (in some order).
    expect(fpBody, 'fingerprint must include role').toMatch(/role/);
    expect(fpBody, 'fingerprint must include content').toMatch(/content/);
    // The fingerprint must NOT include created_date or created_at —
    // these differ across the two stores and would cause the dedup
    // to no-op on cross-store copies.
    expect(
      fpBody,
      'fingerprint must NOT include created_date or created_at — they differ across stores',
    ).not.toMatch(/created_date|created_at/);
  });
});
