"""Pre-execution validation of Fusion 360 Python against a live-introspected
API manifest, plus "did you mean" enhancement of runtime errors.

Why: the CAD Agent writes raw Python against the ``adsk`` API, and an LLM will
occasionally hallucinate a class/member name (``adsk.core.Cylinder3D``,
``createThreadData``). Left unchecked, that name only surfaces as a runtime
``AttributeError`` AFTER Fusion has already partially built geometry, leaving a
broken feature in the timeline. This module catches those names BEFORE execution
and returns a precise, actionable correction instead.

Manifest: ``fusion360_api_manifest.json`` (same dir), generated by dumping
``dir()`` of ``adsk.core`` / ``adsk.fusion`` inside a live Fusion session:
    python client.py "$(cat introspect_manifest.py)"   # writes adsk_manifest.json
Regenerate it if the Fusion build is upgraded.
"""

from __future__ import annotations

import difflib
import json
import logging
import os
import re

logger = logging.getLogger(__name__)

_MANIFEST_PATH = os.path.join(os.path.dirname(__file__), "fusion360_api_manifest.json")

_manifest = None
_all_names = None  # union of top-level names + every class member (for did-you-mean)


def _load_manifest() -> dict:
    global _manifest
    if _manifest is None:
        try:
            with open(_MANIFEST_PATH, "r", encoding="utf-8") as f:
                _manifest = json.load(f)
        except Exception as e:  # noqa: BLE001
            logger.warning("Fusion360 API manifest not loaded (%s); validation disabled", e)
            _manifest = {}
    return _manifest


def _closest(name: str, candidates, limit: int = 4) -> str:
    matches = difflib.get_close_matches(name, list(candidates), n=limit, cutoff=0.6)
    return ", ".join(matches) if matches else "(no close match)"


def _all_known_names() -> set:
    global _all_names
    if _all_names is None:
        m = _load_manifest()
        names = set(m.get("core_names", [])) | set(m.get("fusion_names", []))
        for attrs in list(m.get("core_attrs", {}).values()) + list(m.get("fusion_attrs", {}).values()):
            names |= set(attrs)
        _all_names = names
    return _all_names


def validate_fusion360_code(code: str):
    """Return (ok: bool, error: str | None).

    ok=False means the code references an ``adsk.*`` name that is not in the
    live API manifest. The returned error names the offending symbol and the
    closest real matches. Fails OPEN (returns ok) if the manifest is missing,
    so validation can never block a request on a load error.
    """
    manifest = _load_manifest()
    if not manifest:
        return True, None

    core_names = set(manifest.get("core_names", []))
    fusion_names = set(manifest.get("fusion_names", []))
    core_attrs = manifest.get("core_attrs", {})
    fusion_attrs = manifest.get("fusion_attrs", {})

    # 1. Top-level names: adsk.core.X / adsk.fusion.X
    for m in re.finditer(r"adsk\.(core|fusion)\.(\w+)", code):
        mod, name = m.group(1), m.group(2)
        valid = core_names if mod == "core" else fusion_names
        if name not in valid:
            suggestion = _closest(name, valid)
            return False, (
                f"Invalid Fusion 360 API name: adsk.{mod}.{name} does not exist. "
                f"Did you mean: {suggestion}?"
            )

    # 2. Class members: adsk.core.Class.member / adsk.fusion.Class.member
    for m in re.finditer(r"adsk\.(core|fusion)\.(\w+)\.(\w+)", code):
        mod, cls, member = m.group(1), m.group(2), m.group(3)
        attrs = core_attrs if mod == "core" else fusion_attrs
        class_attrs = attrs.get(cls)
        if class_attrs is not None and member not in class_attrs:
            suggestion = _closest(member, class_attrs)
            return False, (
                f"Invalid Fusion 360 API member: adsk.{mod}.{cls}.{member} does not exist. "
                f"Did you mean: {suggestion}?"
            )

    return True, None


# Raw-adsk failure → granular-tool nudges (2026-08-28). deepseek burned whole
# turns retrying raw adsk for ops that have granular tools; the error hint must
# name the exact tool. Order matters: first match wins.
_GRANULAR_NUDGES = [
    ("ChamferFeatures", "raw adsk chamfer code hits ChamferFeatures API errors. Use the granular fusion360_edge_chamfer(body_index, distance_mm, face='top'|'bottom'|'front'|'back'|'left'|'right', edge='all'|'longest'|'shortest'|'front'|'back'|'left'|'right') instead — it targets ONE face's rim and never touches other bodies. (fusion360_chamfer takes EVERY straight edge of a body; do not use it for a single rim.)"),
    ("ExtrudeFeatureInput", "raw adsk start-extent code hits ExtrudeFeatureInput errors. Use the granular fusion360_extrude(sketch_index, distance_mm, operation='new'|'join'|'cut') instead — it builds the extent correctly."),
    ("FeatureExtentTypes", "raw adsk extent types are easy to get wrong. Use the granular fusion360_extrude(sketch_index, distance_mm, operation='new'|'join'|'cut') instead."),
    ("ThreadFeatures", "raw adsk thread code hits ThreadFeatures errors. Use the granular fusion360_thread(body_index, designation, is_internal) instead."),
    ("HoleFeatures", "raw adsk hole code hits HoleFeatures errors. Use the granular fusion360_hole(body_index, diameter_mm, cx_mm, cy_mm, cz_mm) instead."),
    ("Profiles", "sketch profile access failed (bad profile index). Call fusion360_info for the CURRENT sketch indices, then use the granular fusion360_extrude(sketch_index, distance_mm, ...) with a valid sketch index."),
]


def enhance_fusion360_error(err: str) -> str:
    """Append a 'did you mean' hint to runtime AttributeError tracebacks.

    Covers the cases static validation cannot (instance method calls like
    ``tf.createThreadData(...)``, where the receiver type is unknown until
    runtime). Returns the original string unchanged when no match applies.
    """
    if not err:
        return err
    # Granular-tool nudges (2026-08-28): raw adsk fails on operations that have
    # a granular tool — tell the model WHICH tool instead of leaving it to
    # re-attempt raw python (deepseek burned a whole turn this way).
    for needle, nudge in _GRANULAR_NUDGES:
        if needle in err:
            return err + "\n\n[HINT] " + nudge
    m = re.search(r"has no attribute ['\"]([\w]+)['\"]", err)
    if not m:
        # Stale-index errors (sketch/body collections changed between calls —
        # the classic "sketch index doesn't match the collection" failure).
        # The raw Fusion traceback ("RuntimeError: 3 : invalid argument index")
        # tells a weak local model nothing actionable; append the re-sync hint.
        if "invalid argument index" in err or "Sketches_item" in err or "BRepBodies_item" in err:
            return err + (
                "\n\n[HINT] A sketch/body index is out of range — the live Fusion "
                "scene has different indices than this call assumed (a prior "
                "clear/sketch-create changed the collection). Call fusion360_info "
                "to re-read the CURRENT sketch/body indices, then retry with a "
                "valid index. NEVER guess indices."
            )
        return err
    name = m.group(1)
    names = _all_known_names()
    if not names:
        return err
    suggestion = _closest(name, names)
    return err + f"\n\n[HINT] '{name}' is not in the Fusion 360 API. Did you mean: {suggestion}?"
