"""fusion360_io — geometry exchange + engineering drawing for the CAD Agent.

Three granular tools (all ``fusion360_*``, same pattern as the modeling tools):

- ``fusion360_export_geometry`` — export the live design to STEP/STL/OBJ/IGES/
  SAT/F3D via ``design.exportManager``. The file bytes are returned over the
  socket as base64 (printed by the adsk snippet), decoded here, saved to the
  platform upload dir, and surfaced as a download URL (UserFile row).
- ``fusion360_import_dxf`` — import a 2D DXF (base64) as a sketch onto a
  construction plane via ``app.importManager``, returning the new sketch_index
  so the existing extrude/revolve tools can turn it into a 3D solid.
- ``fusion360_make_drawing`` — generate a dimensioned 2D engineering drawing
  (DXF) from a structured spec the agent builds from the dimensions it already
  knows (its tool-call history). Rendered in the backend with ezdxf — no Fusion
  call needed.

Verified live against Fusion 360 (2026-08-19):
- STEP export: ``design.exportManager.createSTEPExportOptions(path)`` + ``execute``.
- DXF import: ``app.importManager.createDXF2DImportOptions(path, plane)`` +
  ``importToTarget(opts, root)`` (requires the ``planarEntity`` arg — the
  construction plane to place the sketch on).
"""

from __future__ import annotations

import base64
import os
import uuid
from datetime import datetime

from app.config import settings
from app.models.user_file import UserFile
from app.services.tool_registry import registry
from app.services.tool_handlers.fusion360_tool import _call

_PLANES = {
    "xy": "root.xYConstructionPlane",
    "xz": "root.xZConstructionPlane",
    "yz": "root.yZConstructionPlane",
}

# format -> (ExportManager factory suffix, file extension, needs_target)
# Mesh formats (STL/OBJ) tessellate a body/component and need the `root` target as
# the FIRST arg; B-rep formats (STEP/IGES/SAT/F3D) export the design, filename only.
_EXPORT_FORMATS = {
    "step": ("STEP", "step", False),
    "stl": ("STL", "stl", True),
    "obj": ("OBJ", "obj", True),
    "iges": ("IGES", "igs", False),
    "sat": ("SAT", "sat", False),
    "f3d": ("FusionArchive", "f3d", False),
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _save_file(db, user_id: str | None, name: str, file_type: str, data: bytes) -> tuple[str, int]:
    """Persist generated bytes to the upload dir and return (file_url, size)."""
    ext = os.path.splitext(name)[1] or ("." + file_type)
    unique = uuid.uuid4().hex + ext
    path = settings.upload_path / unique
    path.write_bytes(data)
    url = f"/api/uploads/{unique}"
    try:
        f = UserFile(
            name=name,
            file_type=file_type,
            size=len(data),
            file_url=url,
            source="ai_generated",
            created_by_id=user_id,
        )
        db.add(f)
        db.commit()
    except Exception:  # noqa: BLE001 — file is already on disk; don't fail the tool
        db.rollback()
    return url, len(data)


def _bad(msg: str) -> dict:
    return {"success": False, "error": msg, "retryable": True}


def _get_agent_app(db):
    """Resolve the calling AgentApp via TOOL_CONTEXT_VAR (same pattern as
    fusion_endpoint resolution) so per-agent state never leaks across users."""
    try:
        from app.services.agent_tools import TOOL_CONTEXT_VAR
        app_id = (TOOL_CONTEXT_VAR.get() or {}).get("agent_app_id")
        if app_id and db is not None:
            from app.models.agent_app import AgentApp
            return db.get(AgentApp, app_id)
    except Exception:  # noqa: BLE001
        return None
    return None


def _get_project(db) -> str | None:
    app = _get_agent_app(db)
    if app is not None and isinstance(getattr(app, "tool_config", None), dict):
        return app.tool_config.get("fusion_project")
    return None


def _set_project(db, name: str) -> None:
    app = _get_agent_app(db)
    if app is None:
        return
    tc = dict(app.tool_config or {})
    tc["fusion_project"] = name
    app.tool_config = tc
    try:
        db.add(app)
        db.commit()
    except Exception:  # noqa: BLE001
        db.rollback()


# ---------------------------------------------------------------------------
# 1. fusion360_export_geometry
# ---------------------------------------------------------------------------
def _fusion360_export_geometry(args: dict, db, user_id: str | None) -> dict:
    fmt = (args.get("format") or "step").lower()
    if fmt not in _EXPORT_FORMATS:
        return _bad(f"format must be one of {sorted(_EXPORT_FORMATS)}")
    cls, ext, needs_target = _EXPORT_FORMATS[fmt]
    create_line = (
        f"opts = exp.create{cls}ExportOptions(root, path)\n"
        if needs_target
        else f"opts = exp.create{cls}ExportOptions(path)\n"
    )

    code = (
        "import tempfile, os, base64\n"
        "exp = design.exportManager\n"
        f"path = os.path.join(tempfile.gettempdir(), 'zhanlu_export.{ext}')\n"
        + create_line
        + "ok = exp.execute(opts)\n"
        "if not ok:\n"
        "    print('ZB64_ERR: export returned False')\n"
        "else:\n"
        "    with open(path, 'rb') as f:\n"
        "        print('ZB64:' + base64.b64encode(f.read()).decode())\n"
        "    try: os.remove(path)\n"
        "    except Exception: pass\n"
    )
    r = _call(code, db)
    if r.get("error"):
        return {"success": False, "error": r["error"], "retryable": True}
    out = r.get("result", "") or ""
    if "ZB64_ERR" in out:
        return {"success": False, "error": "Fusion export failed (exportManager returned False).", "retryable": True}
    marker = "ZB64:"
    if marker not in out:
        return {"success": False, "error": "No export data returned from Fusion.", "retryable": True}
    b64 = out.split(marker, 1)[1].strip()
    try:
        data = base64.b64decode(b64)
    except Exception as e:  # noqa: BLE001
        return {"success": False, "error": f"Failed to decode export data: {e}", "retryable": True}

    name = (args.get("name") or f"model.{ext}").strip()
    url, size = _save_file(db, user_id, name, ext, data)
    return {
        "success": True,
        "file_url": url,
        "filename": name,
        "format": fmt,
        "size_bytes": size,
    }


# ---------------------------------------------------------------------------
# 1b. fusion360_save / fusion360_project — named project state
# ---------------------------------------------------------------------------
def _fusion360_save(args: dict, db, user_id: str | None) -> dict:
    """Save the live design as a named .f3d AND remember it as the current project."""
    name = (args.get("name") or "untitled").strip()
    if not name.lower().endswith(".f3d"):
        name += ".f3d"
    r = _fusion360_export_geometry({"format": "f3d", "name": name}, db, user_id)
    if not r.get("success"):
        return r
    _set_project(db, name)
    r["project"] = name
    return r


def _fusion360_project(args: dict, db, user_id: str | None) -> dict:
    """Report the current Fusion project (the filename last saved via fusion360_save)."""
    p = _get_project(db)
    if p:
        return {"success": True, "project": p}
    return {"success": True, "project": None, "note": "No project saved yet."}


# ---------------------------------------------------------------------------
# 2. fusion360_import_dxf
# ---------------------------------------------------------------------------
def _fusion360_import_dxf(args: dict, db, user_id: str | None) -> dict:
    b64 = (args.get("dxf_b64") or "").strip()
    if not b64:
        return _bad("dxf_b64 is required (base64-encoded DXF file content)")
    plane = args.get("plane", "xy")
    if plane not in _PLANES:
        return _bad(f"plane must be one of {sorted(_PLANES)}")
    # strip whitespace/newlines that may have been introduced in transit
    b64 = "".join(b64.split())
    # validate before embedding
    try:
        base64.b64decode(b64)
    except Exception as e:  # noqa: BLE001
        return _bad(f"dxf_b64 is not valid base64: {e}")

    plane_expr = _PLANES[plane]
    code = (
        "import tempfile, os, base64\n"
        "app = adsk.core.Application.get()\n"
        "path = os.path.join(tempfile.gettempdir(), 'zhanlu_import.dxf')\n"
        f"open(path, 'wb').write(base64.b64decode('{b64}'))\n"
        "imp = app.importManager\n"
        f"opts = imp.createDXF2DImportOptions(path, {plane_expr})\n"
        "opts.isSingleSketchResult = True\n"
        "opts.isViewFit = True\n"
        "before = root.sketches.count\n"
        "res = imp.importToTarget(opts, root)\n"
        "try: os.remove(path)\n"
        "except Exception: pass\n"
        "print('IMPORT_OK' if res else 'IMPORT_FAIL', 'SKETCH_INDEX', root.sketches.count - 1, 'BEFORE', before)\n"
    )
    r = _call(code, db)
    if r.get("error"):
        return {"success": False, "error": r["error"], "retryable": True}
    out = r.get("result", "") or ""
    if "IMPORT_FAIL" in out:
        return {"success": False, "error": "Fusion failed to import the DXF.", "retryable": True}
    if "IMPORT_OK" not in out:
        return {"success": False, "error": "Unexpected import result: " + out[:300], "retryable": True}
    # parse SKETCH_INDEX
    idx = None
    if "SKETCH_INDEX" in out:
        try:
            idx = int(out.split("SKETCH_INDEX", 1)[1].strip().split()[0])
        except Exception:  # noqa: BLE001
            idx = None
    return {"success": True, "sketch_index": idx, "plane": plane, "stdout": out.strip()}


# ---------------------------------------------------------------------------
# 3. fusion360_make_drawing (backend-side, ezdxf — no Fusion call)
# ---------------------------------------------------------------------------
_SHAPE_TYPES = {"rect", "circle", "line", "polygon"}


def _add_shape(msp, shape, dx=0.0, dy=0.0):
    t = shape.get("type")
    if t == "rect":
        x, y = float(shape.get("x", 0)), float(shape.get("y", 0))
        w, h = float(shape.get("w", 0)), float(shape.get("h", 0))
        msp.add_lwpolyline(
            [(x + dx, y + dy), (x + w + dx, y + dy), (x + w + dx, y + h + dy), (x + dx, y + h + dy)],
            close=True,
        )
    elif t == "circle":
        cx, cy = float(shape.get("cx", 0)) + dx, float(shape.get("cy", 0)) + dy
        msp.add_circle((cx, cy), float(shape.get("r", 1)))
    elif t == "line":
        msp.add_line(
            (float(shape.get("x1", 0)) + dx, float(shape.get("y1", 0)) + dy),
            (float(shape.get("x2", 0)) + dx, float(shape.get("y2", 0)) + dy),
        )
    elif t == "polygon":
        pts = shape.get("points") or []
        msp.add_lwpolyline([(float(p[0]) + dx, float(p[1]) + dy) for p in pts], close=True)


def _add_dim(msp, dim, dx=0.0, dy=0.0):
    p1 = dim.get("p1"); p2 = dim.get("p2")
    if not p1 or not p2:
        return
    x1, y1 = float(p1[0]) + dx, float(p1[1]) + dy
    x2, y2 = float(p2[0]) + dx, float(p2[1]) + dy
    label = str(dim.get("label", ""))
    offset = float(dim.get("offset", 8))
    vx, vy = x2 - x1, y2 - y1
    length = (vx * vx + vy * vy) ** 0.5
    if length < 1e-6:
        return
    nx, ny = -vy / length, vx / length  # unit normal
    # dimension line (offset perpendicular from the p1-p2 segment)
    dl1 = (x1 + nx * offset, y1 + ny * offset)
    dl2 = (x2 + nx * offset, y2 + ny * offset)
    # extension lines
    msp.add_line((x1, y1), dl1)
    msp.add_line((x2, y2), dl2)
    # dimension line with end ticks (short perpendicular marks)
    msp.add_line(dl1, dl2)
    tick = offset * 0.15 + 0.5
    for p, s in ((dl1, 1), (dl2, -1)):
        msp.add_line(p, (p[0] + nx * 0 + (-ny) * tick * s, p[1] + ny * 0 + nx * tick * s))
    # label at midpoint, nudged out along the normal
    mx, my = (dl1[0] + dl2[0]) / 2, (dl1[1] + dl2[1]) / 2
    msp.add_text(label, height=max(2.0, offset * 0.35)).set_placement((mx + nx * 1.5, my + ny * 1.5))


def _fusion360_make_drawing(args: dict, db, user_id: str | None) -> dict:
    spec = args.get("spec")
    if isinstance(spec, str):
        import json as _json
        try:
            spec = _json.loads(spec)
        except Exception:  # noqa: BLE001
            return _bad("spec must be a valid JSON object")
    if not isinstance(spec, dict):
        return _bad("spec (object) is required")

    title = str(spec.get("title") or "Part")
    views = spec.get("views") or []
    dims = spec.get("dims") or []
    if not isinstance(views, list) or not views:
        return _bad("spec.views must be a non-empty list")

    try:
        import ezdxf
    except ImportError:
        return {"success": False, "error": "ezdxf is not installed in the backend.", "retryable": False}

    doc = ezdxf.new("R2010", setup=True)
    msp = doc.modelspace()

    # Arrange views horizontally.
    spacing = 160.0
    view_meta = []
    for i, view in enumerate(views):
        name = str(view.get("name") or f"VIEW {i + 1}")
        dx = i * spacing
        msp.add_text(name, height=5).set_placement((dx, 80))
        for shape in (view.get("shapes") or []):
            _add_shape(msp, shape, dx=dx)
        view_meta.append((name, dx))
        for dim in (view.get("dims") or []):
            _add_dim(msp, dim, dx=dx)
    # global dims (render at the origin / no view offset)
    for dim in dims:
        _add_dim(msp, dim)

    # Title block (bottom-left, modelspace — simple but legible).
    y0 = -90.0
    msp.add_line((-20, y0), (spacing * len(views) - 20, y0))
    msp.add_text(title, height=6).set_placement((-20, y0 - 12))
    msp.add_text(
        f"Units: {spec.get('units', 'mm')}   Scale: 1:1   Date: {datetime.utcnow().strftime('%Y-%m-%d')}   "
        f"Views: {len(views)}",
        height=3.5,
    ).set_placement((-20, y0 - 20))

    import tempfile
    path = tempfile.mktemp(suffix=".dxf")
    doc.saveas(path)
    with open(path, "rb") as f:
        dxf_bytes = f.read()
    try:
        os.remove(path)
    except Exception:  # noqa: BLE001
        pass

    name = (args.get("name") or f"{title.replace(' ', '_')}.dxf").strip()
    if not name.lower().endswith(".dxf"):
        name += ".dxf"
    url, size = _save_file(db, user_id, name, "dxf", dxf_bytes)
    return {
        "success": True,
        "file_url": url,
        "filename": name,
        "size_bytes": size,
        "views": [v[0] for v in view_meta],
    }


# ---------------------------------------------------------------------------
# Schemas & registration
# ---------------------------------------------------------------------------
def _schema(name, desc, props, required):
    return {
        "type": "function",
        "function": {
            "name": name,
            "description": desc,
            "parameters": {
                "type": "object",
                "properties": props,
                "required": required,
            },
        },
    }


registry.register(
    name="fusion360_export_geometry",
    schema=_schema(
        "fusion360_export_geometry",
        "Export the current Fusion 360 design to a file (STEP for CAD exchange, STL for 3D "
        "printing, OBJ mesh, IGES/SAT, or F3D native). Returns a download URL. "
        "Use this to hand the model to other tools or to 3D-print it.",
        {
            "format": {
                "type": "string",
                "enum": sorted(_EXPORT_FORMATS),
                "description": "Export format. Default 'step'.",
            },
            "name": {
                "type": "string",
                "description": "Optional output filename (e.g. 'm6_screw.step').",
            },
        },
        [],
    ),
    handler=_fusion360_export_geometry,
    category="cad",
    toolset="cad",
)

registry.register(
    name="fusion360_save",
    schema=_schema(
        "fusion360_save",
        "Save the current Fusion 360 design as a named .f3d file and remember it as the "
        "current project (persisted on the agent, so it survives across conversations). "
        "Returns a download URL and the project name. Use this when the user asks to save "
        "or after completing a build.",
        {
            "name": {
                "type": "string",
                "description": "Project/filename (e.g. 'shock_absorber'). '.f3d' is appended if missing.",
            },
        },
        ["name"],
    ),
    handler=_fusion360_save,
    category="cad",
    toolset="cad",
)

registry.register(
    name="fusion360_project",
    schema=_schema(
        "fusion360_project",
        "Return the current Fusion project — the filename last saved with fusion360_save. "
        "Call this at the START of a conversation to check whether a project was already "
        "saved, so you can tell the user which CAD file you're working on.",
        {},
        [],
    ),
    handler=_fusion360_project,
    category="cad",
    toolset="cad",
)

registry.register(
    name="fusion360_import_dxf",
    schema=_schema(
        "fusion360_import_dxf",
        "Import a 2D DXF file as a sketch onto a construction plane. Returns the new sketch_index; "
        "use fusion360_extrude or fusion360_revolve with that sketch_index to turn the 2D profile "
        "into a 3D solid. Read the DXF file bytes first (read_file), base64-encode them, and pass "
        "the result as dxf_b64.",
        {
            "dxf_b64": {
                "type": "string",
                "description": "Base64-encoded DXF file content.",
            },
            "plane": {
                "type": "string",
                "enum": sorted(_PLANES),
                "description": "Construction plane to place the sketch on. Default 'xy'.",
            },
        },
        ["dxf_b64"],
    ),
    handler=_fusion360_import_dxf,
    category="cad",
    toolset="cad",
)

registry.register(
    name="fusion360_make_drawing",
    schema=_schema(
        "fusion360_make_drawing",
        "Generate a dimensioned 2D engineering drawing (DXF) from a structured spec. Build the "
        "spec from the dimensions you already know (your tool-call history). "
        "spec.views = [{name, shapes:[{type:'rect'|'circle'|'line'|'polygon', ...}]}], "
        "spec.dims = [{type:'linear', p1:[x,y], p2:[x,y], label, offset}]. "
        "Returns a download URL to the DXF.",
        {
            "spec": {
                "type": "object",
                "description": (
                    "Drawing spec. {\"title\": str, \"units\": 'mm', \"views\": [{\"name\": str, "
                    "\"shapes\": [...]}], \"dims\": [{\"type\":\"linear\",\"p1\":[x,y],\"p2\":[x,y],"
                    "\"label\":str,\"offset\":num}]}. Shapes: rect{x,y,w,h}, circle{cx,cy,r}, "
                    "line{x1,y1,x2,y2}, polygon{points:[[x,y],...]}."
                ),
            },
            "name": {
                "type": "string",
                "description": "Optional output filename.",
            },
        },
        ["spec"],
    ),
    handler=_fusion360_make_drawing,
    category="cad",
    toolset="cad",
)
